### ISSUE TITLE
How to leave all rooms the socket is currently in and join only one room?

### ISSUE THREAD

**Issue by cedrick-ah** [socketio/socket.io#4906] opened 2023-12-25 18:13 UTC
### Discussed in https://github.com/socketio/socket.io/discussions/4905

<div type='discussions-op-text'>

<sup>Originally posted by **cedrick-ah** December 24, 2023</sup>
I'm using socket.io version 4.5.1, nodejs version 16

I'm trying to leave all rooms and subscribe to a new one, but I'm still receiving old events, I checked the content of io.of("/").adapter.rooms and when the socket join its added under the room but but when the socket leave the socket is not removed from the room.</div>

**Comment by haneenmahd** [comment] 2023-12-31 21:42
Could you provide some example reproducible code that will allow to understand how you're doing it?

**Comment by darrachequesne** [comment] 2024-01-05 10:54
Closed as duplicate of https://github.com/socketio/socket.io/discussions/4905.

**Closed by darrachequesne** 2024-01-05 10:54 UTC
