### ISSUE TITLE
Why overwrites query by handshake?

### ISSUE THREAD

**Issue by imcuttle** [socketio/socket.io#3592] opened 2020-05-01 10:34 UTC
When I use `socket.io` multiplexing feat, setup ws connection by query `{type: ''}`, and then I updated query `{type: 'share'}`, but it not received in server side, I saw code as follow

https://github.com/socketio/socket.io/blob/2a1aa1c59c39e9a2b6a0e1996b6ff0cceb1ec61d/lib/socket.js#L116-L120

So why overwrites query by handshake? And now I use `forceNew=true` to disable multiplexing feat

**Comment by sebamarynissen** [comment] 2020-11-07 07:54
It's a bug that I've encountered as well. I still need to test if it's fixed in v3, but have a look at #3495 for a workaround in v2.

**Comment by darrachequesne** [comment] 2020-11-08 00:31
Yes, that's a known quirk in Socket.IO v2, which should be fixed in v3. The explanation can be found in the migration guide: https://socket.io/docs/migrating-from-2-x-to-3-0/#Add-a-clear-distinction-between-the-Manager-query-option-and-the-Socket-query-option

As a workaround for Socket.IO v2, you can explicitly create your Socket instance on the client-side.

Instead of:

```js
const socket = io({
  query: {
     token: "abc"
  }
});
```

You can write:

```js
const { Manager } = require("socket.io-client");

const manager = new Manager();

const socket = manager.socket("/", {
  query: {
    token: "abc"
  }
});
```

In this case, you can update the `socket.query` object, it should be reflected on the server-side upon reconnection (and not overriden by the Manager `query` option):

```js
// client-side
socket.query.token = "def";

// server-side
io.on("connect", (socket) => {
  console.log(socket.handshake.query.token); // def
});
```

**Closed by darrachequesne** 2020-11-08 00:31 UTC

**Comment by sebamarynissen** [comment] 2020-11-08 08:44
@darrachequesne Would there be a possibility to merge #3496 into the 2.4.x branch? It looks to me that the problem is simply that the http query overrides the socket specific query, while the socket specific query should actually override the http query instead (see #3495).
