### ISSUE TITLE
[Error] Cannot read property 'sid' of undefined

### ISSUE THREAD

**Issue by matiaslopezd** [socketio/socket.io#3718] opened 2020-12-02 03:11 UTC
Hi! I migrated to the latest version 3.0.3. But **on the client-side**, I'm getting this error immediately after connecting:

**error**
```js
socket.js:189 Uncaught TypeError: Cannot read property 'sid' of undefined
    at Socket.onpacket (socket.js:189)
    at Manager.<anonymous> (index.js:21)
    at Manager../node_modules/component-emitter/index.js.Emitter.emit (index.js:145)
    at Manager.ondecoded (manager.js:209)
    at Decoder.<anonymous> (index.js:21)
    at Decoder../node_modules/component-emitter/index.js.Emitter.emit (index.js:145)
    at Decoder.add (index.js:117)
    at Manager.ondata (manager.js:201)
    at Socket.<anonymous> (index.js:21)
    at Socket../node_modules/component-emitter/index.js.Emitter.emit (index.js:145)
```

**client-side**
```js
const options = {
 path: '/ws',
 query: { accessToken: 'XXXX', id: 'XXXXXX' },
 transports: ['websocket']
};

const socket = io("http://localhost:3030/my-namespace", options);
socket.on("connection:error", payload => console.log(payload)); // <-- This not listen but received (Network Tab)
socket.on("disconnect", reason => console.log(reason)); // <-- This works
```

**server-side**
```js
const options = {
  pingTimeout: 5000,
  pingInterval: 5000,
  path: '/ws/'
};

const server = require('http').createServer();
const io = require('socket.io')(server, options);
server.listen(3000);
```

Related question: https://stackoverflow.com/questions/64785024/uncaught-typeerror-cannot-read-property-sid-of-undefined-socket-io-client 

What I'm doing wrong? Thanks!

**Comment by darrachequesne** [comment] 2020-12-02 08:12
It seems you are using a v3 client with a v2 server, which are not compatible. Could you please check?

**Comment by matiaslopezd** [comment] 2020-12-02 14:53
@darrachequesne I'm using 3.0.3 on server-side and client-side. The issue doesn't allow listen to custom events, only default like `connect` and `disconnect`.

**Comment by bpofficial** [comment] 2020-12-03 07:14
can also confirm this is happening with me.

**Comment by darrachequesne** [comment] 2020-12-03 13:38
@matiaslopezd hmm... I am not able to reproduce: https://github.com/socketio/socket.io-fiddle/tree/issues-3718

**Comment by qanastek** [comment] 2020-12-14 22:14
@darrachequesne I love you  ❤️ ❤️ ❤️ ❤️ ❤️

**Comment by darrachequesne** [comment] 2020-12-17 12:14
For future readers: this issue happened when one tries to reach a v2 Socket.IO server with a v3 client (which is not possible due to incompatible exchange protocols). We have added a check for that case (https://github.com/socketio/socket.io-client/commit/ec1f8c3474b54600420487a0554cb195cc78f2bc), so this issue should be fixed.

In order to upgrade an existing deployment, please see https://socket.io/docs/v3/migrating-from-2-x-to-3-0/#How-to-upgrade-an-existing-production-deployment

**Closed by darrachequesne** 2020-12-17 12:14 UTC
