### ISSUE TITLE
use pm2 and socket.io-redis connection is wrong

### ISSUE THREAD

**Issue by shuxuezhang** [socketio/socket.io#2678] opened 2016-09-11 14:11 UTC
when  run node app.js everything is ok  ,pm2 start app.js -i 1  is also .
when process more than 2 ，Connection is very slow and i can't emit message.
who know where is wrong? thanks 

//app.js

```
var io = require('socket.io')(6001);
var port = 6379
var host = 'localhost'
var redis = require('redis').createClient;
var adapter = require('socket.io-redis');
var pub = redis(port, host, { auth_pass: "pwd" });
var sub = redis(port, host, { return_buffers: true, auth_pass: "pwd" });
io.adapter(adapter({ pubClient: pub, subClient: sub }));


console.log('开始了  ')
var game = io.of('/game')
game.on('connection', function(socket){
    console.log(socket.id)
    console.log(socket.handshake.query)

    socket.on('messages',function(data){
        console.log(data,'message')
        socket.emit('messages',data)

    })
    socket.on('reconnected',function(data){

        console.log(data,'message')
        socket.emit('messages',data)

    })
    socket.on('disconnect',function(){
    })
});

```

**Comment by lucaswxp** [comment] 2016-09-12 12:38
I also could not get it working in cluster mode, I had to create separate pm2 processes and use nginx ip_hash so clients are redirected to same servers.

**Comment by gnujeremie** [comment] 2016-09-14 07:09
you may find informations here : http://socket.io/docs/using-multiple-nodes/#

**Comment by lcalvy** [comment] 2016-09-23 09:54
Hi @shuxuezhang, 

We have implemented a pm2 like cluster plugin that we use in production.
https://github.com/CoorpAcademy/cluster-sticky

**Comment by darrachequesne** [comment] 2017-01-12 16:57
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).

**Closed by darrachequesne** 2017-01-12 16:57 UTC
Labels: Closed due to inactivity

**Comment by JamesStark-wasp** [comment] 2020-08-25 08:30
anybody know how to male this work in above code snippets because it same for me and not working in my server.
