### ISSUE TITLE
CORS Issue on Socket.io 

### ISSUE THREAD

**Issue by Raeeddoesgaming** [socketio/socket.io#3696] opened 2020-11-16 03:19 UTC
There are multiple cors issues when using the current version. I've tried to use it but I have had to revert back to 1.2.0 because I've gotten multiple CORS errors on my chat application. This means that I have to use middleware which is a lot of work. I don't really know why 1.2.0 works and this one doesn't but someone probably knows.

**Comment by ronsivan1** [comment] 2020-11-16 09:35
I'm having the same issue, 2.3.0 also works for server and client

**Comment by fabiojsousa** [comment] 2020-11-16 18:58
I have the same issue with version 3.0.1, I have to do the downgrade to version 2.3.0.

**Comment by darrachequesne** [comment] 2020-11-16 22:44
Hi!

There is a breaking change regarding CORS in v3, could you please check:

- https://socket.io/docs/v3/migrating-from-2-x-to-3-0/#CORS-handling
- https://socket.io/docs/v3/handling-cors/

Please tell me if something is not clear enough. Thanks!

**Comment by AmauryD** [comment] 2020-11-17 14:58
Same problem here , i've setup a socket.io server on port 3000

My Server config : 

```js
const CORSOptions = {
        allowedHeaders: ["Content-Type", "Authorization"],
        methods: ["GET", "POST", "PUT", "PATCH", "DELETE"],
        origin: "http://localhost:4200",
        credentials: true
    };

    const io = new Server(server, {
        cors: CORSOptions
    });
    io.listen(3000);
```

The server is responding well in browser
http://localhost:3000/socket.io/?EIO=4&transport=polling&t=NNMfM7o
`0{"sid":"30nKEOKaMi8YMIllAAAH","upgrades":["websocket"],"pingInterval":25000,"pingTimeout":5000}`

But in my frontend app on http://localhost:4200 it's giving me this error (typical CORS error):

![image](https://user-images.githubusercontent.com/9933000/99404913-7083a280-28ec-11eb-90b3-19d86be936d4.png)

Client app code:

```js
    const socket = io("http://localhost:3000");
    console.log("init");
    socket.on('connect', function(){
      console.log("connected");
      socket.on('event', function(data){console.log(data)});
      socket.on('disconnect', function(){console.log("disconnected")});
    });
```

**Comment by darrachequesne** [comment] 2020-11-18 00:17
Hi @AmauryD , could you please check with `socket.io@3.0.2`? There was a quite surprising behavior in previous versions, where the constructor options were not properly forwarded.

In your example:

```
// does not work until socket.io@3.0.2
const io = new Server(server, {
  cors: CORSOptions
});
io.listen(3000);

// does work in all versions
const io = new Server(server, {});
io.listen(3000, {
  cors: CORSOptions
);
```

This should be fixed by https://github.com/socketio/socket.io/commit/43705d7a9149833afc69edc937ea7f8c9aabfeef.

**Comment by AmauryD** [comment] 2020-11-18 13:02
> 
> 
> Hi @AmauryD , could you please check with `socket.io@3.0.2`? There was a quite surprising behavior in previous versions, where the constructor options were not properly forwarded.
> 
> In your example:
> 
> ```
> // does not work until socket.io@3.0.2
> const io = new Server(server, {
>   cors: CORSOptions
> });
> io.listen(3000);
> 
> // does work in all versions
> const io = new Server(server, {});
> io.listen(3000, {
>   cors: CORSOptions
> );
> ```
> 
> This should be fixed by [43705d7](https://github.com/socketio/socket.io/commit/43705d7a9149833afc69edc937ea7f8c9aabfeef).

It works with the 3.0.2 release !
Thank you very much 😄

**Closed** 2020-11-19 01:15 UTC

**Comment by cassels** [comment] 2020-11-24 14:28
From what I gather of @AmauryD's comment above the following should work on `>3.0.2`? However, I'm seeing the same errors highlighted above on `3.0.3`. Has a regression been introduced here?
```
const io = new Server(server, {
  cors: CORSOptions
});
io.listen(3000);
```
Note that the suggested workaround prior to `3.0.2` works fine for me on `3.0.3` for now.
```
const io = new Server(server, {});
io.listen(3000, {
  cors: CORSOptions
);
```

**Comment by darrachequesne** [comment] 2020-11-25 13:24
@cassels I am not able to reproduce the issue you are describing: https://github.com/socketio/socket.io-fiddle/tree/cors

Could you please check?

**Comment by cassels** [comment] 2020-12-06 12:48
Hey @darrachequesne, thanks for looking into it. It seems you are right. Sorry for the delay, but noticed it within a personal project and haven't been able to give it much more time until today and it's working without issue now – must have been some other interference causing me to have issues.
