### ISSUE TITLE
Unexpected syntax error

### ISSUE THREAD

**Issue by sumanta-ghosh** [socketio/socket.io#2515] opened 2016-04-06 13:45 UTC
When I am trying to install socket.io in ubuntu 14.04 server I got this issue
I got the error when I run :

```
 sudo npm install socket.io 
```

but it's fine I use the lower version like this 

```
sudo npm install socket.io@1.4.4
```

![screenshot 2016-04-06 19 11 02](https://cloud.githubusercontent.com/assets/2699051/14318709/cf09c07a-fc2b-11e5-8863-b45bec953f50.png)

**Comment by nkzawa** [comment] 2016-04-11 14:19
umm. I can't reproduce. What versions of node and npm do you use ? Does this occur only on ubuntu ?

**Comment by darrachequesne** [comment] 2017-01-12 15:58
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).

**Closed by darrachequesne** 2017-01-12 15:58 UTC
Labels: Closed due to inactivity
