### ISSUE TITLE
socket.broadcast calling itself also

### ISSUE THREAD

**Issue by Rud156** [socketio/socket.io#3165] opened 2018-01-28 13:18 UTC
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour
`socket.brodcast.emit('SomeMesage', data);`
If the method is called fast enough (60fps), The data is sent back to itself also. This most probably occurs due to collision.

### Steps to reproduce (if the current behavior is a bug)
Have 2 canvas move an object left to right send data to each other on the same channel. Both will recieve each other's data as will their own data. I know that this is an edge case and sockets should not be used like this. But looks like a bug.

### Expected behaviour
`socket.brodcast.emit('SomeMesage', data);`
This is supposed to send data to all other sockets connected except itself.

### Setup
- OS: ALL
- browser: ALL
- socket.io version: Lastest Stable

**Comment by agroves333** [comment] 2018-01-29 00:09
I'm experiencing the same thing. I'm using this with the intent to broadcast to everyone in the room except myself. However, I'm also getting my clients on() listener firing.

Server:
```
io.on('connection', socket => {
  console.info('Socket connected!');

  socket.on('board/join', boardId => {
    console.info(`joined board: ${boardId}`);
    socket.join(`board${boardId}`);
  });
  socket.on('card/create', card => {
    const room = `board${card.board}`;
    console.info(`create card in room: ${room}`, card);
    socket.broadcast.to(room).emit('card/create', card);
  });
});
```

Client:
```
socket.emit('board/join', this.props.boardId);
socket.on('lane/create', lane => {
    this.props.createLaneSuccess(lane);
});
socket.on('card/create', card => {
    this.props.createCardSuccess(card);
});
```

What am I missing?

**Comment by kitce** [comment] 2018-03-25 20:49
I am having the same problem too.

Does anyone have a temporary workaround?

**Comment by kitce** [comment] 2018-03-26 10:19
It seems adding a short delay could solve the problem (temporary)

```
setTimeout(() => {
  socket.to(room).emit('event', 'message');
}, 100);
```

**Comment by yhydra** [comment] 2019-04-07 23:49
im also experiencing this but only for a specific message. its weird!

**Comment by yhydra** [comment] 2019-04-07 23:52
adding a delay doesnt work for me, it still sends it to self

**Comment by darrachequesne** [comment] 2021-02-19 23:30
Closed as unable to reproduce.

**Closed by darrachequesne** 2021-02-19 23:30 UTC

**Comment by 123om123** [comment] 2021-04-08 16:16
@Rud156  I'm having the same problem. Did you find out how to fix it? the time delay didn't work for me.

**Comment by 123om123** [comment] 2021-04-08 16:17
> adding a delay doesnt work for me, it still sends it to self

It didn't work for me either, did you find a solution?

**Comment by darrachequesne** [comment] 2021-04-09 07:13
@123om123 are you able to reproduce consistently? Could you please share the code? Thanks!

**Comment by 123om123** [comment] 2021-04-09 15:44
Sure!

**Note:** _The bug only happens in version 4_

### Server-side
```
io.on("connection", function (socket) {
  console.log(socket.id + " joined the server on " + new Date().toLocaleString());
  .
  .
  .
  socket.on("updated player info", function (playerInfo) {
    socket.to(playerInfo.world.split("_").join(" ")).emit("players updated info", playerInfo);
   });
  .
  .
  .
});
```

### Client-side
```
//sending the players info

socket.emit("updated player info", {
    id: mainPlayer.id,
    x: mainPlayer.x,
    y: mainPlayer.y,
    prevX: mainPlayer.prevX,
    prevY: mainPlayer.prevY,
    health: mainPlayer.health,
    sx: mainPlayer.sx,
    sy: mainPlayer.sy,
    score: mainPlayer.score,
    ammoLeft: mainPlayer.ammoLeft,
    reloading: mainPlayer.reloading,
    timesReloaded: mainPlayer.timesReloaded,
    needsToReload: mainPlayer.needsToReload,
    bulletList: mainPlayer.bulletList.length,
    username: mainPlayer.username,
    email: mainPlayer.email,
    loggedIn: mainPlayer.loggedIn,
    afk: mainPlayer.afk,
    drawn: mainPlayer.drawn,
    lastDirection: mainPlayer.lastDirection,
    clipWidth: mainPlayer.width,
    clipHeight: mainPlayer.height,
    above: mainPlayer.above,
    below: mainPlayer.below,
    world: currentWorld,
  });
.
.
.
//receiving the player's info from the server

socket.on("players updated info", function (playerData) {
  PlayerList.forEach((player) => {
    if (player.id == playerData.id) {
      player.x = playerData.x;
      player.y = playerData.y;
      player.prevX = playerData.prevX;
      player.prevY = playerData.prevY;
      player.health = playerData.health;
      player.sx = playerData.sx;
      player.sy = playerData.sy;
      player.score = playerData.score;
      player.ammoLeft = playerData.ammoLeft;
      player.reloading = playerData.reloading;
      player.timesReloaded = playerData.timesReloaded;
      player.needsToReload = playerData.needsToReload;
      player.username = playerData.username;
      player.email = playerData.email;
      player.loggedIn = playerData.loggedIn;
      player.afk = playerData.afk;
      player.drawn = playerData.drawn;
      player.lastDirection = playerData.lastDirection;
      player.width = playerData.clipWidth;
      player.height = playerData.clipHeight;
      player.above = playerData.above;
      player.below = playerData.below;
    }
  });
});
```

**Comment by darrachequesne** [comment] 2021-04-09 21:32
@123om123 sorry I wasn't clear enough, could you please share provide a complete example that we can run? You can fork the project here: https://github.com/socketio/socket.io-fiddle

**Comment by ismailsemihsenturk** [comment] 2023-04-11 16:25
I have the same problem. 
Here's my repo: https://github.com/ismailsemihsenturk/React_Native_WebRTC_ChatApp you need at least 2 phone (1 emulator and 1 physical phone would do the work too).

**Comment by GiovaneW** [comment] 2024-11-12 18:06
Well, i thing i'm find the possible trouble.
Client are initialized with a single and unique room created by socket.io server to every client, in my case, when i'm force the client to leave this "main room" created by lib and join the client on a custom room, the broadcast event make a itself calling too. Otherwise, when i'm only join a client on specific room without leaving the "main room", it's works fine.
