### ISSUE TITLE
After upgrade to the latest version (Java Android + Server) the old sockets are not disconnecting anymore.

### ISSUE THREAD

**Issue by sandro-csimas** [socketio/socket.io#2392] opened 2016-01-16 02:33 UTC
Server code:

```
circles.on('connection', function(socket) {
  var userId = socket.request._query.user;
  logger.debug('Connecting user %d', userId);
  var user =  userService.getUser(userId);
  if(user) {   
    socket.emit('connected');
    logger.debug('User %d connected (Socket %s)', user.id, socket.id);
    addSocket(user, socket); // Adds the socket to the list of sockets of the user

    socket.on('disconnect', function() {
      logger.debug('User %d disconnected (Socket %s)', user.id, socket.id);
      removeSocket(user, socket); // Removes the socket from the list of sockets of the user
    });
  } else {
    logger.error('User %d does not exist', userId);
    socket.disconnect();
  }
});
```

Server log:

```
2016-01-15T18:10:45.448Z - ESC[34mdebugESC[39m: User 1 connected (Socket /circles#h5OXbKNB2odID4NPAAAA)
2016-01-15T18:10:45.449Z - ESC[34mdebugESC[39m: Sockets of user 1: /circles#h5OXbKNB2odID4NPAAAA

2016-01-15T18:10:53.078Z - ESC[34mdebugESC[39m: User 1 disconnected (Socket /circles#h5OXbKNB2odID4NPAAAA)
2016-01-15T18:10:53.078Z - ESC[34mdebugESC[39m: Sockets of user 1: 

2016-01-15T18:11:11.707Z - ESC[34mdebugESC[39m: User 1 connected (Socket /circles#N26DdFoLABUh9PNkAAAE)
2016-01-15T18:11:11.708Z - ESC[34mdebugESC[39m: Sockets of user 1: /circles#N26DdFoLABUh9PNkAAAE

2016-01-15T18:13:30.476Z - ESC[34mdebugESC[39m: User 1 connected (Socket /circles#zE027HKtvwZINFNRAAAF)
2016-01-15T18:13:30.479Z - ESC[34mdebugESC[39m: Sockets of user 1: /circles#N26DdFoLABUh9PNkAAAE,/circles#zE027HKtvwZINFNRAAAF

// AFTER FIVE HOURS 

2016-01-15T23:20:18.825Z - debug: User 1 connected (Socket /circles#0dBM9LYIkJvEgVQ1AAD_)
2016-01-15T23:20:18.825Z - debug: Sockets of user 1: /circles#b_wMYp4qv4bniqvpAABH,/circles#8HK94jcSdeATuKm7AAB0,/circles#8HK94jcSdeATuKm7AAB0,/circles#5aM-IbOXFROoZNA8AADj,/circles#Hp9-gHsgbICbOi6vAAD-,/circles#0dBM9LYIkJvEgVQ1AAD_

2016-01-15T23:20:44.327Z - debug: User 1 disconnected (Socket /circles#5aM-IbOXFROoZNA8AADj)
2016-01-15T23:20:44.328Z - debug: Sockets of user 1: /circles#b_wMYp4qv4bniqvpAABH,/circles#8HK94jcSdeATuKm7AAB0,/circles#8HK94jcSdeATuKm7AAB0,/circles#Hp9-gHsgbICbOi6vAAD-,/circles#0dBM9LYIkJvEgVQ1AAD_
```

See how many sockets are created. This is another issue in when uses Socket.io in Android, but before upgrade all the old Sockets were disconnected after some seconds.

Java code is simple. Singleton with a Socket instance:

```
private void setupSocket() {
  options = new IO.Options();
  options.secure = true;
  try {
    socket = IO.socket(Configuration.IO_URL, options);
  } catch(URISyntaxException e) {
    Log.e(TAG, "Error creating socket instance", e);
    throw new APIException(e);
  }
}

public synchronized void connect(User user) {
  options.query = "user=" + user.getId();
  socket.connect();
  enableEvents(true); // Add listeners of events
}

public void disconnect() {
  socket.disconnect();
  enableEvents(false); // Removes all listeners from events using socket.off()
}
```

**Comment by nkzawa** [comment] 2016-01-17 06:47
Do you mean old sockets don't get disconnected on server, even sockets get disconnected on Android clients? Could you remove app-specific code from your example and simplify it to reproduce the problem?

**Comment by sandro-csimas** [comment] 2016-01-17 19:36
@nkzawa, i simplify the server code. 
Before upgrade my functions addSocket and removeSocket was working very well and I saw a maximum of three sockets per user. These sockets were disconnect after some seconds and only one stays connected. With the server upgrade it seems that the disconnect function is not called sometimes.
This log shows what i mentioned above:
````
2016-01-15T23:20:18.825Z - debug: User 1 connected (Socket /circles#0dBM9LYIkJvEgVQ1AAD_)
2016-01-15T23:20:18.825Z - debug: Sockets of user 1: /circles#b_wMYp4qv4bniqvpAABH,/circles#8HK94jcSdeATuKm7AAB0,/circles#8HK94jcSdeATuKm7AAB0,/circles#5aM-IbOXFROoZNA8AADj,/circles#Hp9-gHsgbICbOi6vAAD-,/circles#0dBM9LYIkJvEgVQ1AAD_
````
The another problem is that the same socket ID is connecting more than once. Notice that the second and the third socket.id are the same in the user socket list. The connection function can be called more than once for the same socket?
````
var addSocket = function(user, socket) {
  var socketsIds = socketsIdsByUser[user.id]
  if(!socketsIds) {
    socketsIds = [];
    socketsIdsByUser[user.id] = socketsIds;
  }
  socketsIds.push(socket.id);
  logger.debug('Sockets of user %s: %s', user.id, socketsIds.toString());
};

var removeSocket = function(user, socket) {
  var socketsIds = socketsIdsByUser[user.id];
  if(socketsIds) {
    var index = _.indexOf(socketsIds, socket.id);
    socketsIds.splice(index, 1);
    logger.debug('Sockets of user %s: %s', user.id, socketsIds.toString());
  }
};
````
I will watch my logs for longer and make more tests.

**Comment by nkzawa** [comment] 2016-01-18 03:31
Thanks, but still difficult to understand your example and logs because of `User`. Can you test if it occurs with node.js client? I think the problem is mainly on server side, because server should handle connections properly even if clients do something wrong.

**Comment by sandro-csimas** [comment] 2016-01-18 15:09
The code is very simple. Basicaly i store the sockets in a MAP where the key is the user ID and the value is an array of sockets of the user. After when i want to do a broadcast, i retrieve the connected socket of a given user using this MAP.

When the socket emits the connection event, i check the user ID handshake attribute (````socket.request._query.user````) and add this socket on the MAP.
````
{user: 1, sockets: [/circles#qeXArsxNLWNYV-NcAAN7]} // After adding
````
When the socket emits the disconnect event, i remove the socket from the MAP.
````
{user: 1, sockets: []} // After removing
````
I don't know what is happening, but some sockets are not removed from the MAP. According to this think that the disconnect event is not called sometimes. Resuming, this is the code:
````
circles.on('connection', function(socket) {
    addSocket(user, socket); // Adds the socket to the list of sockets of the user
    socket.on('disconnect', function() {
        removeSocket(user, socket); // Removes the socket from the list of sockets of the user
    });
});
````
After several hours this is happening:
````
2016-01-18T14:44:10.904Z - debug: 4 of 28 indexed sockets are connected: /circles#4aO3wn5TS4hrtyyaAAOS,/circles#a1Z2pDeTvrEU3TyFAAOr,/circles#kJ-3woNnxX-_oJDKAAOs,/circles#9hQNLd4DcN64-g3WAAOt
````
I have 4 users testing the app.
4 is the number of total sockets connected (This number is right - _.size(namespace.connected)) 
28 is the number of sockets on the MAP (This number is should be 4).

I will downgrade from 1.4.4 to 1.3.7 and i will verify this behavior aagain.

**Comment by sandro-csimas** [comment] 2016-01-19 01:17
Dowgrading its working correctly with the same code...
```
2016-01-18T14:50:42.321Z - debug: 4 of 4 indexed sockets are connected: lUsFSpNOZPn9ciFVAAAG,X8k4aCCQaqRI-zpaAAAM,a4rdT-xXTnbhMlSFAAAN,R3OHDezXca2_pzdjAAA
````
Ten hours later...
````
2016-01-19T01:15:42.480Z - debug: 6 of 6 indexed sockets are connected: cDv2s-44Bt0_UwlpAATV,08pB4BYV13hZcZnjAATZ,hQdtPMxnCDQbKUdSAATb,P2ks10L9biuujbghAATc,ujJaj3ruooSZ7jxBAATe,X2fIWpRSyqVFB5qPAATf
````

**Comment by oniono** [comment] 2016-01-19 01:17
NAVER - http://www.naver.com/
--------------------------------------------

oniono@naver.com 님께 보내신 메일 <Re: [socket.io] After upgrade to the latest version (Java Android + Server) the old sockets are not disconnecting anymore. (#2392)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by nkzawa** [comment] 2016-01-29 14:14
Maybe this is because the value of `socket.id` was changed on 1.4.x. `socket.id` is different on each namespace now. Please fix your app if it's the cause.

**Comment by darrachequesne** [comment] 2017-01-12 15:55
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).

**Closed by darrachequesne** 2017-01-12 15:55 UTC
Labels: Closed due to inactivity
