### ISSUE TITLE
Sessionid not cleared on disconnect

### ISSUE THREAD

**Issue by zlokomatic** [socketio/socket.io#2396] opened 2016-01-18 16:46 UTC
Hey,

if someone tries to leave a room in the disconnect event then the sid is not cleared from the adapter.

I made a small example:

https://gist.github.com/zlokomatic/df4a88d62136ee5ec016

**Comment by samuel281** [comment] 2016-01-21 05:20
It's because socket.leave calls adapter.del inside and socket.onclose calls adapter.delAll. 

In the adapter.del, you can see it actually initialize sid property and never clears it.
````    
    //https://github.com/socketio/socket.io-adapter/blob/master/index.js#L62
    this.sids[id] = this.sids[id] || {};
````

And adapter.delAll clears all props at the bottom line
````
//https://github.com/socketio/socket.io-adapter/blob/master/index.js#L90
delete this.sids[id];
````

But I don't think that's a big deal.

You don't have any reason to manually call socket.leave in the disconnect event handler.
http://socket.io/docs/rooms-and-namespaces/#disconnection

**Comment by darrachequesne** [comment] 2017-01-12 15:55
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).

**Closed by darrachequesne** 2017-01-12 15:55 UTC
Labels: Closed due to inactivity
