### ISSUE TITLE
socket.io failing over time for Chrome and Firefox

### ISSUE THREAD

**Issue by kunalchaudhary23** [socketio/socket.io#3461] opened 2019-06-27 20:59 UTC
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

We cannot reproduce this reliably, but this is a description of our server setup and issue.

We are running socket.io 2.2.0 on a Node.JS/Express server.

After about 12 hours our server does not respond to emissions from clients on desktop Chrome and Firefox. It continues to function on Edge, Safari, and mobile Chrome/Safari.

For example:

Server: 

    io.on('connection', (socket) => {
        socket.on(‘test’, (data) => {
           console.log(“This is a test”)
        })
    })

Client:

`this.socket.emit(‘test’)`

In this example, we see the expected behavior during the first 12 or so hours of the server’s uptime. “This is a test” is fired as soon as the client emits.

After that, perhaps due to gradual load on the server (though we typically never have more than 20 clients connected at once), the server stops listening to the client. Despite verifying that the client has emitted ‘test’, the server never logs “This is a test”. Again, this only occurs on desktop Chrome and desktop Firefox.  

This seems odd because if the server was overloaded - it should recover when the number of clients goes down. In addition, why would excess load suddenly permanently disable the ability for Chrome and Firefox to send emissions to our server? We know that the websocket connection is being established from the client by looking at the network logs. We also see that the connection is sending pings but never receiving pongs from the server.

### Expected behaviour

Chrome and Firefox sockets continue to operate as normal.

### Setup
- OS: Ubuntu 18.04
- browser: Desktop Chrome, Desktop Firefox
- socket.io version: 2.2.0

**Comment by chevett** [comment] 2019-08-02 23:22
I'm seeing this as well after upgrading from 1.4 to 2.2.0.  If I use [artillery](https://github.com/artilleryio/artillery) to hit my local socketio server everything appears fine.  However, after opening and closing a couple thousand connections I can no longer get a new connection from chrome(75.0.3770.142) or firefox(68.0.1).  If I then try artillery again, it is still able to obtain new connections.

I saw this ticket a couple weeks ago, but did not believe it to be possible.  Anyway, I installed the "gnome-web" browser and that odd browser is indeed able to obtain a new connection when firefox/chrome cannot.

More specifically, I am attempting to connect to a namespace.  It appears I might be connecting but not joining the namespace?

Below is what it looks like in chrome:
![image](https://user-images.githubusercontent.com/1141615/62403393-cc40e580-b55a-11e9-8043-396fa4a25d6d.png)

When successful there is normally another /rider line followed by much more data.  

On the server side, I have logging in my very first middleware function, but nothing shows up when trying from chrome/firefox.


My client options look like this: 
```
 {
		forceNew: true,
		transports: ['websocket'],
		upgrade: false,
}
```

**Comment by Xwhat** [comment] 2020-05-22 09:11
If you don't restrict transport to `websocket` only (server & client side) it will still works on firefox/chrome but it will use `XHR` instead of `websocket`.

**Comment by darrachequesne** [comment] 2020-07-09 10:01
Without a proper way to reproduce, that will indeed be hard to debug the issue..

@chevett your example is weird indeed. Besides is what you should have:

![image](https://user-images.githubusercontent.com/13031701/87025507-ccba1580-c1da-11ea-9181-2590110cb65d.png)

`0{"sid"...` => Engine.IO connect packet sent by the server
`40/rider,` => Socket.IO connect packet sent by the client
`40` => Socket.IO connect packet for the default namespace sent by the server
`40/rider,` => Socket.IO connect packet for the rider namespace sent by the server
`2` => Engine.IO ping packet sent by the client
`3` => Engine.IO pong packet sent by the server

You're missing both the connection to the namespace (`40/rider,`) and the pong response (`3`). Do you have any middleware that could throw/not call `next()`?

@kunalchaudhary23 are you using the default WebSocket server ([ws](https://github.com/websockets/ws)) or `uws`?

**Comment by David-Good-Enough** [comment] 2020-07-09 10:48
Since i updated socket io package, i don't have this issue anymore (server running since 3 weeks  now without issues)

**Comment by darrachequesne** [comment] 2020-07-09 11:07
@David-Good-Enough good news!

Let's close this issue then. @chevett could you please check my [comment](https://github.com/socketio/socket.io/issues/3461#issuecomment-656034559), and open a new issue if needed? Thanks!

**Closed by darrachequesne** 2020-07-09 11:07 UTC
Labels: question

**Comment by chevett** [comment] 2020-07-09 11:46
We were working around this issue by restarting the our app fairly often, but we stopped that a while ago and everything is running as expected again. Thank you very much :+1:
