### ISSUE TITLE
socket.rooms is not an array 

### ISSUE THREAD

**Issue by hstarorg** [socketio/socket.io#2495] opened 2016-03-17 16:11 UTC
In server code, socket.rooms is not an array ,that is a object.
When I use socket.join('xxx'), socket.rooms can't be set.

I will get rooms with `socket.adapter.rooms`, it's different to [api doc](http://socket.io/docs/server-api/).

**Comment by cloakedninjas** [comment] 2016-04-02 18:01
Just checkout out a project that hasn't been updated for a few months to find this breaking change

`TypeError: socket.rooms.indexOf is not a function`

Original version was 1.3.7 so it looks like Socket.io should have gone to v2 at some point

**Comment by Jokero** [comment] 2016-04-11 08:13
@rauchg ping

**Comment by magicdawn** [comment] 2016-05-29 08:12
`socket.adapter.rooms` is all rooms. haha
`socket.join('xxx')` is a asynchronous, just get `socket.rooms` in the callback ...

**Comment by magicdawn** [comment] 2016-05-29 08:13
And in the document on socket.io website. it's still 
> `socket.rooms` is an Array

**Comment by hstarorg** [comment] 2016-05-29 15:38
@magicdawn callback will be called on join room succeed.

**Comment by darrachequesne** [comment] 2017-01-12 16:02
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).

**Closed by darrachequesne** 2017-01-12 16:02 UTC
Labels: Closed due to inactivity
