### ISSUE TITLE
Socket.IO HTTPS CloudFlare

### ISSUE THREAD

**Issue by stalkerdenrus** [socketio/socket.io#2642] opened 2016-08-12 16:57 UTC
Hello. Tried ports that recommends CloudFlare:
For requests made via HTTPS:
443
2053
2083
2087
2096
8443
Users will still receive 525 error. You can either help me?

**Comment by MaffooBristol** [comment] 2016-08-25 17:19
Are you sure this is a socket.io issue? What happens when you try and connect normally via 'https://', does it also have the same issue?

According to [this page from cloudflare](https://support.cloudflare.com/hc/en-us/articles/200278659-Error-525-SSL-handshake-failed), it seems to be to do with full ssl not working, for example if your server certificate is invalid!

**Comment by mpgn** [comment] 2016-09-02 20:55
same error for me !

**Comment by darrachequesne** [comment] 2017-01-12 16:56
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).

**Closed by darrachequesne** 2017-01-12 16:56 UTC
Labels: Closed due to inactivity
