### ISSUE TITLE
Unable to customize protocol

### ISSUE THREAD

**Issue by enflout** [socketio/socket.io#2070] opened 2015-03-30 18:17 UTC
When I send a packet (event message via emit or just a message via send) I get in Google Chrome Console this kind of packet:

```
42["message",{"conversationId":1,"from":"2015-03-01T00:00:00"}]
```

Is it possible to customize this format? For example, change to

```
{
    "type": 42,
    "event": "message",
    "conversationId": 1,
    "from": "2015-03-01T00:00:00"
}
```

or

```
{
    "type": 42,
    "event": "message",
    "params": {
        "conversationId": 1,
        "from": "2015-03-01T00:00:00"
    }
}
```

or it is not supported and never be supported?

**Comment by nkzawa** [comment] 2015-04-19 08:15
It's not supported and will never be in my opinion. Can I ask why you need this?

**Comment by enflout** [comment] 2015-04-20 09:55
@nkzawa, it's not so easy to describe but I'll try.

1) Strict SocketIO protocol is not convenient for cases when server is SocketIO like and client uses pure vanilla websockets (for example C++ client, all popular C++ SocketIO library supports version 0.9 and neither - 1.0+ - at the moment when I explore these libraries).

Server - SocketIO protocol. Client - pure websockets. If tomorrow protocol will be changed (for example, format of messages will be changed) and all frameworks what I use will develop new versions only for this new protocol, it is unable to me to have all these updates and freeze old version of protocol, backward compatibility will be lost. Is is okay for server, new version of library - new changes in code, it is simple, but is cause changes on the all clients.
So some class overriding standart parsing policy of packets may be very convenient.

2) And the second one, default socket io protocol is not very useful for me. For example I want to pass with each my request some additional data (api version, transaction id) and params of operation:

In the socketIO

["/v1/doIt", "AAAA-BBBB-CCCC-DDDD", params]

or

["doIt", "v1", "AAAA-BBBB-CCCC-DDDD", params]

or

["doIt", {
    "version": "v1",
    "transactionId": "AAAA-BBBB-CCCC-DDDD",
    "params": {}
}]

but the most evident case in my opinion

{
    "command": "doIt",
    "version": "v1",
    "transactionId": "AAAA-BBBB-CCCC",
    "params": {}
}

I can work in socket io and it is great, but sometimes I think that deficiency of flexibility can produce a lot of problems for my project in future.

**Comment by nkzawa** [comment] 2015-04-20 18:40
I think flexible protocol makes the situation worse because clients and server have to know what kind of protocol they use to communicate each others anyway.
Additionally, the problem is not only data format, but socket.io protocol includes how endpoints start handshake, etc.

For the second reason, I think you can just create your own protocol on top of socket.io.

**Comment by darrachequesne** [comment] 2017-01-12 15:48
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).

**Closed by darrachequesne** 2017-01-12 15:48 UTC
Labels: Closed due to inactivity, Feature request
