### ISSUE TITLE
Strange bug when sending an object with an async method call to a room

### ISSUE THREAD

**Issue by brandoncollins7** [socketio/socket.io#3572] opened 2020-04-07 15:09 UTC
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

When including an async method call as a property to the emit object, the send goes to everyone regardless of if they are in the room or not.

### Steps to reproduce (if the current behaviour is a bug)
Not working:

        let pairs = await db('currency_pairs')
        await Promise.all(
            pairs.map(async p => {
                socket.to(`orderbook-${p.id}`).emit('orderbook', {
                    orderbook: await orderbook_service.getOrderbook(p.id),
                    pairId: p.id
                })
            })
        )

Working:

        let pairs = await db('currency_pairs')
        await Promise.all(
            pairs.map(async p => {
                let orderbook = await orderbook_service.getOrderbook(p.id)
                socket.to(`orderbook-${p.id}`).emit('orderbook', {
                    orderbook,
                    pairId: p.id
                })
            })
        )

### Expected behaviour

*What is expected?*

emit should only send to users which have been joined to the room

### Setup
- OS: Windows - Node.js
- browser:
- socket.io version:
2.3.0

**Comment by darrachequesne** [comment] 2021-02-23 12:01
Duplicate of https://github.com/socketio/socket.io/issues/3431

Added in the documentation [here](https://socket.io/docs/v3/rooms/#Usage-with-asynchronous-code), until we fix this behavior in Socket.IO v4.

**Closed by darrachequesne** 2021-02-23 12:01 UTC
