### ISSUE TITLE
When socket.io is under heavy / medium load it is sending a message to the wrong socket

### ISSUE THREAD

**Issue by mesutyigit** [socketio/socket.io#3751] opened 2021-01-11 14:26 UTC
**Describe the bug**
I noticed it while doing the load test. I have a multi-organizational application and I am using socket.io. A user of customer A joins room A, while user B only registers to room B. I prepared a load test scenario with Artillery, with a total of 7000 sockets for 10 minutes. I realized that some of the messages I just left in room A go to B users in an interesting way. There was this problem at socket.io 2.x, I upgraded it to 3.x today and the problem continues.

At first I suspected ID conflict, but
I tried to override the io.engine.generateId and give myself longer UUIDs as a result I saw that the problem was not ID conflict.

**To Reproduce**
If you prepare a load test with artillery and try a medium / heavy scenario, you may generate the error.
Please fill the following code example:

Socket.IO server version: `3.0.5`

Socket.IO client version: `3.0.3`

**Comment by mesutyigit** [comment] 2021-01-11 18:22
Also , this issue related with #2962. It seems that the problem is still not solved.

**Comment by darrachequesne** [comment] 2021-01-11 20:48
Hi! Could you please the code you used for the load test?

**Comment by mesutyigit** [comment] 2021-01-16 21:56
I found out exactly how this bug was triggered.

-  when user of A site login , joining these rooms
   socket.join("A_sites_user")
   socket.join("A_sites_user_SUBJECT_1")

-  when user of B site login , joining these rooms
   socket.join("B_sites_user")
   socket.join("B_sites_user_SUBJECT_1")


artillery load test to -> with only A site user



bug trigger with this code:

` io.to("A_sites_user").to("A_sites_user_SUBJECT_1").emit("foo",{bar:1})` 

 - Interestingly, some of the messages sent in this way go to the B user's socket. Not all but a few!
 
If the 'io.to.to.to.to' method is called consecutively in this way, I think an error has been made while calculating the socket ids in the rooms specified here.

**Comment by llaakso** [comment] 2021-01-18 09:12
socket.join is async and therefore causes such kind of problems. Maybe there is a good reason for such logic, however, I too once spent some time wondering why simple join room + emit won't always work. Decided to ditch rooms and code own logic.

**Comment by darrachequesne** [comment] 2021-01-18 23:11
> socket.join is async

@llaakso I don't think this is true anymore. I think it was needed for the very first versions of the Redis adapter, which made an async operation when joining a room, but that's not the case anymore.

The join method ([here](https://github.com/socketio/socket.io/blob/3.1.0/lib/socket.ts#L252-L259)) might actually return a promise if the underlying adapter itself returns a promise, but this is not the case of the default adapter (https://github.com/socketio/socket.io-adapter/blob/2.1.0/lib/index.ts#L52-L69) nor the Redis adapter (which does not override the addAll method).

Regarding the artillery load test, I'm not able to reproduce with the following test: https://github.com/darrachequesne/artillery-socketio-test/

@mesutyigit could you please check?

**Comment by darrachequesne** [comment] 2021-06-17 13:12
Closed as we were unable to reproduce, please reopen if needed.

**Closed by darrachequesne** 2021-06-17 13:12 UTC
Labels: bug
