### ISSUE TITLE
Limit receive data size on server

### ISSUE THREAD

**Issue by ybelenko** [socketio/socket.io#2326] opened 2015-11-27 22:38 UTC
Hi!
I'm using Socket.io for few month. Now I think that I want to avoid big data transferring between users, because this could be a big Ddos hole inside simplest chat application. I don't allow my users send messages bigger then 1000 chars from the client side anyway.
If I understand correct, "maxBufferSize" option can't solve this problem.

Question is how I can set maximum size for transferred data? This option inside Socket.IO constructor would be very handy when you don't want to send media files.

**Comment by LordMajestros** [comment] 2015-11-27 23:03
This option will need to be passed to the underlying websocket server. Check this pull request for more details https://github.com/websockets/ws/pull/574
I should point out that that pull request does not work for compressed messages sent from the client side, inflating them surpasses the maxPayload value as the maxPayload only applies to each chunk received.
I'll publish my fix for compressed messages to a PR sometime next week. Currently the test for large messages fails with my PR.

**Comment by EmilTholin** [comment] 2015-12-05 01:06
+1 This feels like the last missing piece of this great library.

**Comment by LordMajestros** [comment] 2015-12-31 22:24
Sorry it took longer than I thought to get to this. 
https://github.com/websockets/ws/pull/650
All that's left is to add the maxPayload option to engine.io in a socket.io pr.

**Comment by darrachequesne** [comment] 2017-01-12 15:52
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).

**Closed by darrachequesne** 2017-01-12 15:52 UTC
Labels: Closed due to inactivity

**Comment by samuraitruong** [comment] 2017-02-02 08:58
actually, this is still open, since issue still there, for now client can send huge data to ddos server.

**Comment by edenprojectde** [comment] 2017-04-06 00:32
+1

**Comment by darrachequesne** [comment] 2017-04-06 11:34
Please use the `maxHttpBufferSize` option.

It should work for polling and websocket (since Engine.io 1.6.10, https://github.com/socketio/engine.io/commit/17ec2150c00e3e0e68fa6a490f940c2f4c8f11bc)
