### ISSUE TITLE
Changing query parameter issue

### ISSUE THREAD

**Issue by TheBubbleDuck** [socketio/socket.io#1677] opened 2014-07-10 17:36 UTC
I am hoping I can get some direction on this.

Initializing the io with io(url,opts) works with the query parameter. If that query parameter needs to change you can dot into the sio.io.opts object. However, after it is changed that way, it is not able to be changed again.
##### Iteration 0 - Works On Initialization

<code>
socket = io(options.socket,{query: {_accessToken: 'cow'} });  
</code>
Server's socket.request._query._accessToken returns 'cow'
##### Iteration 1 -Works When changed the first time

<code>
socket.io.opts.query._accessToken = 'moo';
</code>
Server's socket.request._query._accessToken returns 'moo'
##### Iteration 2 -  Doesn't work anymore

<code>
socket.io.opts.query._accessToken = 'twomoos';
</code>
Server's socket.request._query._accessToken returns 'moo''

Although it seems to change on the client side, the server still returns the value of the access token in Iteration 1. 

Doing some digging, I found that the 
<code>
socket.io.engine.transport.ws
</code>
contains the URL for the request, but keeps the _accessToken as the iteration 1 variable. 
<code>
ws://192.168.1.8/socket.io/?_accessToken=moo&transport=websocket&sid=mY9rC4km7ASypgDTAAAI 
</code>
I can't change the variable using javascript because it still stays the same. That also seems rather hacky and I'd like to not do that.

I haven't put in an issue request for anything, so I hope this counts as a legitimate one.

**Comment by peteruithoven** [comment] 2015-02-17 13:58
I've been providing the query string through the url (instead of through a query property of the options object). And I've been experiencing that it doesn't pick up query changes at all. 
Looking through the code it doesn't pass changes properties to a cached manager. (Unless the namespace changed or options like forceNew, or multiplex are used). 
https://github.com/Automattic/socket.io-client/blob/master/lib/index.js#L36

I can confirm this by enabling the debug for engine.io* and socket.io*. I see that eventhough I changed the querry string in the url it opens the old url. (Through the `socket.io-client:manager opening ...` statement)

Also, I don't see a query property used in the code... Are you sure this is supported? 
You are using version 1.x and not 0.9 right? 
Maybe you can also debug this by enabling the debug statements of socket.io and engine.io.

**Comment by peteruithoven** [comment] 2015-02-17 14:11
A bigger issue for me is that I can't work around this with forceNew, without always using it (disabling multiplexing in general). It will pick up query string changes when forceNew is enabled, but when I don't supply this anymore it will fallback to the old & cached manager and it will use the old query string again. 
This is partly caused by the fact that a connection made with forceNew or disabling multiplex are not cached. 

Actually I now see that it should make a new connection when it's the same namespace since a few days, see the commit below. That would solve my issue. Maybe this is not released yet. I'll check.  
https://github.com/Automattic/socket.io-client/commit/7d237cc91fbb34ce484b188cf7d10462c6b34bd9

**Comment by peteruithoven** [comment] 2015-02-17 16:15
The fix that would solve my situation is not released yet.

**Comment by pertinax** [comment] 2015-03-16 11:47
I can't believe that this issue exist and is not implemented just from the begining ..

**Comment by Aliance** [comment] 2015-11-18 13:51
+1

**Comment by abaranovskii** [comment] 2015-11-18 14:40
+1

**Comment by lunow** [comment] 2015-11-21 14:40
+1

**Comment by rek** [comment] 2016-01-20 09:31
+1

**Comment by twong** [comment] 2016-01-20 09:32
+1

**Comment by FredLuart** [comment] 2016-01-21 15:50
+1

**Comment by FredLuart** [comment] 2016-01-25 20:44
On socket.io 1.4.4, even with forceNew parameters, query modification using "socket.io.opts.query" is not considered on reconnection. This is working with version 0.9 using "socket.socket.options.query".

**Comment by Ethefor** [comment] 2016-04-12 08:51
+1

**Comment by FredLuart** [comment] 2016-06-24 07:48
any update on this issue ?

**Comment by AlexDanault** [comment] 2016-08-26 11:57
+1

**Comment by Ryanthegiantlion** [comment] 2016-09-20 06:09
+1

**Comment by juanpujol** [comment] 2016-11-14 18:19
+1

**Comment by codeofsumit** [comment] 2017-11-21 10:43
+1

**Comment by FredLuart** [comment] 2018-03-15 13:45
Any update on this issue ?

**Comment by GStipick** [comment] 2018-10-08 19:14
"socket.io-client": "2.1.1"

Ran into this problem myself today and I think I may have found a solution.
I was able to change the query parameter option by updating the `mysocket.query` object.

The solution as proposed in [the client query object documentation](https://socket.io/docs/client-api/#With-query-option) did not work for me (`mysocket.io.opts.query` did not change the query param for the socket)

```javascript
// On socket creation
const authToken = localStorage.getItem('authToken');
const mysocket = io(`${serverUrl}/${namespaceName}`, {
  transports: ['websocket'],
  query: { authToken },
});

// Somewhere else in my code after I have updated the localStorage
const authToken = localStorage.getItem('authToken');
mysocket.query = { authToken }

// Next time I 're-connected' the socket, the query param was updated correctly and the new authToken was sent
```

The `mysocket` object looks as follows:
```javascript
{
  "io": {},
  "json": {},
  "nsp": "/Test",
  "ids": 0,
  "id": "/Test#randomString",
  "acks": {},
  "receiveBuffer": [],
  "sendBuffer": [],
  "connected": false,
  "disconnected": true,
  "flags": {},
  "query": { "authToken": "Whaterver Your Auth Token Is"}, // <-- I was able to update this directly
  "subs": null,
  "_callbacks": { "$connecting": [null], "$connect": [null], "$action": [null] }
}
```

Hopefully this helps.

**Comment by orhemi** [comment] 2018-12-20 14:56
Yes, but it is updated successfully only once.
When I try to update it again, it does not work.

**Comment by MickL** [comment] 2020-03-24 20:54
This function works for me:

```
updateAccessToken(accessToken: string) {
    this.socket.close();
    this.socket.io.opts.query = { accessToken }
    this.socket.connect();
}
```

I am on socket.io-client `2.3.0`

**Comment by TheKruspe** [comment] 2020-10-06 11:45
Why isn't this fixed after six years? Is there any way to change the query without calling `this.socket.close()`?

**Comment by MickL** [comment] 2020-10-06 11:49
> Why isn't this fixed after six years? 🤔 

Why dont you fix this? 🤔 This is an open source project...

**Comment by darrachequesne** [comment] 2020-10-06 13:04
The problem is that the `query` parameter is used both by the Manager (and the underlying Engine.IO client) and the Socket.

The solution by @GStipick will only work for a Socket in a non-default namespace:

```js
const socket = io('/admin', {
  query: { abc: 'def' },
});

socket.on('reconnect_attempt', () => {
  socket.query = {
    token: 'ghi'
  }
});
```

For the default namespace, you must update the `query` option of the Manager (which will be included in the query params of the HTTP requests):

```js
const socket = io({
  query: { abc: 'def' },
});

socket.on('reconnect_attempt', () => {
  socket.io.opts.query = {
    token: 'ghi'
  }
});
```

This change will only be used upon reconnection to the namespace (hence the `reconnect_attempt` event).

This inconsistency will be fixed in Socket.IO v3, please see my proposition here: https://github.com/socketio/socket.io/issues/3250#issuecomment-704245631

**Comment by darrachequesne** [comment] 2021-02-17 08:56
For future readers: this was fixed in Socket.IO v3

Documentation:
- https://socket.io/docs/v3/migrating-from-2-x-to-3-0/#Add-a-clear-distinction-between-the-Manager-query-option-and-the-Socket-query-option
- https://socket.io/docs/v3/client-initialization/#query

**Closed by darrachequesne** 2021-02-17 08:56 UTC
Labels: Socket.IO v3

**Comment by FerusAndBeyond** [comment] 2021-05-01 22:47
I'm getting something similar in 4.0.1

**Comment by bij7n** [comment] 2022-01-24 13:18
close the socket before change query 
in this order
```
socket.disconnect()
socket.close()
socket.io.opts.query={key:valye}
socket.connect()
```
test in version 4

**Comment by darrachequesne** [comment] 2022-01-25 00:15
@bij7n a minor nitpick, in your example above, the `close()` is not needed, as it is an alias for `disconnect()`:

```js
socket.disconnect()
socket.io.opts.query={key:valye}
socket.connect()
```

Reference: https://socket.io/docs/v4/client-api/#socketclose

Thanks for the code example :+1:

**Comment by ChrisIT9** [comment] 2022-04-12 20:57
This is still not fixed. This fucking sucks
