### ISSUE TITLE
no way to shutdown a server cleanly

### ISSUE THREAD

**Issue by msmouse** [socketio/socket.io#1602] opened 2014-06-07 21:48 UTC
Hi, I'm seeking for a way to shutdown a server. The current behavior is, when I call close() on engine, clients disconnect, but connect again immediately. Even if I call socket.io.close() on disconnect, the server is still listening.

And, can I suppose if socket.io.close() is called,(and references from my program is all deleted), the socket will be subject to garbage collection?

"use strict"

var svr = require('socket.io')(12332);
var clt1 = require('socket.io-client')('ws://127.0.0.1:12332');
var clt2 = require('socket.io-client')('ws://127.0.0.1:12332');
svr.on('connection', function(socket) {
    console.log("svr connected");
    svr.engine.close();
});

clt1.on('connect', function() {
    console.log('clt connected');
});
clt1.on('disconnect', function() {
    console.log('clt disconnected');
    // clt1.io.close();
});
clt1.on('error', function() {
    console.log('clt error');
});

**Comment by ChiperSoft** [comment] 2015-03-29 19:54
I'm experiencing this problem as well.  Calling close on the http server does make it stop accepting new connections, but the http server never fires its close event, so the close callback never gets evoked.  If I shutdown without anyone connecting, then the server closes fine, but once a single person has connected the server refuses to shutdown cleanly.

I've tried `io.close()`, `io.engine.close()`. I'm sending a shutdown command to all clients, which causes the frontend to close on its end, and then I see the socket disconnecting, so I know the sockets are all closed.

For whatever reason, the http server never realizes that all connections are complete.  This is a pretty big issue for me, since I can't safely close my database links until I know all requests have finished and http is clear.

**Comment by amitport** [comment] 2015-05-23 15:04
:+1:

**Comment by paulpflug** [comment] 2015-05-30 12:54
+1

I think a problem is, that the `httpServer.close()` is async [here](https://github.com/Automattic/socket.io/blob/master/lib/index.js#L356).
So the `server` should bind to the `httpServer` close event.

Workaround:
```coffee
ioClosed = new Promise (resolve) ->
  if io.httpServer
    io.httpServer.on "close", resolve
  else
    resolve()
```

**Comment by PritamUpadhyay** [comment] 2015-05-30 12:59
+1

**Comment by llaakso** [comment] 2015-05-30 14:33
+1

**Comment by ilkkao** [comment] 2015-07-08 13:25
Busy server has always active websocket connections, there must be a way to shutdown the server cleanly without expecting any co-operation from the clients? I mean assuming I have:

```
let io = socketIo(server);

io.on('connection', function(socket) {
  [add socket to active sockets list] 
  
  [all other logic]

  socket.on('disconnect', function() {
    [remove socket from active sockets list]
  });
}
```

Then in shutdown this should work?

```
// 1.
io.close() // Stop accepting new connections

// 2.
for [all items in active sockets list] {
    socket.disconnect() // <- This doesn't close the underlying TCP socket.
}
```

But it doesn't.

**Comment by ilkovich** [comment] 2015-07-11 01:42
Just spent way too much time struggling with this, but I had success with the following: 

```javascript
function wireUpServer(/*httpServer*/ server) {
    var connections = {};
    server.on('connection', function(conn) {
        var key = conn.remoteAddress + ':' + conn.remotePort;
        connections[key] = conn;
        conn.on('close', function() {
            delete connections[key];
        });
    });

    server.destroy = function(cb) {
        server.close(cb);
        for (var key in connections)
            connections[key].destroy();
    };
}
```

Then during your init process you can call: 

```javascript
wireUpServer(server)
```

and when you're ready to destroy

```javascript
io.close();
server.destroy();
```

**Comment by timdp** [comment] 2015-09-19 11:35
Similar logic [here](http://stackoverflow.com/q/14626636) for a plain old `net.Server`.

Given that socket.io tries to abstract away a lot of the underlying network tomfoolery, it'd be great if it came with this feature baked in.

**Comment by jamesshore** [comment] 2016-02-14 20:29
I'm also experiencing this issue. socket.io v1.4.5. Here's code to reproduce it:

`server-hang.js`:

```javascript
// Copyright (c) 2016 Titanium I.T. LLC. All rights reserved. For license, see "README" or "LICENSE" file.
(function() {
  "use strict";

  var PORT = 5020;
  var TIMEOUT = 10000;

  var io = require('socket.io')(PORT);

  console.log("Waiting " + (TIMEOUT / 1000) + " seconds...");
  setTimeout(function() {
    io.close();
    console.log("PROCESS SHOULD NOW EXIT");
  }, TIMEOUT);

}());
```

`server-hang.html`:

```html
<!DOCTYPE html>
<html lang="en">

<head>
  <title>Server won't exit</title>
  <meta charset="utf-8">

  <script src="https://cdn.socket.io/socket.io-1.4.5.js"></script>
</head>

<body>

<p>Look at the console!</p>

<script>
  console.log("Client started");

  console.log("Connecting...");
  var origin = "http://localhost:5020";
  var socket = io(origin);

  socket.on("connect", function() {
    console.log("Server connected");
    socket.destroy();
    console.log("disconnect() called");
  });
</script>

</body>
</html>
```

To reproduce:

1. Run `node server-hang.js`
2. Within 10 seconds, drag `server-hang.html` into a browser window. It will load as a file resource and trigger the bug.
3. Observe that the server doesn't exit after printing "PROCESS SHOULD NOW EXIT."

Expected behavior: The server should exit after 10 seconds.

**Comment by littleguga** [comment] 2016-05-06 02:37
Also have this bug.

My code is similar to @jamesshore

**Comment by shakyShane** [comment] 2016-06-07 12:49
I have tracked down the cause of this, it is indeed a bug.

The `ws` package that engine.io uses has the following block inside of a `close` method

<img width="870" alt="screen shot 2016-06-07 at 13 19 16" src="https://cloud.githubusercontent.com/assets/1643522/15857468/87c81a8c-2cb3-11e6-9de7-094ed258f5ec.png">

src: https://github.com/websockets/ws/blob/master/lib/WebSocket.js#L125-L131

As you can see from the overlay,  the `_closeReceived` property never gets set to `true` at any point by socket.io or engine.io, this means the `terminate()` method is never called and instead we enter into a 30 second wait

```js
// socket.io/engine.io never sets `self._closeReceived` to true, so we can never get into this block
// to call the terminate method
if (self._closeReceived && self._isServer) {
    self.terminate();
} else {

    // WE ALWAYS REACH HERE
    // and closeTimeout = 30 seconds
    clearTimeout(self._closeTimer);
    self._closeTimer = setTimeout(cleanupWebsocketResources.bind(self, true), closeTimeout);
}
```

The chain of events that lead to this bug begin here https://github.com/socketio/engine.io/blob/master/lib/server.js#L180-L188

Here's a screencast showing the stack https://www.youtube.com/watch?v=H0ngC6TDePE&feature=youtu.be

@rauchg @3rd-Eden @einaros is there any extra information you would need? 

This is a big problem for tools such as [Browsersync](https://github.com/BrowserSync/browser-sync) as we want to allow users to gracefully boot up/shut down servers at will, and currently if any socket is connected, they will be doomes to the `30000` wait timeout as shown above.

Many thanks for your hard on this lib, please inform me if you need any further information.

**Comment by enrichz** [comment] 2017-04-11 09:31
Any update on this issue?

**Comment by paulpflug** [comment] 2017-04-17 12:55
A part of the problem is, that a `httpserver` will not close as long as there are connections alive:
https://nodejs.org/api/http.html#http_server_close_callback

A proper closing mechanism would need to keep track of all connections - which is probably out of scope of socketio.

```js
// will close the underlying httpserver - that means it wont accept new connections
// but as long as there are open connections, it won't actually close
io.httpServer.close() 

// will close all active websocket sessions - but not the connections
io.close()
```

Just use the solution presented above..

**Comment by nguiard** [comment] 2017-11-07 16:17
Any news on this issue?

**Comment by nguiard** [comment] 2017-11-08 20:22
Nevermind, sorry for the above question, I realise the solution presented above actually works. I was just having issues with closing socket.io server when clients are still connected and thought the problem was still here in engine.io.

**Comment by chenxiaochun** [comment] 2017-11-14 08:06
@nguiard ,i aslo found the issue is still existed.

**Comment by s-a** [comment] 2017-12-22 11:08
Is this module still maintained? We facing the same error. None of the suggested codes work around the problem. In fact in my case there is no client connected. 😿

**Comment by mandaputtra** [comment] 2019-07-18 14:52
Hi quick question here @s-a do you experienced EARDDRESINUSE? or the port is still in use ? When use nodemon or others?

**Comment by allenchuang** [comment] 2019-09-09 22:46
This issue still exists.... Ctrl-C killing the server would still persist the socket connections, and upon refresh of client, it will ask for another new socket + reconnecting the old socket... the server is not disconnected from the first connection, another refresh will trigger an extra socket...

**Comment by linuscarlstrom** [comment] 2019-10-14 08:32
Is there any updates on this issue?

**Comment by n1ru4l** [comment] 2020-05-01 20:13
https://github.com/socketio/socket.io/issues/1602#issuecomment-120561951

I am using the following with `Set` instead of an object (and `delete`):

```js
const connections = new Set();

server.on("connection", connection => {
  connections.add(connection);
  connection.once("close", () => {
    connections.delete(connection);
  });
});

const shutdownHandler = once(() => {
  console.log("Shutting down");
  httpServer.close(err => {
    if (err) {
      console.error(err);
      process.exitCode = 1;
    }
  });

  for (const connection of connections) {
    connection.destroy();
  }
});

process.on("SIGINT", shutdownHandler);
```

**Comment by n1ru4l** [comment] 2020-05-26 15:18
@TheLudd https://github.com/dungeon-revealer/dungeon-revealer/blob/f5dcce720cee0e0d41e012cfb5c5bd5af3e77687/server/index.js#L50-L72

**Closed** 2020-07-22 15:43 UTC

**Comment by mfahadshah** [comment] 2023-01-13 19:23
This might help.. added in socket v4
// make all Socket instances disconnect
io.disconnectSockets();

https://socket.io/docs/v4/server-api/#server

**Comment by jokester** [comment] 2024-02-02 14:44
I still experience server hang-when-close with socket.io v4.7.4 . Cutting underlying TCP connection still work, calling `server.disconnectSockets(true)` did not.

This is a renewed snippet of the TCP connection trick, thanks for information in this thread.

```ts
import type net from 'node:net';
import type http from 'node:http';

/**
 * record alive TCP connections, to force disconnect them during shutdown
 * (socket.io may have problem close all connections.)
 * @return a function to close all TCP sockets
 */
export function prepareTcpConnect(server: http.Server): () => void {
  const sockets = new Set<net.Socket>();
  server.on('connection', conn => {
    sockets.add(conn);
    conn.on('close', () => {
      sockets.delete(conn);
    });
  });

  return () => sockets.forEach(s => s.destroy());
}
```

**Comment by darrachequesne** [comment] 2024-02-05 08:24
@jokester I don't think this should be needed. Isn't `io.close()` sufficient?

https://github.com/socketio/socket.io/blob/e36062ca2df0b1a4adcf986bafc3fd92675d3896/lib/index.ts#L745-L760

It should close both:

- the Engine.IO server (`io.engine.close()`): https://github.com/socketio/engine.io/blob/ff0fbfb61f2509ef302870cfd993344c1d035e7d/lib/server.ts#L389-L398
- and the HTTP server: https://nodejs.org/api/http.html#serverclosecallback

Also, I was not able to reproduce the issue:

```js
// server.js
import { createServer } from "node:http";
import { Server } from "socket.io";

const httpServer = createServer();
const io = new Server(httpServer, {});

const port = process.env.PORT || 3000;

io.on("connection", (socket) => {
  console.log(`connect ${socket.id}`);

  socket.on("disconnect", (reason) => {
    console.log(`disconnect ${socket.id} due to ${reason}`);
  });
});

io.of("/chat").on("connection", (socket) => {
  console.log(`[chat] connect ${socket.id}`);

  socket.on("disconnect", (reason) => {
    console.log(`[chat] disconnect ${socket.id} due to ${reason}`);
  });
});

httpServer.listen(port, () => {
  console.log(`server listening at http://localhost:${port}`);
});

setTimeout(() => {
  io.close();
  console.log("PROCESS SHOULD NOW EXIT");
}, 10_000);
```

```js
// client.js
import { io } from "socket.io-client";

const port = process.env.PORT || 3000;

const socket = io(`http://localhost:${port}`);

socket.on("connect", () => {
  console.log(`connect ${socket.id}`);
});

socket.on("connect_error", (err) => {
  console.log(`connect_error due to ${err.message}`);
});

socket.on("disconnect", (reason) => {
  console.log(`disconnect due to ${reason}`);
});

const socket2 = io(`http://localhost:${port}`, {
  forceNew: true
});

const socket3 = io(`http://localhost:${port}/chat`, {
  forceNew: true
});

const socket4 = io(`http://localhost:${port}`, {
  forceNew: true,
  transports: ["polling"]
});

const socket5 = io(`http://localhost:${port}`, {
  forceNew: true,
  transports: ["websocket"]
});
```

That being said, I only found [one change](https://github.com/socketio/socket.io/commit/e14a10b7cece99199e0c5609dcbc1560c244ccfe) impacting the `close()` method since the opening of the issue, so it might not be completely fixed...

**Comment by jokester** [comment] 2024-02-19 09:12
@darrachequesne sorry I don't have a good reproduction or insight in code.

When developing [my app using socket.io](https://github.com/jokester/limb) I think my server stuck at 5% or 10% of all runs, until I cut the TCP sockets. 

I'm currently reading socket.io code to write an experimental adapter, maybe I can be lucky enough to find a hint 🤔
