### ISSUE TITLE
io.connect('/') does not obey the port number

### ISSUE THREAD

**Issue by ali-bugdayci** [socketio/socket.io#2025] opened 2015-02-27 12:12 UTC
Previously in the 1.1.0 version the following code would connect while testing at "localhost:3000"
```
io.connect('/admin')
```

Now it does not use the port number and tries to connect "localhost", hence I have to enter:
```
 io.connect(window.location.origin + '/admin')
```

**Comment by ahmetemir** [comment] 2015-02-27 12:21
You should specify your port in options like {port:3000} otherwise socket.io tries to get from your url.

**Comment by ali-bugdayci** [comment] 2015-02-27 13:21
Well in 1.1 version I did not have to. 

Normally, in html terms, '/path' would lead to the current "origin/path" including port and http/s on origin

**Comment by ahmetemir** [comment] 2015-02-27 14:04
Actually all I can say is socket.io ignores port in url and got port number from either options or  protocol (http/s).

**Comment by nkzawa** [comment] 2015-03-02 17:03
Duplicate of #2021, https://github.com/Automattic/socket.io-client/issues/812

**Comment by MrOrz** [comment] 2015-04-14 01:31
Hello,

It has been 1.5 months since the last version bumping. Although [the fix](https://github.com/Automattic/socket.io-client/commit/5abd97b2313aa3e9c9b2e1035dd4c24379fd77e8) is already merged in January, but somehow it did not appear in the released versions. People bumping into this issue is still increasing, making the thread https://github.com/Automattic/socket.io-client/issues/812 longer and longer.

Is there a roadmap on the next release?

**Comment by peteruithoven** [comment] 2015-04-14 09:49
I think the [1.4.0 milestone](https://github.com/Automattic/socket.io/milestones/1.4.0) is the roadmap? And I'm sure people are working on it. But I'm also curious about a release estimation. I understand this is difficult, because most if not all are doing this in their spare time.

**Closed** 2016-01-17 13:22 UTC
Labels: Socket.IO client
