### ISSUE TITLE
CORS Errors after updating to 2.2.0

### ISSUE THREAD

**Issue by sjones6** [socketio/socket.io#3381] opened 2018-11-29 18:16 UTC
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

Getting lots of CORS errors after the latest update.
![screen shot 2018-11-29 at 1 13 25 pm](https://user-images.githubusercontent.com/12819256/49242465-d6618180-f3d8-11e8-8a7b-b41fd1da3c23.png)

### Steps to reproduce (if the current behaviour is a bug)

[Repo](https://github.com/WireWheel/socketio-2.2.0-cors-error). See README for instructions.

### Expected behaviour

No CORS errors.

### Setup
- OS: Mac
- browser: Chrome 70
- socket.io version: 2.2.0

### Other information (e.g. stacktraces, related issues, suggestions how to fix)

@davericher made a comment [here](https://github.com/socketio/socket.io/commit/df05b73bb93d7c34c758504001f869cb156703d5#commitcomment-31497120) indicating this. Perhaps he has more details.

**Comment by Bramzor** [comment] 2018-11-29 18:29
+1 Started to fail since I downloaded the packages again.

**Comment by Bramzor** [comment] 2018-11-29 18:38
Workaround: npm install socket.io@2.1.1

**Comment by darrachequesne** [comment] 2018-11-29 20:48
Hmm.. I don't see anything related in the [changelog](https://github.com/socketio/socket.io/releases/tag/2.2.0)... It may be the update of the `ws` package.

Is anyone able to reproduce the issue?

**Comment by neemah** [comment] 2018-11-29 20:56
Yes.

**Comment by sjones6** [comment] 2018-11-29 21:06
@darrachequesne : I updated my description with a link to repo where you can reproduce the issue. Instructions are in the README at the repo.

**Comment by sjones6** [comment] 2018-11-29 21:12
Another way to solve: fill in the `origin` property in your socketio server config:
```javascript
const Server = require('socket.io');
const io = new Server({
  origins: 'http://your-cors-url' // i believe can also be an array of urls, defaults to '*'
});
```
You should see this show up in the response headers for the handshake request in your network tab:
![screen shot 2018-11-29 at 4 10 28 pm](https://user-images.githubusercontent.com/12819256/49252205-601d4900-f3f1-11e8-96da-d51547c61276.png)

The browser should stop complaining about the CORS violation then.

**Comment by sjones6** [comment] 2018-11-29 21:15
@darrachequesne It seems like if you comment out [these lines](https://github.com/socketio/engine.io-client/blob/master/lib/transports/polling-xhr.js#L226) in `engine.io-client`:
```javascript
if ('withCredentials' in xhr) {
  xhr.withCredentials = true;
}
```
then the requests succeed.

So maybe, in v <2.2.0, somehow `'withCredentials' in xhr === false`?

**Comment by xaviergonz** [comment] 2018-11-29 21:36
I think with credentials was always set to true. 

The problem is that allow origins * is not allowed when with credentials is set to true. Previous versions would use the client origin header when an origin was valid, but the new version just uses "*", and therefore the browser complains.

**Comment by darrachequesne** [comment] 2018-11-29 21:44
@flenter could it be related to https://github.com/socketio/engine.io/pull/511?

**Comment by xaviergonz** [comment] 2018-11-29 21:46
Another option is of course to set with credentials to false, but that'd mean that the socket io server does not care about getting / setting any cookies. Not sure if that's the case with socket io

**Comment by neemah** [comment] 2018-11-29 21:50
https://github.com/socketio/engine.io/pull/511/files#diff-c945a46d13b34fcaff544d966cffcabaL259

**Comment by xaviergonz** [comment] 2018-11-29 21:52
That pr could have added a way to set the header to the client request origin header. Maybe a good place to do this is that when using origins with a callback and the callback is called with success true the Allow-origins would be set to the origin that was passed to the callback.

Either way, after that PR this is a breaking change though I guess? 

As it is right now I see no way to support all origins when with credentials is set to true

**Comment by darrachequesne** [comment] 2018-11-29 21:55
I reverted the PR and published a new version of `engine.io`. Could you please check that it fixes the issue? https://github.com/socketio/engine.io/commits/master

**Comment by xaviergonz** [comment] 2018-11-29 21:56
Or to avoid a breaking change then when origins is not explicitly set in the options / set to undefined (default) or origins function is called with undefined then it will use the client origin header (the old default behavior)

**Comment by Bramzor** [comment] 2018-11-30 00:01
Wouldnt it make sense to have credentials off by default? For most cases it shouldnt be on anyway right?

**Comment by sjones6** [comment] 2018-11-30 01:56
@darrachequesne : Thanks; we've pulled down 3.2.2 of `engine.io` and things are back in our environments.

Based on this comment [this comment](https://github.com/socketio/socket.io/issues/3381#issuecomment-443001962) from @xaviergonz , I think I have a clearer picture: 

In `socket.io <2.2`, CORS was enforced _only if_ you supplied `origins`; if not, all origins were allowed. In 2.2.0 (really new dep on `engine.io@3.2.1` via [this commit](https://github.com/socketio/socket.io/commit/df05b73bb93d7c34c758504001f869cb156703d5#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L31) I think), CORS is enforced whether or not you supply an `origins` options. 

I'm all for enforcing CORS as default behavior ... but seems like that's probably a breaking for new major version.

**Comment by neemah** [comment] 2018-11-30 09:50
Is there any ETA on bug fix release? 2.2.0 uses engine 3.2.1, not 3.2.2

**Comment by ravid87** [comment] 2018-11-30 09:59
@neemah i had to remove and add socket.io to have the updated version : 
yarn remove socket.io && yarn add socket.io

here my yarn list now : 
├─ socket.io@2.2.0
│  ├─ debug@~4.1.0
│  ├─ debug@4.1.0
│  │  └─ ms@^2.1.1
│  ├─ engine.io@~3.3.1
│  ├─ has-binary2@~1.0.2
│  ├─ ms@2.1.1
│  ├─ socket.io-adapter@~1.1.0
│  ├─ socket.io-client@2.2.0
│  └─ socket.io-parser@~3.3.0

**Comment by neemah** [comment] 2018-11-30 10:13
Well @ravid87,3.3.1 engine.io is "broken", while 3.3.2 is fixed :)

**Comment by ravid87** [comment] 2018-11-30 10:53
@neemah the broken one was 3.2.2

> @darrachequesne : Thanks; **we've pulled down 3.2.2** of `engine.io` and things are back in our environments.
> 
> Based on this comment [this comment](https://github.com/socketio/socket.io/issues/3381#issuecomment-443001962) from @xaviergonz , I think I have a clearer picture:
> 
> In `socket.io <2.2`, CORS was enforced _only if_ you supplied `origins`; if not, all origins were allowed. In 2.2.0 (really new dep on `engine.io@3.2.1` via [this commit](https://github.com/socketio/socket.io/commit/df05b73bb93d7c34c758504001f869cb156703d5#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L31) I think), CORS is enforced whether or not you supply an `origins` options.
> 
> I'm all for enforcing CORS as default behavior ... but seems like that's probably a breaking change that should be added in new major version.

**Comment by neemah** [comment] 2018-11-30 10:56
@ravid87 3.2.2 doesn't exist https://github.com/socketio/engine.io/tree/3.2.2, so i assume author of message meant 3.3.2, which is latest release, if you check commits / tags.

So still waiting for fix :)

**Comment by sjones6** [comment] 2018-11-30 11:41
@neemah @ravid87 : sorry for confusion; correcting my typo by editing comment ...

**Comment by sjones6** [comment] 2018-11-30 11:47
@neemah : `npm` should resolve correctly to `engine.io@3.3.2` based on the deps in `socket.io`:
```
"engine.io": "~3.3.1"
```
You need to delete your package-lock.json (or yarn.lock) first though before installing of you'll get `3.3.1` again..

**Comment by ravid87** [comment] 2018-11-30 12:18
@sjones6 ok thx for the version correction. But i'm still confused because, 
1) even if i delete yarn.lock, i have this in my yarn.lock : 

`
socket.io@^2.2.0:
  version "2.2.0"
  resolved "https://registry.yarnpkg.com/socket.io/-/socket.io-2.2.0.tgz#f0f633161ef6712c972b307598ecd08c9b1b4d5b"
  integrity sha512-wxXrIuZ8AILcn+f1B4ez4hJTPG24iNgxBBDaJfT6MsyOhVYiTXWexGoPkd87ktJG8kQEcL/NBvRi64+9k4Kc0w==
  dependencies:
    debug "~4.1.0"
    **engine.io "~3.3.1"**
    has-binary2 "~1.0.2"
    socket.io-adapter "~1.1.0"
    socket.io-client "2.2.0"
    socket.io-parser "~3.3.0"
`

2) i don't understand why everything works with 3.3.1...

**Comment by neemah** [comment] 2018-11-30 12:19
2 - probably because you are checking it on same domain, where this problem does not appear

**Comment by ravid87** [comment] 2018-11-30 12:23
@neemah here my setup : 
-> the app is on **foobar.com**
-> the socket is on **socket.foobar.net**

so its not on same domain :/

**Comment by neemah** [comment] 2018-11-30 12:29
then probably you configurated origin with value `http[s]://foobar.com` where you run ` socket.foobar.net`

**Comment by ravid87** [comment] 2018-11-30 12:56
@neemah no origins configured on socket.io or express.js.

i had CORS problem yesterday and today after a clean install of socket.io everything worked again...

**Comment by sjones6** [comment] 2018-11-30 16:29
@ravid87 : Can you confirm today you have `engine.io@3.3.2` on your file system today? Based on [your comment](https://github.com/socketio/socket.io/issues/3381#issuecomment-443187287), the dependency on `engine.io "~3.3.1"` is correct but the downloaded version should be resolved to `3.3.2` not `3.3.1`. Yesterday, it would have been `3.3.1` until the update was published.

`yarn list --pattern engine.io --depth=5` should tell you.

**Comment by ravid87** [comment] 2018-12-02 12:43
> @ravid87 : Can you confirm today you have `engine.io@3.3.2` on your file system today? Based on [your comment](https://github.com/socketio/socket.io/issues/3381#issuecomment-443187287), the dependency on `engine.io "~3.3.1"` is correct but the downloaded version should be resolved to `3.3.2` not `3.3.1`. Yesterday, it would have been `3.3.1` until the update was published.
> 
> `yarn list --pattern engine.io --depth=5` should tell you.

yes ! i have the 3.3.2 :+1:

**Comment by AhCamargo** [comment] 2019-12-10 18:38
I Have same problem with CORS:

`-- socket.io@2.3.0
  `-- engine.io@3.4.0

**Comment by cmmash** [comment] 2020-02-06 16:01
Having the same problem as @AhCamargo responded, with the same versions of socket.io and engine.io, but mine is that I'm trying to open a socket.io connection with auth from a different domain (client side) than the server side

Full error context:

1. Client at: `http://localhost:5530/`
Client code:
```

      // ... get sessionToken, initialize stuff.

      var socket = io.connect('http://localhost:8011', {
        query: query,
        transportOptions: {
          polling: {
            extraHeaders: {
              'x-user-token': sessionToken
            }
          }
        }
      });

      socket.on('connect', () => {
        console.log("===> rootNspDemo connection established!!!!!, socket: ", socket.id);
      })
      socket.on('disconnect', (reason) => {
        console.log('rootNspDemo connection disconnected: ' + reason);
        socket.close(); // stop reconnecting
      })
      socket.on(topic, function(data) {
          console.log("###> root namespace progress data: ", data);
          document.getElementById("taskStatus").innerHTML = data.taskStatus;
      });
    }
```

The server side:

```
// ... imports


// Initialize express
const app = express();

// TRIED ALL THESE, BUT NONE WORK
// const cors = require('cors');
// app.use(cors({credentials: true, methods: ['GET', 'PUT', 'POST', 'PATCH', 'DELETE', 'OPTIONS']}));
// app.options('*', cors({credentials: true, methods: ['GET', 'PUT', 'POST', 'PATCH', 'DELETE', 'OPTIONS']}));
// app.use(cors());
// app.options('*', cors({methods: ['GET', 'PUT', 'POST', 'PATCH', 'DELETE', 'OPTIONS']}));

const server = app.listen(SERVER_PORT, () => {
    logInfo(
      `%s v%s listening on port %s in %s mode`,
      PKG.name,
      PKG.version,
      SERVER_PORT,
      ENV
    );
  });


// var socketIOAllowedOrigins = "http://localhost:* http://127.0.0.1:*";
var socketIOAllowedOrigins = "http://localhost:5530";

// TRIED THIS ALSO, DIDN'T WORK
// const io = require('socket.io').listen(server, {origins: socketIOAllowedOrigins});

const socketIOAuth = async function(socket, next) {
  const sessionToken = socket.handshake.headers['x-user-token'];
  const user = await getUser(sessionToken);
  if (!user) {
  // eslint-disable-next-line no-console
    console.log('---> socket ' + socket.id + ' of nsp: ' + socket.nsp.name + ' FAILED authentication !!');
    socket.disconnect('unauthorized');
    next(new Error('invalid sessionToken'));
  } else {
  // eslint-disable-next-line no-console
    console.log('---> socket ' + socket.id + ' of nsp: ' + socket.nsp.name + ' is authenticated!!');
  }

  return next();
};

const io = require('socket.io').listen(server);
io.use(socketIOAuth); // REMOVING THIS, and NOT SENDING AUTH TOKEN FROM CLIENT, THEN IT WORKS
// io.origins('*');

io.origins(['localhost:8011', 'localhost:5530',
  'http://localhost:8011', 'http://localhost:5530']);

const runDemo = (socket) => {
    // Demo test of progress bar
    // eslint-disable-next-line no-console
    console.log('Running socket.io demo for topic: ', socket.handshake.query.topic);
    let i = 0;
    const interval = setInterval(function() {
      if (i < 100) {
        socket.emit(socket.handshake.query.topic, { rootDummy: true, progress: i, taskStatus: 'RUNNING' });
        i++;
      } else {
        socket.emit(socket.handshake.query.topic, { rootDummy: true, progress: i, taskStatus: 'SUCCESS' });
        clearInterval(interval);
      }
    }, 1000);
  }

io.on('connection', runDemo);
```

Here's the interesting bits I debugged:

Removing auth middleware from socketio in server side - `io.use(socketIOAuth); ` and also removing the passing of sessionToken from client side :
```
        transportOptions: {
          withCredentials: true,
          polling: {
            extraHeaders: {
              // 'x-user-token': sessionToken
            }
          }
        }
```

Makes the connection work fine.

**Comment by vicky-gonsalves** [comment] 2020-03-12 15:32
I have same issue..

**Comment by brunobrante** [comment] 2020-05-29 19:42
I have same issue..

**Comment by darrachequesne** [comment] 2021-03-04 06:15
For future readers: this was fixed in [`engine.io@3.3.2`](https://github.com/socketio/engine.io/releases/tag/3.3.2) (the change was reverted)

Please see the documentation here: https://socket.io/docs/v3/handling-cors/

**Closed by darrachequesne** 2021-03-04 06:15 UTC
