### ISSUE TITLE
Half close on error

### ISSUE THREAD

**Issue by nuclearace** [socketio/socket.io#2031] opened 2015-03-03 19:24 UTC
![](https://i.imgur.com/S7O8aQK.png)

The underlying transport does not close, yet a disconnect event is emitted. Client still thinks it is connected.

**Comment by Mewte** [comment] 2015-03-06 06:04
I'm noticing similar behavior, I'm using a node.js server with socket.io-client, when the socket encounters an error, the master server shows the error in the console and triggers disconnect, but the client remains connected. However, the server no longer responds to the client. I also can't seem to find a way to capture the error that occurs. It just shows it in the console which isn't very helpful for logging.

**Comment by Mewte** [comment] 2015-03-06 06:58
I found out that if I do: 
`````javascript
	client.on("error", function(){
		client.disconnect();
	});
`````
I can force the client to disconnect, though it won't invoke the clients auto reconnect. I could possibly emit an "error" event to the client and let the client decide how it should be handled (and possibly invoke the reconnection manually) Perhaps this is intended as it does give you more control over how errors are handled.

**Comment by nkzawa** [comment] 2015-03-09 16:35
looks related: https://github.com/Automattic/engine.io/issues/310

**Comment by darrachequesne** [comment] 2017-01-12 15:46
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).

**Closed by darrachequesne** 2017-01-12 15:46 UTC
Labels: Closed due to inactivity
