### ISSUE TITLE
Yarn cannot install socket.io but npm succeeds

### ISSUE THREAD

**Issue by SrihariThalla** [socketio/socket.io#3003] opened 2017-07-10 11:26 UTC
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour
Yarn get stuck while installing socket.io. But it succeeds with npm!

It downloads `node-sass` and then is stuck with indefinite lines with "waiting..." which stays on the screen.

```
[1/4] ⠂ node-sass: Downloading binary from https://github.com/sass/node-sass/releases/download/v4.5.3/darwin-x64-48_binding.node
```

### Steps to reproduce (if the current behaviour is a bug)
`yarn add socket.io` is just the command.

### Setup
- OS: macOS 10.12.5 (16F73), Kernel: Darwin 16.6.0
- NodeJS: v6.11.0
- npm: 5.0.6
- Yarn: v0.27.5
- socket.io version: 2.0.3

#### Related
https://github.com/yarnpkg/yarn/issues/3867

Thanks for your help!

**Comment by SrihariThalla** [comment] 2017-07-10 11:27
BTW, if it helps, `socket.io-client` has no issues and installation succeeds with Yarn!

**Comment by ianstormtaylor** [comment] 2017-10-06 21:56
Seeing this same problem, can't use `socket.io` with yarn at all for some reason, even on the latest version of each. I originally opened this: https://github.com/yarnpkg/yarn/issues/4653

**Comment by darrachequesne** [comment] 2021-02-19 14:28
Closed as I was not able to reproduce, please reopen if needed.

**Closed by darrachequesne** 2021-02-19 14:28 UTC
