### ISSUE TITLE
Maximum concurrent connection?

### ISSUE THREAD

**Issue by vinhjs** [socketio/socket.io#2048] opened 2015-03-11 10:31 UTC
I am trying to run a code on Client but it stopped when var "count" increase about 1000.
I tried many times but still keep this result. Please help to explain the reason and help to give the solution to adjust this.
Many thanks.

Server:

```
var app = require('express')();
var http = require('http').Server(app);
var io = require('socket.io')(http);

io.on('connection', function(socket){
  socket.on('chat message', function(msg){
    io.emit('chat message', msg);
  });
});

http.listen(3000, function(){
  console.log('listening on *:3000');
});
```

Client:

```
var async = require('async');

var count = 0;

async.whilst(
    function () { return count < 2000; },
    function (callback) {
        var socket = require('socket.io-client')('http://locahost:3000', {'force new connection': true});

        socket.on('connect', function(){
            count++;
            console.log('connections: ' + count);
            callback();
        })

    },
    function (err) {
        console.log('DONE');
    }
);
```

**Comment by 3rd-Eden** [comment] 2015-03-11 10:33
Opening the same question in multiple projects isn't really helpful. Answered in primus/primus#355 (file descriptor limit)

**Comment by piotrchludzinski** [comment] 2015-11-02 14:32
I have a big problem with socket.io connection limit. If the number of connections is more than 400-450 connected clients (by browsers) users are getting disconnected. I increased soft and hard limits for tcp but it didn't help me. The problem is only for browsers. When I tried to connect by socket-io-client module from other node.js server I reached 5000 connected clients. Its very big problem for me and totally blocked me. I have tried with standard Websocket library (ws module with node.js) and problem was similar. I can reach only 456 connected clients by ws module. I tried to devide connected clients between a few instances of server. Every group of clients were connecting by other port. Unfortunately this change didn't help me. Sum of connected users was the same like before. Please help. I'm stuck.

**Comment by marco-aa** [comment] 2015-11-02 14:39
Dear piotrchludzinski,
once i had the same problem - i increased the "ulimit -n 2048" for the shell/enviroment/bash-script i was running my nodejs/socket.io code

**Comment by piotrchludzinski** [comment] 2015-11-02 14:52
The problem occurred in production so I started testing it on my laptop. I wrote something like that:

for (var i = 0; i < 700; i++) {
        var socket = io.connect('<?= Yii::app()->params['node_js_url'] ?>', {"force new connection": true});
        sockets.push(socket);
    }

Server script noticed me about 700 connected clients but after 1 minute over half of them becoming disconnected. When I check number of tcp connection always is ~500 connection. Number of connection is not fixed. I changed count of iteration to over 1000 but number of connections is still the same.

**Comment by marco-aa** [comment] 2015-11-02 15:06
As i mentioned above - not only tcp settings of the server are importend- open file descriptors limit of system resource are importend too (check manula for ulimit sysconf) and check the parameter of your server

**Comment by iav2014** [comment] 2016-07-21 13:10
see /etc/sysctl.conf  for limits,
or try (on Centos) vi  /proc/<node server process pid>/limits
this works for my:
ulimit -n 200000
ulimit -n 200000
ulimit -s 200000
and try to use node v.4

**Comment by darrachequesne** [comment] 2017-01-12 16:46
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).

**Closed by darrachequesne** 2017-01-12 16:46 UTC
Labels: Closed due to inactivity
