### ISSUE TITLE
Manual connect/disconnect sequence not possible

### ISSUE THREAD

**Issue by j-philipp** [socketio/socket.io#1667] opened 2014-07-06 21:14 UTC
I try to manually connect and disconnect a socket.io-client via console and do not understand the following behaviour I recognized in FF30, IE10 and Chrome 35 using socket.io 1.0.6.

Client: var socket = io(); Server: Client connected
Client: socket.connected; --> true
Client: socket.disconnect(); Server: Client disconnected
Client: socket.connected; --> false
Client: socket.connect(); Server: Client connected
Client: socket.connected; --> **FALSE!**
Client: socket.disconnect(); Server: No reaction.
Client: socket.connect(); Server: No reaction.
Client: <Close Browser> Server: Client disconnected

Is this a bug or am I doing something wrong here?

**Comment by mauron85** [comment] 2015-07-31 09:38
+1 I'm fighting with this, since I started using socket 1.x and maybe also with 0.9.x branch.

Seems not to be priority for socket.io team.

**Comment by darrachequesne** [comment] 2017-01-12 15:49
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).

**Closed by darrachequesne** 2017-01-12 15:49 UTC
Labels: Closed due to inactivity
