### ISSUE TITLE
Using socket.disconnect(false) on root namespace breaks all communication

### ISSUE THREAD

**Issue by manad777** [socketio/socket.io#2433] opened 2016-02-06 07:39 UTC
I've got a very short example here: https://github.com/manad777/sio-root-bug

Run it, and it should work fine. However, uncomment lines 32-34 in index.js, and all communication stops silently.

The lines in question are:

``` javascript
io.of('/').on('connect', function(socket) {
   socket.disconnect(false);
});
```

Essentially, I can use socket.disconnect(false) on any namespace, but if I use it on the root namespace, all communication stops.

**Comment by LordMajestros** [comment] 2016-02-10 14:32
See https://github.com/socketio/socket.io/pull/2415/files and https://github.com/socketio/socket.io/issues/2400 that seems to be the intended behaviour.
If you call with true it disconnects the socket with false it closes the namespace.

**Comment by manad777** [comment] 2016-02-17 19:32
You misunderstand the issue I'm reporting.

I know that disconnecting the socket from a namespace (disconnect(false)) closes that socket's connection to the namespace. That's my goal. 

What I'm saying is that disconnecting the socket from the root namespace breaks other namespaces as well. Please refer to my example, it's very short and to the point. The client connects to 3 namespaces, if you include root. Disconnecting from root should not prevent the transmission of events on the other 2 namespaces, and yet it does.

**Comment by LordMajestros** [comment] 2016-02-17 20:15
Yes, I agree that the documentation should mentions this.
I think it makes sense from the perspective that the root namespace is indeed the root.
The way clients connect when they connect to a non default(root) namespace is that they connect first to the root namespace then to the specified namespace. It follows then that if you close the root namespace it closes other namespaces(stems and branches).

**Comment by darrachequesne** [comment] 2017-01-12 15:56
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).

**Closed by darrachequesne** 2017-01-12 15:56 UTC
Labels: Closed due to inactivity
