### ISSUE TITLE
npm install socket.io error

### ISSUE THREAD

**Issue by sandeepbs39** [socketio/socket.io#2132] opened 2015-05-27 10:54 UTC
C:\node server>npm install socket.io
npm WARN package.json response-node@1.0.0 No description
npm WARN package.json response-node@1.0.0 No repository field.
npm WARN package.json response-node@1.0.0 No README data
npm WARN package.json fs@0.0.2 fs is also the name of a node core module.
npm WARN package.json fs@0.0.2 No description
npm WARN package.json fs@0.0.2 No repository field.
npm WARN package.json fs@0.0.2 No README data
\

> ws@0.5.0 install C:\node server\node_modules\socket.io\node_modules\engine.io\
node_modules\ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

|
C:\node server\node_modules\socket.io\node_modules\engine.io\node_modules\ws>if
not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\
bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (
rebuild)
Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
  bufferutil.cc
..\src\bufferutil.cc(32): warning C4996: 'NanSymbol': was declared deprecated [
C:\node server\node_modules\socket.io\node_modules\engine.io\node_modules\ws\bu
ild\bufferutil.vcxproj]
          C:\node server\node_modules\socket.io\node_modules\engine.io\node_mod
  ules\ws\node_modules\nan\nan.h(616) : see declaration of 'NanSymbol'
     Creating library C:\node server\node_modules\socket.io\node_modules\engine
  .io\node_modules\ws\build\Release\bufferutil.lib and object C:\node server\no
  de_modules\socket.io\node_modules\engine.io\node_modules\ws\build\Release\buf
  ferutil.exp
  Generating code
  Finished generating code
  bufferutil.vcxproj -> C:\node server\node_modules\socket.io\node_modules\engi
  ne.io\node_modules\ws\build\Release\\bufferutil.node
  validation.cc
..\src\validation.cc(112): warning C4996: 'NanSymbol': was declared deprecated
[C:\node server\node_modules\socket.io\node_modules\engine.io\node_modules\ws\b
uild\validation.vcxproj]
          C:\node server\node_modules\socket.io\node_modules\engine.io\node_mod
  ules\ws\node_modules\nan\nan.h(616) : see declaration of 'NanSymbol'
     Creating library C:\node server\node_modules\socket.io\node_modules\engine
  .io\node_modules\ws\build\Release\validation.lib and object C:\node server\no
  de_modules\socket.io\node_modules\engine.io\node_modules\ws\build\Release\val
  idation.exp
  Generating code
  Finished generating code
  validation.vcxproj -> C:\node server\node_modules\socket.io\node_modules\engi
  ne.io\node_modules\ws\build\Release\\validation.node
npm ERR! fetch failed https://github.com/rase-/node-XMLHttpRequest/archive/a6b6f
2.tar.gz
npm WARN retry will retry, error on last attempt: Error: tunneling socket could
not be established, cause=connect ETIMEDOUT
-

**Comment by ccarterc** [comment] 2015-05-27 20:47
I'm having similar issues.  I wonder if this is related to the specific version of node.  I'm running 12.4

**Comment by mikekidder** [comment] 2015-05-28 00:36
@ccarterc - Node version is not the problem. @rauchg is working on this.

The github repo has been corrected, but one published for npm is not.  And the version number are out of wack.  The repo here on master is 1.3.2, and npm states 1.3.5

For now you can **npm install automattic/socket.io** to install from github.  

If you are install another repo, and one of its dependencies need socket.io (webpack), this will work.  Just install socket.io first, followed by the generic "npm install".  npm will see you already have socket.io install and not install again

**Comment by rauchg** [comment] 2015-05-28 05:55
`master` was missing some hotfixes we did (1.3.3-1.3.5). Now updated!

—
@rauchg <https://twitter.com/rauchg>

**Comment by ccarterc** [comment] 2015-05-28 17:24
@mikekidder @rachg thanks so much for the quick replies. Up and running now :)

**Comment by mikekidder** [comment] 2015-05-29 20:41
@rauchg -- npm install of ***socket.io*** via github is working fine.
The npm published has several differences; the biggest diff is ***engine.io*** dependency at ***ws@0.5.0***

**npm install automattic/socket.io**
>socket.io@1.3.5 node_modules\socket.io
+-- debug@2.1.3 (ms@0.7.0)
+-- has-binary@0.1.6 (isarray@0.0.1)
+-- socket.io-adapter@0.3.1 (debug@1.0.2, socket.io-parser@2.2.2)
+-- socket.io-parser@2.2.4 (isarray@0.0.1, debug@0.7.4, component-emitter@1.1.2, benchmark@1.0.0, json3@3.2.6)
+-- engine.io@1.5.1 (base64id@0.1.0, accepts@1.1.4, engine.io-parser@1.2.1, ws@0.7.2)
+-- socket.io-client@1.3.5 (indexof@0.0.1, to-array@0.1.3, component-emitter@1.2.0, component-bind@1.0.0, backo2@1.0.2, object-component@0.0.3, parseuri@0.0.2, engine.io-client@1.5.1)

**npm install socket.io**
>socket.io@1.3.5 node_modules\socket.io
+-- debug@2.1.0 (ms@0.6.2)
+-- has-binary-data@0.1.3 (isarray@0.0.1)
+-- socket.io-adapter@0.3.1 (object-keys@1.0.1, debug@1.0.2, socket.io-parser@2.2.2)
+-- socket.io-parser@2.2.4 (isarray@0.0.1, debug@0.7.4, component-emitter@1.1.2, benchmark@1.0.0, json3@3.2.6)
+-- engine.io@1.5.1 (base64id@0.1.0, debug@1.0.3, engine.io-parser@1.2.1, ws@0.5.0)
+-- socket.io-client@1.3.5 (to-array@0.1.3, indexof@0.0.1, debug@0.7.4, component-bind@1.0.0, object-component@0.0.3, backo2@1.0.2, component-emitter@1.1.2, has-binary@0.1.6, parseuri@0.0.2, engine.io-client@1.5.1)

It's causing the build errors to display in window console.   Not sure on Mac.

**Comment by mikesigs** [comment] 2015-06-03 19:13
+1

**Comment by Karnith** [comment] 2015-07-08 02:49
I can verify mac is working on compile, windows is failing due to ws compile error.

**Comment by nmors** [comment] 2016-01-17 23:37
I seem to be having this issue on latest npm version:
node 0.12

npm ERR! Linux 3.13.0-66-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "socket.io"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! file /home/................./.npm/socket.io/1.4.4/package/package.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! Unexpected end of input
npm ERR! File: /home/nathan/.npm/socket.io/1.4.4/package/package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR! 
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

npm ERR! Please include the following file with any support request:
npm ERR!     ../../../../../../npm-debug.log

**Comment by nmors** [comment] 2016-01-17 23:54
Using node 5.4.1 on socket.io master

$npm install
npm ERR! cb() never called!

Using node 5.4.1 on latest npm version:
(same issue)
npm ERR! Linux 3.13.0-66-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "socket.io" "--save"
npm ERR! node v5.4.1
npm ERR! npm  v3.3.12
npm ERR! file /home/........./.npm/socket.io/1.4.4/package/package.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! No data, empty input at 1:1
npm ERR! 
npm ERR! ^
npm ERR! File: /home/......./.npm/socket.io/1.4.4/package/package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR! 
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

npm ERR! Please include the following file with any support request:

**Comment by nmors** [comment] 2016-01-18 01:01
running  

      $ npm cache clear

fixed the issue!

**Comment by nkzawa** [comment] 2016-01-18 01:47
should be fixed on the latest version.

**Closed by nkzawa** 2016-01-18 01:47 UTC

**Comment by nmors** [comment] 2016-01-18 05:31
latest master version still has the issue, unless you run <b>npm cache clear</b> !

my npm cache obviously had some remnants of a previous socket.io, or something like that...
