### ISSUE TITLE
Enable SO_REUSEADDR (OSError: [Errno xx] Address already in use)

### ISSUE THREAD

**Issue by azbub** [socketio/socket.io#4356] opened 2022-04-27 18:42 UTC
**Describe the bug**
I am subscribing to a wss feed and often times there is a disconnection from the server.

I want to automatically reconnect to the server so I added the following to my disconnect event : 

```
        @socketio_client.on('disconnect', namespace='/streaming')
        def on_disconnect():
            print('Server disconnected.')
            socketio_client.disconnect()
            os.system(f'python3 __scriptfile__py &')
            exit()
```

however when this event is triggered, I get this message : `OSError: [Errno 98] Address already in use`

I though I would either enable reuseaddr or kill the connection and start a new one, how does one proceed ?

**To Reproduce**

N/A

Socket.IO server version: `x.y.z`
Unknown
Socket.IO client version: `x.y.z`

4.6.0
*Client*

**Expected behavior**
close the connection then start a new session of `python3 file.py`, the port/address should not already be in use.

**Platform:**
Linux Ubuntu latest

**Additional context**
N/A

**Comment by darrachequesne** [comment] 2022-04-28 12:53
Duplicate of https://github.com/socketio/socket.io/discussions/4355.

**Closed by darrachequesne** 2022-04-28 12:53 UTC
Labels: to triage
