### ISSUE TITLE
warning cors - steps issue 1011

### ISSUE THREAD

**Issue by arivasvera** [socketio/socket.io#1972] opened 2015-01-30 14:30 UTC
Hi, I followed the steps you suggest in issue #1011 but the browser warns me of the following:

> _Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://domain.dev:3300/socket.io/1/?t=1422538971224. This can be fixed by moving the resource to the same domain or enabling CORS._

May you help me?

**Comment by invisibleroads** [comment] 2015-02-17 03:42
I have the same issue.  I think socket.io 1.3 doesn't handle ports.

Non-standard ports (other than 80) work in socket.io 1.2 but not in 1.3.

**Comment by invisibleroads** [comment] 2015-02-17 03:53
It looks like they have a fix, but it has not yet been released.
https://github.com/Automattic/socket.io-client/issues/812

**Comment by darrachequesne** [comment] 2017-01-12 15:46
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).

**Closed by darrachequesne** 2017-01-12 15:46 UTC
Labels: Closed due to inactivity
