### ISSUE TITLE
Missing error handler on `socket`.

### ISSUE THREAD

**Issue by ozergul** [socketio/socket.io#2445] opened 2016-02-15 00:03 UTC
Hi,
Why I am getting this message?

My app.js

```
io.sockets.on('connection', function(socket) {
    socket.on('login', function(data) {
        var player = new Player(socket, name)
    })      
})  

```

My player.js

```
var Player = function(socket, name) {
    this.socket = socket
    this.name_ = name
};
```

I can't resolved this and I have not an idea how can I solve this.. Is this a issue?

Error message:
`Missing error handler on`socket`.
RangeError: Maximum call stack size exceeded
    at Object.hasOwnProperty (native)
    at _hasBinary (/Users/macbook/Desktop/batak/node_modules/socket.io/node_modules/has-binary/index.js:49:45)
    at _hasBinary (/Users/macbook/Desktop/batak/node_modules/socket.io/node_modules/has-binary/index.js:49:63)
    at _hasBinary (/Users/macbook/Desktop/batak/node_modules/socket.io/node_modules/has-binary/index.js:49:63)
    at _hasBinary (/Users/macbook/Desktop/batak/node_modules/socket.io/node_modules/has-binary/index.js:49:63)
    at _hasBinary (/Users/macbook/Desktop/batak/node_modules/socket.io/node_modules/has-binary/index.js:49:63)
    at _hasBinary (/Users/macbook/Desktop/batak/node_modules/socket.io/node_modules/has-binary/index.js:49:63)
    at _hasBinary (/Users/macbook/Desktop/batak/node_modules/socket.io/node_modules/has-binary/index.js:49:63)
    at _hasBinary (/Users/macbook/Desktop/batak/node_modules/socket.io/node_modules/has-binary/index.js:49:63)
    at _hasBinary (/Users/macbook/Desktop/batak/node_modules/socket.io/node_modules/has-binary/index.js:49:63)`

**Comment by manad777** [comment] 2016-02-17 21:18
Your issue is not in the code you posted, it works fine, assuming you're not making a bazillion connections. The problem is elsewhere. Put console.log statements to see how often you enter the connection and login handlers. It's likely you have an infinite loop somewhere.

**Comment by squishybanana04** [comment] 2016-09-24 13:56
I know this thread is old but usually I get an error like that when it is a recursive object. From experience, I know that the socket object is a recursive object.

**Comment by darrachequesne** [comment] 2017-01-12 16:57
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).

**Closed by darrachequesne** 2017-01-12 16:57 UTC
Labels: Closed due to inactivity
