### ISSUE TITLE
My socket.io server dont receive or dont emit a response to my socket after random amount of time

### ISSUE THREAD

**Issue by SylvainSimon** [socketio/socket.io#3587] opened 2020-04-25 15:43 UTC
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

When sending a socket.emit request triggered inside a socket.on event, it works most of the time, but after an indefinite time, without any error occurring and without any trace of this one does not respond at all. Request events are sent but there are no more events emited in response.

### Steps to reproduce (if the current behaviour is a bug)

Have a simple socket.io serveur listening on port.

![image](https://user-images.githubusercontent.com/11244274/80283892-53527100-871b-11ea-9ee8-96da07293a76.png)

In the main event connection

![image](https://user-images.githubusercontent.com/11244274/80283912-6f561280-871b-11ea-8585-9967908ddb47.png)

Have a event emited by client to request data and who respond data with socket.emit.

![image](https://user-images.githubusercontent.com/11244274/80283926-8432a600-871b-11ea-8bd5-722aac986078.png)

Dont care to the axios call, it's work like a charm wheneve, i'v tested..

It's works until an indefinite amout of time. After this my request event sended by client dont trigger the data event anymore. and i just see the request event in the messages history of the connection 

![image](https://user-images.githubusercontent.com/11244274/80284015-eab7c400-871b-11ea-813c-d5b9d329b0e7.png)

NB : I have 3200 client connected in day and 800 in night. The error occurs randomly the night or the day, without link of the number of clients.

### Expected behaviour

I expect see the update event after i send the request event like this

![image](https://user-images.githubusercontent.com/11244274/80283972-bd6b1600-871b-11ea-92a0-d63478d38bee.png)

### Setup
- OS: Debian
- browser: Chrome extension
- socket.io version: 2.3.0

**Comment by KallynGowdy** [comment] 2020-07-29 14:43
Seems related to #3459. If you try downgrading socket.io to `2.1.1` does the issue dissapear?

**Comment by ikerya** [comment] 2020-09-26 09:23
The same trouble. After a few days the server sends a couple of events on connect (as it's designed), but then stops emitting. Restarting the server helps, but no errors are shown. 

My version: 2.2.0. I will try to downgrade to 2.1.1, but shouldn't it be fixed?

**Comment by darrachequesne** [comment] 2020-10-05 09:21
Let's close this as duplicate of https://github.com/socketio/socket.io/issues/3459.

> shouldn't it be fixed?

Without a clear way to reproduce, I'm not sure how we can fix this...

**Closed by darrachequesne** 2020-10-05 09:21 UTC
