### ISSUE TITLE
client side is getting server hang up

### ISSUE THREAD

**Issue by WolneyEEG** [socketio/socket.io#2468] opened 2016-03-03 01:10 UTC
Hello,

I have created the NodeJs project to host a server:

`
var fs = require('fs');
var https = require('https');

var express = require('express');
var app = express();

// Preparing for HTTPS hosting (This is not a self signed certificate and it is green on chrome)
var sslDir = '/home/wolney/Applications/ssl/'
var privateKey = fs.readFileSync(sslDir+'server.key');
var certificate = fs.readFileSync(sslDir+'server.crt');
var certificateAuthority = fs.readFileSync(sslDir+'sub.class1.server.ca.pem');
var credentials = {key: privateKey, cert: certificate, ca: certificateAuthority}
var serverPort = 443;

var server = https.createServer(credentials, app);
var io = require('socket.io')(server);

app.get('/', function(req, res) {
res.sendFile(__dirname + '/public/index.html');
});

io.on('connection', function(socket) {
console.log('new connection');
socket.emit('message', 'This is a message from the dark side.');
});

server.listen(serverPort, function() {
console.log('server up and running at %s port', serverPort);
});
`
public/index.html is:

`<!doctype html> <html> <head> </head> <body> <h1>I am alive!!</h1> <script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/1.3.5/socket.io.js"></script> <script> var URL_SERVER = 'https://apex5associates.com:443'; var socket = io.connect(URL_SERVER); socket.on('message', function(data) { alert(data); }); </script> </body> </html>`

It woks fine when using the browser in the browser however some clients do get hang up.

wscat -c wss://apex5associates.com:443
error: Error: socket hang up

I do no see connection log message appear.

Any idea of what I am doing wrong?

Wolney

**Comment by Xeluim** [comment] 2016-04-30 10:38
I also got this problem weird because I can't find any clue about why it is happening ...

**Comment by darrachequesne** [comment] 2017-01-12 15:58
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).

**Closed by darrachequesne** 2017-01-12 15:58 UTC
Labels: Closed due to inactivity
