### ISSUE TITLE
Clients to client server Callbacks

### ISSUE THREAD

**Issue by BeetleBird** [socketio/socket.io#2483] opened 2016-03-10 10:06 UTC
Anyone knows if client to **client callbacks** exists ?
Say , A client broadcasts to connected clients using server as 
`socket.broadcast("hellofunction" , data );` and if the clients _receive/responds_ then it will send back to the first client who broadcasted.
**So basically ,**
`client[1] - server - clients[n](Callback) - server - client[1] ( Clients Responded / Recevied )`

**Comment by dsalcedo** [comment] 2016-03-16 21:42
```javascript
//client
socket.emit('helloFunction',data);

//server
io.on('connection', function(socket){
  socket.on('helloFunction', function(data){
    socket.broadcast("hellofunction" , test );
  });
};)

//client
socket.on('hellofunction', function(data){
   //code
});
```

**Comment by ZoeLove** [comment] 2016-03-17 01:15
Can i know , how socket.broadcast runs ? Since , we need to emit it saying `socket.broadcast.emit() ;`

Other thing , i dont understand how is this to be called as callback , i think you dont read my question .

**Comment by darrachequesne** [comment] 2016-04-18 21:29
@ZoeLove hi! client-to-client callbacks do not exist, so I'm afraid you'll have to implement that yourself.

socket.broadcast basically sends a given message to every socket in a room, except the sender.

callback are simply acknowledgement:

```javascript
socket.emit('hello', 'you', function (data) {
  // the client received "hello", and responded with data
});
```

**Comment by darrachequesne** [comment] 2017-01-12 16:02
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).

**Closed by darrachequesne** 2017-01-12 16:02 UTC
Labels: Closed due to inactivity
