### ISSUE TITLE
Property 'handleUpgrade' does not exist on type 'BaseServer'.ts(2339)

### ISSUE THREAD

**Issue by GreenTea124** [socketio/socket.io#4693] opened 2023-04-15 00:13 UTC
**Describe the bug**
When you do this:

```ts
import {Server} from "socket.io";

const io = new Server({
	cors: { origin: "*" }
});

//...
io.engine.handleUpgrade(req, socket, head);
```

Code works but TypeScript produces following error:

```
Property 'handleUpgrade' does not exist on type 'BaseServer'.ts(2339)
```

**Version**

```
"socket.io": "^4.6.1",
"socket.io-client": "^4.6.1",
```

**Comment by haneenmahd** [comment] 2023-04-29 20:44
The `BaseServer` type exists on the `engine.io` codebase. This is more likely a problem with enginge.io, an engine used by Socket.io under the hood. Can you report this issue in the engine.io [repo](https://github.com/socketio/engine.io)

**Comment by haneenmahd** [comment] 2023-04-29 20:52
I don't think there is any problem with the types, I checked it out and it works fine. Can you try and re-install the packages?

**Comment by darrachequesne** [comment] 2023-05-01 06:20
The issue is that the [`BaseServer`](https://github.com/socketio/engine.io/blob/911d0e35757ea9ee93d1807c401c734661615e96/lib/server.ts#L143) class (used [here](https://github.com/socketio/socket.io/blob/59280da20b5ab6509bafb87793cc0077d60d9c27/lib/index.ts#L163)) does not expose a `handleUpgrade()` method, only [`Server`](https://github.com/socketio/engine.io/blob/911d0e35757ea9ee93d1807c401c734661615e96/lib/server.ts#L553) does.

**Comment by darrachequesne** [comment] 2023-05-01 06:29
As a temporary workaround, one could use:

```ts
import { Server } from "socket.io";
import { Server as Engine } from "engine.io";

const io = new Server({
    cors: { origin: "*" }
});

//...
(io.engine as Engine).handleUpgrade(req, socket, head);

```

**Comment by darrachequesne** [comment] 2024-10-22 06:24
For future readers:

This should be fixed by https://github.com/socketio/socket.io/commit/132d05fc0b319df7eb1b3010a91adc7d5ae58ef2, included in `socket.io@4.8.0`.

**Closed by darrachequesne** 2024-10-22 06:24 UTC
Labels: bug
