### ISSUE TITLE
Support callbacks when sending to a specific client (Does this count as a broadcast?)

### ISSUE THREAD

**Issue by aarmora** [socketio/socket.io#3438] opened 2019-05-01 21:57 UTC
### You want to:

* [] report a *bug*
* [X ] request a *feature*

### Current behaviour

When using the socket.io server and sending to a specific client with `socket.to('destination').emit('event', 'message', callBackFunction);` it throws [this error](https://github.com/socketio/socket.io/blob/e0b2cb0c5a9af768a48c43f65643412cc8edc7df/lib/socket.js#L155). While maybe this error message needs to be updated (unless this is actually viewed as a broadcast), the function certainly does not currently support callbacks when sending to a specific client.

### Desired behaviour

Callbacks supported when sending directly to a client.

### Setup
- OS: Windows
- browser: Chrome 73
- socket.io version: 2.2.0

### Other information (e.g. stacktraces, related issues, suggestions how to fix)

While it seems logical to not support callbacks on `.broadcast`s, sending an `.emit` to a specific client seems like it would make sense. Is there something that I am missing that makes this a silly feature?

Anyone else that has had this issue, have they just had to manually implement their own acks?

I really appreciate all of your work on this great package!

**Comment by tingtingtinghuang** [comment] 2019-09-20 08:29
@darrachequesne Sorry to mention you here.
Is there any other solution to solve this problem? When I send message to specific client, I can't use ack as it regarded a broadcast.

**Comment by darrachequesne** [comment] 2021-02-23 12:26
Duplicate of https://github.com/socketio/socket.io/issues/1811

**Closed by darrachequesne** 2021-02-23 12:26 UTC
