### ISSUE TITLE
"Transport not open" after upgrade to v4

### ISSUE THREAD

**Issue by RonnieRocket147** [socketio/socket.io#3838] opened 2021-03-14 19:24 UTC
**Describe the bug**
Yesterday I have upgraded an Angular application which uses socket.io-client to version 4.0.0. The server was also upgraded to 4.0.0. Today our logging recorded multiple "Transport not open" errors on the client side which were never observed before. The (minified) stack trace looks like this:

```
m.send at line 1:198353      {snip} .onClose()),this}send(e){if("open"!==this.readyState)throw new Error("Transport not open");this.write(e)}onOpen(){this.readyState="open",thi {snip}
c.flush
c.sendPacket
c.write
PVQj.t.Manager._packet
t.Socket.packet
t.Socket.emit
```

**To Reproduce**
Unable to reproduce so far. 

**Platform:**
 - Device: Chrome 89 + Safari 14
 - OS: Windows + Mac

**Additional context**
`socket.emit()` is only called when `socket.connected` returns `true`. But somehow during the emit the `Transport  not open` is thrown.

I have downgraded the client to 3.1.3 to see if the error persists and will update this issue tomorrow with the results.

**Comment by zxlin** [comment] 2021-03-16 01:34
@RonnieRocket147 are you experiencing this on page reload?

I'm seeing this in our app too, repro is something like

```JS
window.addEventListener('unload', () => {
  socket.emit(...);
});
```

**Comment by RonnieRocket147** [comment] 2021-03-16 08:02
@zxlin no we experience it during normal usage. But it might well be related to the same commit you mentioned in socketio/engine.io-client#658.

Downgrading to 3.1.3 did resolve our issue.

**Comment by darrachequesne** [comment] 2021-03-16 22:19
I could indeed reproduce, thanks.

This seems to be linked to [this commit](https://github.com/socketio/engine.io-client/commit/ed48b5dc3407e5ded45072606b3bb0eafa49c01f), included in `engine.io-client@4.1.2` and `socket.io-client@3.1.2`.

**Comment by darrachequesne** [comment] 2021-04-01 09:39
This should be fixed by https://github.com/socketio/engine.io-client/commit/d291a4c9f6accfc86fcd96683a5d493a87e3644c, included in `engine.io-client@5.0.1` and `socket.io-client@4.0.1`.

**Closed by darrachequesne** 2021-04-01 09:39 UTC
Labels: bug

**Comment by RonnieRocket147** [comment] 2021-04-02 15:26
Hi @darrachequesne 

I noticed also the strange behaviour that `socket.connected` was `true` but the transport was silently closed internally which looks like a bug to me. Is this still the case and can the `connected` property be updated when the transport is silently closed in the `onbeforeunload`?

**Comment by darrachequesne** [comment] 2021-04-02 21:37
@RonnieRocket147 yes, that is still the case. Could you please explain what your use case is? And why you think it is a bug?

Note: this change was meant to fix the issue here: https://github.com/socketio/socket.io/issues/3639

**Comment by RonnieRocket147** [comment] 2021-04-19 09:17
Let me try to explain my concern. The `Transport not open` error I noticed after upgrading the client to 4.0.0 was happening when users were performing actions in our web application. So they were not navigating away from the page. The introcuded fix just silences this error now so my fear is there is another issue which will go unnoticed now.

If `socket.connected` is true and the emit is silently dropped due to `Transport not open` how can this be detected?

Thank you!

**Comment by texonidas** [comment] 2021-05-14 00:11
I'm having a similar issue to @RonnieRocket147, ours seems to be triggered by a user clicking on tel protocol links. The user in question also has relatively poor internet, but it only occurs as an actual error when tel protocol links are clicked.

**Comment by RonnieRocket147** [comment] 2021-05-14 06:58
This could perfectly explain why I noticed random "Transport not open" errors after users where clicking on the page.
