### ISSUE TITLE
Possible filedescriptor leak

### ISSUE THREAD

**Issue by lucaswxp** [socketio/socket.io#2677] opened 2016-09-11 00:28 UTC
I'm facing a issue where the file descriptors of my node program just keep increasing.

I think the blame is in socket.io, basically I don't think socket.disconnect() is doing what is supposed to:

server

``` javascript
    var httpServer = http.createServer()
    var io = io(httpServer, {
        allowUpgrades: true,
        transports: ['websocket', 'polling']
    })

    io.on('connection', (socket) => {
           socket.on('doSomething', doSomething)
        })

    function doSomething(socket){
        // do something
        // then disconnect
        socket.emit('end');
        socket.disconnect();
        console.log(Object.keys(io.engine.clients)) // clients just keep increasing, never deleted
    }
```

client

``` javascript
      const io = require('socket.io-client')
      function callServer(){
        var socket = io(endpoint, {
          'force new connection': true, transports: ['websocket', 'polling']
        });

        socket.emit('doSomething', {payload: '...'});
        setTimeout(callServer, 100)
      }
      callServer();
```

My `io.engine.clients` just keeps increasing, and it never cleans up.

Socket.io version: 1.4.8

**Comment by lucaswxp** [comment] 2016-09-12 12:09
Could you guys help me with this? I'm out of ideas, why are file descriptors never closed? This is basically running until consumes all my RAM or I'm out of filedescriptors.

**Comment by Nibbler999** [comment] 2016-09-12 13:08
I can't reproduce your issue with the example code. `io.engine.clients` only ever has a single entry.

**Comment by lucaswxp** [comment] 2016-09-12 20:48
Could something else make the socket hang? I'm sure disconnect is getting called.

**Comment by carpii** [comment] 2016-09-15 02:45
@ lucaswxp have you used 'lsof' to monitor which file descriptors are being consumed?

**Comment by lucaswxp** [comment] 2016-09-15 16:03
@carpii Yes, that's how I discovered the leak.

I see thousands connections ESTABILISHED, but also can only reproduce ocasionally locally.

**Comment by MasterJames** [comment] 2016-09-15 18:13
Could it be the https agent and keep alive keeping the sockets in a pool?
https://nodejs.org/api/http.html

**Comment by carpii** [comment] 2016-09-16 23:46
Any reverse proxy infront of your httpd (nginx, haproxy etc?)

If you add a disconnect handler to the client socket, and just log to console, is your client receiving the socket.io disconnect event?

**Comment by lucaswxp** [comment] 2016-09-17 15:29
@carpii Yes, nginx in front doing load balancing.

I will try that.

**Comment by carpii** [comment] 2016-09-17 23:15
@ lucaswxp yes its probably some nginx config. Make sure you configure nginx to allow all relevant HTTP headers to be proxied (ie Connection: Upgrade etc)

Also check that you are actually using websocket transport. If nginx isnt proxying Connection header, it may be that you are still using polling for all clients, without realising.

I don't use nginx, but I use haproxy in a similar way. 
Haproxy has some 'keepalive' config settings which may be affecting things, no doubt nginx has similar.

**Comment by lucaswxp** [comment] 2016-09-18 04:12
@carpii I'm sure websockets are being used, no polling. Connection header is allowed. I have disabled keepalive in nginx, dont know why it's hanging.

**Comment by carpii** [comment] 2016-09-23 01:13
@lucaswxp The test code you posted above, can you reproduce the problem when its not running in a reverse-proxy environment?
Try setting up a test project so the socket.io client is hitting the socket.io server directly, and see if its still leaking FD's

**Comment by carpii** [comment] 2016-10-22 01:38
@lucaswxp Please could you close this ticket if you are not still having an issue? Thanks

**Comment by lucaswxp** [comment] 2016-10-22 05:25
Hey @carpii, I didn't have the time yet to tackle this issue, I have developed a temporary solution, but soon will have to change it, then I'll update the ticket let you know. I think the answer might be valuable for other users.

**Comment by darrachequesne** [comment] 2021-02-18 14:33
Closed due to inactivity, please reopen if needed.

**Closed by darrachequesne** 2021-02-18 14:33 UTC
