### ISSUE TITLE
Docs, client docs are not reachable

### ISSUE THREAD

**Issue by DomiR** [socketio/socket.io#2863] opened 2017-02-16 17:14 UTC
*Note*: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Steps to reproduce (if the current behaviour is a bug)

**Note**: the best way to get a quick answer is to provide a failing test case, by forking the following [fiddle](https://github.com/darrachequesne/socket.io-fiddle) for example.

### Setup
- OS:
- browser:
- socket.io version:

**Comment by hugmanrique** [comment] 2017-02-17 01:11
Duplicate of #2859 #2856 #2831 and more.

Is it so difficult to read the issues before creating the same thing?

**Closed** 2017-02-17 01:15 UTC
