### ISSUE TITLE
node server is not running. I think problem with npm install. Not able to find any resolution. please let me know how to resolve this.

### ISSUE THREAD

**Issue by sunilreddyc** [socketio/socket.io#2665] opened 2016-09-03 16:35 UTC
ramesh@sunil MINGW32 /e/letschat
$ npm install
npm WARN package.json letschat@1.0.0 No repository field.
npm WARN package.json letschat@1.0.0 No README data
npm ERR! fetch failed https://registry.npmjs.org/base64-arraybuffer/-/base64-arr                                                                                                                aybuffer-0.1.2.tgz
npm WARN retry will retry, error on last attempt: Error: getaddrinfo ENOENT regi                                                                                                                stry.npmjs.org:443
npm ERR! fetch failed https://registry.npmjs.org/blob/-/blob-0.0.4.tgz
npm WARN retry will retry, error on last attempt: Error: getaddrinfo ENOENT regi                                                                                                                stry.npmjs.org:443
npm ERR! fetch failed https://registry.npmjs.org/arraybuffer.slice/-/arraybuffer                                                                                                                .slice-0.0.6.tgz
npm WARN retry will retry, error on last attempt: Error: getaddrinfo ENOENT regi                                                                                                                stry.npmjs.org:443
npm ERR! fetch failed https://registry.npmjs.org/better-assert/-/better-assert-1                                                                                                                .0.2.tgz
npm WARN retry will retry, error on last attempt: Error: getaddrinfo ENOENT regi                                                                                                                stry.npmjs.org:443
npm ERR! fetch failed https://registry.npmjs.org/utf8/-/utf8-2.1.0.tgz
npm WARN retry will retry, error on last attempt: Error: getaddrinfo ENOENT regi                                                                                                                stry.npmjs.org:443
npm ERR! fetch failed https://registry.npmjs.org/options/-/options-0.0.6.tgz
npm WARN retry will retry, error on last attempt: Error: getaddrinfo ENOENT regi                                                                                                                stry.npmjs.org:443
npm ERR! fetch failed https://registry.npmjs.org/ultron/-/ultron-1.0.2.tgz
npm WARN retry will retry, error on last attempt: Error: getaddrinfo ENOENT regi                                                                                                                stry.npmjs.org:443
npm ERR! fetch failed https://registry.npmjs.org/has-cors/-/has-cors-1.1.0.tgz
npm WARN retry will retry, error on last attempt: Error: getaddrinfo ENOENT regi                                                                                                                stry.npmjs.org:443
npm ERR! fetch failed https://registry.npmjs.org/after/-/after-0.8.1.tgz
npm WARN retry will retry, error on last attempt: Error: getaddrinfo ENOENT regi                                                                                                                stry.npmjs.org:443
npm ERR! fetch failed https://registry.npmjs.org/parsejson/-/parsejson-0.0.1.tgz
npm WARN retry will retry, error on last attempt: Error: getaddrinfo ENOENT regi                                                                                                                stry.npmjs.org:443
npm ERR! fetch failed https://registry.npmjs.org/parseqs/-/parseqs-0.0.2.tgz
npm WARN retry will retry, error on last attempt: Error: getaddrinfo ENOENT regi                                                                                                                stry.npmjs.org:443
npm ERR! fetch failed https://registry.npmjs.org/component-inherit/-/component-i                                                                                                                nherit-0.0.3.tgz
npm WARN retry will retry, error on last attempt: Error: getaddrinfo ENOENT regi                                                                                                                stry.npmjs.org:443
npm ERR! fetch failed https://registry.npmjs.org/yeast/-/yeast-0.1.2.tgz
npm WARN retry will retry, error on last attempt: Error: getaddrinfo ENOENT regi                                                                                                                stry.npmjs.org:443
npm ERR! fetch failed https://registry.npmjs.org/xmlhttprequest-ssl/-/xmlhttpreq                                                                                                                uest-ssl-1.5.1.tgz
npm WARN retry will retry, error on last attempt: Error: getaddrinfo ENOENT regi                                                                                                                stry.npmjs.org:443
socket.io@1.4.8 node_modules\socket.io
├── debug@2.2.0 (ms@0.7.1)
├── has-binary@0.1.7 (isarray@0.0.1)
├── socket.io-parser@2.2.6 (isarray@0.0.1, json3@3.3.2, component-emitter@1.1.2, benchmark@1.0.0)
├── socket.io-adapter@0.4.0 (socket.io-parser@2.2.2)
├── engine.io@1.6.11 (base64id@0.1.0, accepts@1.1.4, ws@1.1.0, engine.io-parser@1.2.4)
└── socket.io-client@1.4.8 (to-array@0.1.4, component-emitter@1.2.0, indexof@0.0.1, object-component@0.0.3, component-bind@1.0.0, backo2@1.0.2, parseuri@0.0.4, engine.io-client@1.6.11)

ramesh@sunil MINGW32 /e/letschat

$ node server
module.js:327
    throw err;
    ^

Error: Cannot find module 'E:\letschat\server'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:974:3

ramesh@sunil MINGW32 /e/letschat
$ npm install
npm WARN package.json letschat@1.0.0 No repository field.
npm WARN package.json letschat@1.0.0 No README data

ramesh@sunil MINGW32 /e/letschat
$ cat package.json
{
  "name": "letschat",
  "version": "1.0.0",
  "description": "letschat",
  "main": "server.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "sunil",
  "license": "ISC",
  "dependencies": {
    "express": "^4.14.0",
    "socket.io":"*"
  }
}

ramesh@sunil MINGW32 /e/letschat
$ npm install
npm WARN package.json letschat@1.0.0 No repository field.
npm WARN package.json letschat@1.0.0 No README data

ramesh@sunil MINGW32 /e/letschat
ramesh@sunil MINGW32 /e/letschat
$ npm --version
2.15.9

**Comment by carpii** [comment] 2016-09-15 02:47
In what way is this related to socket.io?

**Comment by MaffooBristol** [comment] 2016-09-15 08:54
@carpii It seems a bit like 95% of issues on this project are completely unrelated to the actual project at hand. It'd be nice if someone with the power to close issues could do some spring cleaning, but rauchg tends to be a bit nonexistent in these queues.

But yeah, to the OP, your npm install isn't working, the 443s make me think there was an ssl issue. Try again, and if it still doesn't work, try `npm config set registry http://registry.npmjs.org/` and then `npm install`.

**Comment by jdc20181** [comment] 2016-09-15 12:10
Why do you guys always say this i mean seriously. If they can't even install it then whats the point? I tried using it and stackoverflow did what? Nothing they are worthless-

**Comment by MaffooBristol** [comment] 2016-09-15 12:15
Ah, long time no see!

I though you were giving up on commenting on socket.io threads mate?

The reason everyone keeps saying that the issue is not with socket.io is because *the issue is not with socket.io*. This is the issue queue for socket.io. I don't understand how that doesn't make sense.

**Comment by darrachequesne** [comment] 2016-09-16 23:17
@sunilreddyc as @MaffooBristol suggested, `Error: getaddrinfo ENOENT registry.npmjs.org:443` looks like a proxy issue or something, as if npm could not contact the said url.

I'm closing this now, as this does not seem related to socket.io itself :angel:

**Closed by darrachequesne** 2016-09-16 23:17 UTC

**Comment by marfredd** [comment] 2017-05-06 01:46
so what should we do if it said fetch failed?

**Comment by carpii** [comment] 2017-05-06 01:52
@marfredd Look for npm solutions (clear your cache, reinstall, whatever) 

its in no way related to socket.io
