### ISSUE TITLE
Acknowledgements do not seem to work on 1.3.6

### ISSUE THREAD

**Issue by overwatchcorp** [socketio/socket.io#2225] opened 2015-09-07 17:22 UTC
Client:

``` javascript
socket.emit('echo', 1, function(d) {
  console.log('received echo: ' + d);
});
```

Server:

``` javascript
io.on('connection', function(socket) {
  return socket.on('echo', function(dat, callback) {
    callback(dat);
  });
});
```

The server receives the event, yet `console.log('received echo: ' + d);` is never called. Client and server are on 1.3.6.

**Comment by darrachequesne** [comment] 2015-10-02 23:54
Hi! It may be a bit late, but the following code seems to work for me (node@v0.12.7 / socket.io-client@1.3.6 / socket.io@1.3.6):
```
var cluster = require('cluster'),
  server = require('socket.io')(),
  client = require('socket.io-client');

if (cluster.isMaster) {
  server.listen(8181);
  server.on('connection', function(socket) {
    socket.on('echo', function(data, callback) {
      console.log('[server] echo with %j', data);
      callback(data);
    });
  });
  cluster.fork();
} else {
  var socket = client('http://localhost:' + '8181');
  socket.on('connect', function () {
    socket.emit('echo', 1, function (data) {
      console.log('[client] ack with %j', data);
    });
  });
}
```
May it be caused by a connection problem between the server and the client?

**Comment by darrachequesne** [comment] 2017-01-12 15:49
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).

**Closed by darrachequesne** 2017-01-12 15:49 UTC
Labels: Closed due to inactivity
