### ISSUE TITLE
socket.on('event') missing callback crashes server 

### ISSUE THREAD

**Issue by dmastylo** [socketio/socket.io#2178] opened 2015-07-16 18:44 UTC
```javascript
socket.on('location_update', function(data, callback) {
      if (!socket.authenticated) {
        callback({ success: false, message: 'User is not authenticated.' });
        return;
      }
}
```

If the client is not listening for a callback then this crashes the server as the "callback" method is undefined.

```
Missing error handler on `socket`.
TypeError: undefined is not a function
    at Socket.<anonymous> (.../sockets/game-handler.js:124:9)
```

How can we circumvent this? Don't see anything in docs.

**Comment by codevelop** [comment] 2015-07-18 15:39
Have you tried another method?

**Comment by johnmanko** [comment] 2015-07-18 15:53
This seems like it is expected behaviour.  What am I missing?  Why not test callback before calling, and/or wrapping it in a try/catch?

**Comment by dmastylo** [comment] 2015-07-20 20:59
So I basically have to error check every time I want to pass a callback to the client otherwise my server crashes.

**Comment by johnmanko** [comment] 2015-07-25 22:00
Yes, because that is what you are coding. Socket.IO is passing your callback; it's not acting as wrapper for it.  Therefore, it's your responsibility, not Socket.IO's,to verify if there is a proper callback.

**Comment by dsalcedo** [comment] 2015-08-05 02:26
Please close this question listed as 'issue'. For questions please use stackoverflow.
Code strong.

**Closed** 2016-02-12 12:32 UTC
