### ISSUE TITLE
Reopen #1988

### ISSUE THREAD

**Issue by webarchymeta** [socketio/socket.io#2264] opened 2015-09-29 19:35 UTC
Apparently, the change from
   `uri = loc.hostname + uri;`
to
   `uri = loc.host + uri;`
in `function url(...)' in socket.io.js file of the socket.io-client package is not merged into the release branch (I am referring to version 1.3.7).

**Comment by nkzawa** [comment] 2015-11-13 02:00
I confirmed this is the case.  This should be fixed on the next release since master branch is already [fixed](https://github.com/socketio/socket.io-client/blob/master/lib/url.js#L37).
Thanks for your report.

**Comment by nkzawa** [comment] 2016-01-17 12:15
1.4.x has been released, thanks.

**Closed by nkzawa** 2016-01-17 12:15 UTC
