### ISSUE TITLE
err_connection_refused error

### ISSUE THREAD

**Issue by rashthedude** [socketio/socket.io#2176] opened 2015-07-14 21:51 UTC
Hi there, 

I'm unable to connect a Rails app using the socket.io client to the a Nodejs app socket.io server. Both are running on localhost but different ports. I did find a few answers about the very same error on stackoverflow but none seem to be working for me. Anything in particular I can do or maybe am overlooking here?

Regards, 
Rashid

**Comment by rashthedude** [comment] 2015-07-14 21:56
Even tried 'io('localhost', {port: 4210}) to no avail.

**Comment by tecnogram888** [comment] 2015-07-15 15:43
Post your error?

**Comment by rashthedude** [comment] 2015-07-15 15:45
Managed to get it to work eventually by: 'io.connect('127.0.0.1:4210)'. Localhost doesn't seem to work, any reason before I close the issue?

**Comment by tecnogram888** [comment] 2015-07-16 18:51
Mac: http://stackoverflow.com/questions/5985034/localhost-doesnt-resolve-to-127-0-0-1
Windows: http://www.softaculous.com/board/index.php?tid=4857
Or just google "localhost doesn't resolve"
I think it's a local issue due to your environment. Can you ping localhost?

**Comment by darrachequesne** [comment] 2017-01-12 15:49
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).

**Closed by darrachequesne** 2017-01-12 15:49 UTC
Labels: Closed due to inactivity
