### ISSUE TITLE
unexplained disconnect 'transport end' after upgrading

### ISSUE THREAD

**Issue by runvnc** [socketio/socket.io#777] opened 2012-03-03 03:21 UTC
After adding a dependency to my package.json today I removed my node_modules and ran npm_install.  I didn't specify any version number for socket.io so I guess it picked up the latest.

After I did that I noticed that within ? a minute or so of starting up my application, my socket would be disconnected and I see a 'transport end' info message in the node.js console output.  I having socket.io set for websockets only.  I am on Chrome 13 on Linux.

I went into package.json and set it at 0.8.7, ran npm install again, and now I am not seeing disconnects anymore.

Hopefully I wasn't just confused about something.  I did go back and repeat the steps and had the same result.  Sorry I don't have more specific information.

**Comment by dragongem45** [comment] 2015-05-20 10:29
1.3.5 errors still there

**Comment by rauchg** [comment] 2015-05-20 20:15
Is it?

**Comment by sakop** [comment] 2015-05-25 09:25
Yes, the problem still exists in 1.3.5...

**Comment by MirHamzaHasan** [comment] 2015-05-26 20:49
Problem Still exist

**Comment by stellasoft-will** [comment] 2015-06-18 06:59
Yes the problem still is occurring in 1.3.5 please fix

**Comment by bf** [comment] 2015-08-27 23:42
I think this is a haproxy client timeout issue as  @citosid has pointed out. Increase the haproxy client timeout for the websocket backend and this issue should be fixed.

**Comment by onelifemedia** [comment] 2015-09-02 17:18
I have the same issue, but I'm not using haproxy.  Does anyone know the last version where this was working?

**Comment by bf** [comment] 2015-09-02 19:10
Okay, I am also getting reports that the issue is not 100% fixed in our system. Funny thing is that I could reliably reproduce the problem by setting "timeout client 1" in haproxy to one second, and experience the bug in our frontend.

Prompted by this I increased "timeout client" to a larger number and thought the problem would go away, as the socket.io keepalive / heartbeat would have enough time to refresh the connection. This assumption is most probably wrong, and I'll keep you guys posted if I find out more things.

**Comment by fc** [comment] 2015-11-10 22:14
I posted this on a [stackoverflow](http://stackoverflow.com/questions/33136892/socketio-client-silently-loses-connection-and-creates-new-socket-transport-clos/33628774#33628774) post and for some of you this may resolve it:
"It appears that HackTimer.js and ccapture.js both replace window.setTimeout with a custom function. HackTimer.js seems to work okay if it executes before any other JavaScript. For ccapture.js you may want to try to make sure it is run as the first script. So, SocketIO first uses your browser's native setTimeout that then gets blown away by the custom setTimeout which breaks any of the currently running timers."

Search your code for to see if one of your libraries is replacing it:
```
ag 'window.setTimeout\s*='
```

**Comment by utan** [comment] 2016-01-05 01:23
Does this bug still exits? I upgraded to the master version and any mobile device disconnect in about 2 minutes with Transport close notice..

This was what it make stir away from socket.io 1 > and kept me on socket.io 0.9.17 . But now i am trying again, set a ping pong manually on the server to keep it alive and now disconnects after 19 minutes.. the interval is every 35 secs..

If i run socket.io 0.9.17 this issue is not present.. but I don't want to use it anymore since is being deprecated. Any help, this happens in browser in mobile devices.

**Comment by rauchg** [comment] 2016-01-08 18:03
@utan what are the reproduction steps?

**Comment by utan** [comment] 2016-01-08 18:37
Hi @rauchg ,

Thanks for your reply..

1) Install socket.io 1.4.0 
2) set nginx config to proxy
```
                        proxy_set_header Upgrade $http_upgrade;
           		proxy_set_header Connection "upgrade";
           		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
           		proxy_set_header Host $host;
           		proxy_http_version 1.1;
           		proxy_pass http://io_nodes;
```

3) Set you client using socket.io 1.4.0 / 2015-11-28 
4) Connect in a Mobile device.. 
5) Leave the mobile browser connected to you app then leave your phone idle.

then logs ;
```javascript
  engine:polling compressing +0ms
  engine:socket executing batch send callback +1ms
PuTTY  engine intercepting request for path "/socket.io/" +95ms
  engine handling "GET" http request "/socket.io/?EIO=3&transport=polling&t=L8YVUt6&sid=DJNvvkhmCQew_3vGAAAB" +0ms
  engine setting new request for existing client +0ms
  engine:polling setting request +0ms
  engine:socket transport error +6s
  engine:polling closing +2ms
  engine:polling transport writable - closing right away +0ms
  engine:polling writing "ï¿½1" +0ms
  socket.io:client client close with reason transport error +0ms
  socket.io:socket closing socket - reason transport error +0ms
```

You get disconnected after 3 4 minutes.. 

If using polling you get this error log;
```
 engine:socket executing batch send callback +1ms
PuTTY  engine intercepting request for path "/socket.io/" +106ms
  engine handling "GET" http request "/socket.io/?EIO=3&transport=polling&t=L8YXgi6&sid=skadf3It4qBRi0S0AAAC" +1ms
  engine setting new request for existing client +0ms
  engine:polling setting request +0ms
  engine:socket transport error +3s
  engine:polling closing +0ms
  engine:polling transport writable - closing right away +0ms
  engine:polling writing "ï¿½1" +0ms
  socket.io:client client close with reason transport error +1ms
  socket.io:socket closing socket - reason transport error +2ms
  engine intercepting request for path "/socket.io/" +373ms
  engine handling "POST" http request "/socket.io/?EIO=3&transport=polling&t=L8YXhdB&sid=skadf3It4qBRi0S0AAAC" +0ms

```

**Comment by utan** [comment] 2016-01-08 18:39
So @rauchg closed it?

Really don't think you should.

**Comment by rauchg** [comment] 2016-01-11 16:10
I didn't.

**Comment by utan** [comment] 2016-01-11 20:12
So is this a normal behavior for socket.io now? did something change in the WS protocol that now disconnect users in mobile devices if their are not plugin in and they idle?

I am banging my head to the wall with this issue it won't let me complete an upgrade.. and refactor my code with new socket.io...
My server Ubuntu 10.10 
Nginx version: Nginx/1.8.0
Node v0.10.31 // if I upgrade to 4.0 is the same thing..

using https and Nginx proxing socket.io..

Is anyone else having the same issues or is just me?

**Comment by odnarb** [comment] 2016-01-14 21:54
I think I might be as well.. very difficult to pinpoint my case though. I'm using sails.js with socket.io.

ubuntu 14.04
node v5.3.0
npm v 3.3.12
"socket.io@~1.4.3"

My client is a mix of socket.io-client and sails.io.js:

```
var socketIOClient = require('socket.io-client');
var sailsIOClient = require('sails.io.js');
var io = sailsIOClient(socketIOClient);
io.socket.on('connect', function(data){....})
```
So the initial connection lasts forever...but then after an .emit() or .broadcast() to this client, the server dumps the client after ~25 seconds to 1min AND..the client doesn't get notified of the disconnect. It thinks it's still connected.

Very frustrating.

**Comment by andrin-n-dream** [comment] 2016-01-16 13:03
I'm having a similar issue, but only if I use a secure socket (wss instead of ws). With ws everything works fine but with wss the connection gets dropped sporadically at random times (~15 minutes). No firewalls, no proxies.

**Comment by odnarb** [comment] 2016-01-19 16:37
Thank you @andrin-n-dream I think mine is related to SSL as well. I have a windows machine as the client and my ubuntu vm (same machine) as the server. Bridged network adapter. Never have had any issues with the general network connection.

Happens on SSL regardless whether I use nginx SSL or sails.js SSL termination.

**Comment by oniono** [comment] 2016-01-19 16:37
NAVER - http://www.naver.com/
--------------------------------------------

oniono@naver.com 님께 보내신 메일 <Re: [socket.io] unexplained disconnect 'transport end' after upgrading (#777)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by andrin-n-dream** [comment] 2016-01-19 16:54
I debugged forever and could not find another solution for SSL but to reconnect manually. Would be great if engine.io would do this for me and retry when the transport is closed.

**Comment by Pranoy1c** [comment] 2016-09-11 19:27
is there a solution for this? i am having the exact same issue. after a few seconds, i get a heartbeat timeout in the debug log from  server but the client still thinks it's connected.

**Comment by odnarb** [comment] 2016-09-15 16:28
Well due to other pressing issues I have upgraded my env and this is now on the backburner. Would be nice to see if node 6.5.0 makes any difference. Sails.js has updated some packages and changed its use of these low-level functions...

I just don't have time to dive into this again right now as I'm migrating a massive amount of legacy C++. Maybe later this year or January.

**Comment by ForgeableSum** [comment] 2017-08-04 20:27
lol. this is still happening on 2.0.3. 
https://github.com/socketio/socket.io/issues/3025

**Comment by ForgeableSum** [comment] 2017-08-04 22:01
also i cannot use any of the workarounds in this thread on 2.0.3:
io.set('heartbeat timeout', 99999);

@Aaron1011 Is this meant to be server-side or client code? If its server side, does anything need to be changed on the client end?

**Comment by ForgeableSum** [comment] 2017-08-04 22:20
Tried:
io.set('heartbeat timeout', 99999);
On the server side and did not fix the problem using socket.io v 2.0.3. Gonna try downgrading to 0.8.6 next.

**Comment by ForgeableSum** [comment] 2017-08-05 04:10
Could not downgrade to 0.8.6 because it indeed up being a massive rabbit hole. All the syntax has changed and since there is no documentation i could find on 0.8.6, it's a lost cause. I really don't feel like rewriting my app to downgrade to an ancient version on the hope that it might fix this issue. 

Does anyone have any ideas/fixes for v2.03? Things I've tried: 

* setting pingInterval to 9999999
* setting pingTimeout to 99999999
* sending messages automatically as a keep-alive. I send a message every 1 second, but still get the random disconnects.
* Disabled firewall
* Tried with XHR polling on/off
* Changed port from something random to 80

I'm positive it's not a coding error but is PC-specific as it happens on some and not on others. It might have something to do with the network adaptar.

**Comment by utan** [comment] 2017-08-05 13:13
@forgeableSun you should write ur app based on Primus, I refactored my app with primus and currently using socketJs with it..

Support some other project no need to change code in other to use any other real time project..

Regards.

**Comment by ForgeableSum** [comment] 2017-08-05 13:33
@utan I'd love to try it. but how exactly do i switch from socket.io with one line of code? There doesn't seem to be any examples on switching from other frameworks.

**Comment by utan** [comment] 2017-08-05 13:38
npm install browserchannel --save

var primus = new Primus(server, { transformer: 'browserchannel' });

https://github.com/primus/primus/blob/master/README.md#supported-real-time-frameworks

Hope helps.

**Comment by ForgeableSum** [comment] 2017-08-05 13:40
what does browser channel have to do with socket.io?

**Comment by utan** [comment] 2017-08-05 13:42
That's just an example how to switch to a different  framework.. 

As you asked for an example..

**Comment by ForgeableSum** [comment] 2017-08-05 13:46
okay, but socket.io is not even listed as one of the supported realtime frameworks. it's never just 1 line of code to switch APIs, I don't see how the docs can advertise that without giving any examples.

**Comment by utan** [comment] 2017-08-05 13:50
Listen, socket.io is buggy after >= 1 it has weird disconnects, me suggesting to use primus is so u can switch to a different framework..

That's why I gave u an example, of course u will need to refactor code to use primus then after u are gonna be free to try different frameworks to see which one is best for u or if one breaks then u use a different one..

Regards

**Comment by ForgeableSum** [comment] 2017-08-05 14:00
@utan I see, I was thinking it was a transformer for switching from 1 framework to another with the entire app written in that framework (like an adapter). But really, it's a transformer for seamlessly switching to frameworks with the entire app written in primus.

**Comment by utan** [comment] 2017-08-05 14:02
Indeed, u went up my head.. i am not as proficient to know the difference, thought we were talking about same thing..

Regards.

**Comment by ForgeableSum** [comment] 2017-08-05 23:58
My server logs:
client disconnect. Reason for disconnect: "transport close"
client disconnect. Reason for disconnect: "transport close"
client disconnect. Reason for disconnect: "transport close"
client disconnect. Reason for disconnect: "transport close"
client disconnect. Reason for disconnect: "transport close"
client disconnect. Reason for disconnect: "transport close"
client disconnect. Reason for disconnect: "transport close"
client disconnect. Reason for disconnect: "transport close"
client disconnect. Reason for disconnect: "transport close"
client disconnect. Reason for disconnect: "transport close"
client disconnect. Reason for disconnect: "transport close"
client disconnect. Reason for disconnect: "transport close"
client disconnect. Reason for disconnect: "transport close"
client disconnect. Reason for disconnect: "transport close"
client disconnect. Reason for disconnect: "transport close"

**Comment by ForgeableSum** [comment] 2017-08-08 20:37
Switched to ws (https://github.com/websockets/ws) which involved massive rewrites, but i now use the native websocekts browser objects and everything works perfectly. I no longer have the problem. So long socket.io!

**Comment by Fursious** [comment] 2018-01-19 17:01
I was getting random disconnects after 10 to 30 minutes. I recalled that my hosting service runs NodeJS with Passenger on an Apache shared server. I don't really understand it but basically there are meant to be issues with websockets. I am testing with setting transports: ['polling'] only while on the localhost can run with transports: ['websockets', 'polling'] without errors and dropouts. So far so good after 30min...

**Comment by darrachequesne** [comment] 2021-02-17 08:45
Closed due to inactivity, please reopen if needed.

**Closed by darrachequesne** 2021-02-17 08:45 UTC

**Comment by namxam** [comment] 2021-06-16 08:53
Well, I am seeing seeing the issue in 2021 when connecting from a 2.* client to a 3+ server. Quite annoying.

**Comment by darrachequesne** [comment] 2021-06-17 12:28
@namxam did you enable the compatibity mode?

Reference:
- https://socket.io/docs/v4/troubleshooting-connection-issues/#The-client-is-not-compatible-with-the-version-of-the-server
- https://socket.io/docs/v4/migrating-from-2-x-to-3-0/
