### ISSUE TITLE
Fix socket.io so sticky sessions are not required

### ISSUE THREAD

**Issue by dapriett** [socketio/socket.io#2140] opened 2015-06-02 13:59 UTC
I'm wondering if there is any work being done to fix socket.io so it no longer requires sticky sessions, and to rely on redis.

I'm currently using sail.js with redis and was trying to use the PM2 module to do clustering (see my issue here https://github.com/balderdashy/sails/issues/2927).  Unfortunately it breaks since the sessions don't stick.  Looks like the only fix I've found is to use this sticky-sessions module - but there is no good way to use this in sails.js without maybe hacking their code.  Is there something I can do to socket.io to make it so it doesn't matter which node instance it hits?

**Comment by OriTheMan** [comment] 2015-06-29 20:52
same issue for me

**Comment by oznu** [comment] 2015-08-06 14:18
+1

**Comment by MoLow** [comment] 2016-08-01 21:10
+1

**Comment by manast** [comment] 2016-10-20 11:57
If you only use websockets as transport protocol, any reason why it should not work without sticky sessions?
(In 2016 you probably do not need to care about browsers not supporting websockets...)

**Comment by darkterra** [comment] 2017-03-18 20:01
+1

**Comment by witoldsz** [comment] 2017-03-20 16:27
Trouble is, some users are having antivirus or some corpo-crap proxy which break WS protocol. Socket.io tries to fall back to long-pooling. Long-pooling does not work with no sticky-sessions, we have no sticky-sessions and OPS say we can't have. That's a big problem for us. Why does socket.io require sticky-session?

**Comment by manast** [comment] 2017-03-20 18:55
@witoldsz is that really based on facts? I really would like to see the numbers. For what I know, WS works pretty much where HTTP works...

**Comment by manast** [comment] 2017-03-20 18:57
@witoldsz It requires sticky sessions because it is not correctly architected. The session needs to live in the same server during the connection/upgrade procedure.

**Comment by darrachequesne** [comment] 2017-03-20 21:02
This has already been discussed: https://github.com/socketio/engine.io/issues/261  

@manast could you please give some details? From what I understand, the issue is not only when upgrading from long-polling to websocket (that one could be fixed with a Redis backend storing the sessionId between several requests), but for long-polling sessions, when the client cannot upgrade due to incompatibility, proxy, firewall...

**Comment by darrachequesne** [comment] 2021-02-18 13:47
For future readers: I've updated the documentation [here](https://socket.io/docs/v3/using-multiple-nodes/#Why-is-sticky-session-required), which explains the reasoning for the sticky sessions requirement.

Please reopen if needed.

**Closed by darrachequesne** 2021-02-18 13:47 UTC
