### ISSUE TITLE
Allow to emit message to several rooms at once

### ISSUE THREAD

**Issue by angel1st** [socketio/socket.io#3313] opened 2018-08-21 12:45 UTC
**Note**: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

For bug reports and feature requests for the **Swift client**, please open an issue [there](https://github.com/socketio/socket.io-client-swift).

For bug reports and feature requests for the **Java client**, please open an issue [there](https://github.com/socketio/socket.io-client-java).

### You want to:

* [x] request a *feature*

### Current behaviour

Thanks to https://github.com/socketio/socket.io/pull/2879 it is possible to *join* several rooms at once.

It would be nice to have the same for sending a message to multiple rooms.
Currently, we can achieve it with following code snippet:

```
['room1', 'room2', 'room3'].forEach(room => {
  // send message to all clients in the room, but the sender
  socket.broadcast.to(room).emit('message', 'nice game');
});
```

It would be much better if we can have it like that:

```
io.in(['room1', 'room2', 'room3']).emit('message', 'cool game');
socket.broadcast.to(['room1', 'room2', 'room3']).emit('message', 'nice game');
```

**Comment by soulessvadi** [comment] 2018-08-21 19:31
And I have a little addition.
io.to(socketId).ifNotIn('room').emit('message', 'cool game');

**Comment by Strate** [comment] 2018-08-22 07:25
At least we can handle multiple arguments. I use this kind of patched function:
```
io.to = (function(to) {
  return function patchedTo(...rooms) {
    return rooms.reduce(
      (thisArg, room) => to.call(thisArg, room),
      this
    )
  }
})(io.to);
```

**Comment by i-Clyde** [comment] 2018-08-27 21:42
It would be also great to do something like this:
`io.sockets.connected[{socketA, socketB, socketC, socketD}].join(roomtoken)`
`io.sockets.connected[{socketA, socketB, socketC, socketD}].leave(roomtoken)`
That will make lobby based applications easier to manage ^^

**Comment by darrachequesne** [comment] 2021-02-23 11:55
Duplicate of https://github.com/socketio/socket.io/issues/3048

**Closed by darrachequesne** 2021-02-23 11:55 UTC

**Comment by darrachequesne** [comment] 2021-03-11 14:51
For future readers: this feature was implemented by https://github.com/socketio/socket.io/commit/085d1de9df909651de8b313cc6f9f253374b702e and included in `socket.io@4.0.0`.

Syntax:

```js
io.to(["room1", "room2", "room3"]).emit(/* ... */);

socket.to(["room1", "room2", "room3"]).emit(/* ... */);
```

Documentation: https://socket.io/docs/v3/migrating-from-3-x-to-4-0/#Allow-to-pass-an-arrow-to-io-to
