### ISSUE TITLE
Why socket.broadcast.emit()  broadcast to every sockets including the sender?

### ISSUE THREAD

**Issue by HOLYYUN** [socketio/socket.io#4000] opened 2021-07-02 02:25 UTC
code
 `socket.broadcast.emit('someone create ',{roomList:roomList});`
and all the clients in namespace "/hall"
the emit had   broadcast to everyone,including the sender.

**Comment by darrachequesne** [comment] 2021-07-02 12:29
Duplicate of https://github.com/socketio/socket.io/discussions/3999.

**Closed by darrachequesne** 2021-07-02 12:29 UTC

**Comment by capital-G** [comment] 2022-12-12 11:55
Just came across the same error - make sure that you have only one connection between your client and server [I created multiple connections by creating a new connection for each vue component]. You can check the number of clients/connections via `console.log(socket.broadcast)` which will return a `BroadcastOperator`, e.g.

```typescript
BroadcastOperator {
  adapter: <ref *1> Adapter {
    _events: [Object: null prototype] {},
    _eventsCount: 0,
    _maxListeners: undefined,
    nsp: Namespace {
      _events: [Object: null prototype],
      _eventsCount: 1,
      _maxListeners: undefined,
      sockets: [Map],
      _fns: [],
      _ids: 0,
      server: [Server],
      name: '/',
      adapter: [Circular *1],
      [Symbol(kCapture)]: false
    },
    rooms: Map(3) {
      '3FdBx7kY0YGyA17BAAAB' => [Set],
      '_PA7ouIT9Z3Bs_GHAAAL' => [Set],
      'wT7q5EanSOmlacH0AAAN' => [Set]
    },
    sids: Map(3) {
      '3FdBx7kY0YGyA17BAAAB' => [Set],
      '_PA7ouIT9Z3Bs_GHAAAL' => [Set],
      'wT7q5EanSOmlacH0AAAN' => [Set]
    },
    encoder: Encoder { replacer: undefined },
    [Symbol(kCapture)]: false
  },
  rooms: Set(0) {},
  exceptRooms: Set(1) { 'wT7q5EanSOmlacH0AAAN' },
  flags: {}
}
```

This has 3 clients connected and is distributing its message to 2 of them.
