### ISSUE TITLE
Can't find executable "python"

### ISSUE THREAD

**Issue by DustinJackson** [socketio/socket.io#2185] opened 2015-07-28 20:54 UTC
came across this problem when installing browser-sync.

see https://github.com/BrowserSync/browser-sync/issues/739

**Comment by maxzeroedge** [comment] 2015-07-29 00:30
Try installing python and make sure it is in path

**Comment by edge** [comment] 2015-07-29 00:54
Looking at the issue you linked, it looks like this is a problem for Windows users.

Is `python` in your path environment variable? I don't think the python installer adds it by default.

**Comment by DustinJackson** [comment] 2015-07-29 01:26
Yes it is for windows users.  When installed Python 2.7.10 I got "Build tools for Visual Studio 2010 could not be found error".

![screenshot_1](https://cloud.githubusercontent.com/assets/3475338/8947944/5099aca6-356f-11e5-98ea-f7d4193b7e70.png)

**Comment by deltakosh** [comment] 2015-09-08 23:28
Is there a way to just not display the error?

**Comment by maxzeroedge** [comment] 2015-09-09 03:29
You have to install some version of visual studio. Preferrably 2010 because
that's what the devs were working on. But any new express edition will also
work.
P. S. Installing vs gives error stddef.h noy found.

**Comment by deltakosh** [comment] 2015-09-09 03:35
I do not think I can ask users to install vs :)

**Comment by darrachequesne** [comment] 2017-01-12 15:49
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).

**Closed by darrachequesne** 2017-01-12 15:49 UTC
Labels: Closed due to inactivity
