### ISSUE TITLE
Useless debug key set in local storage

### ISSUE THREAD

**Issue by rugk** [socketio/socket.io#2610] opened 2016-07-10 13:04 UTC
Socket.io seems to set this key, always when it is used:

```
debug = undefined
```

Socket.io v1.4.5

Discovered in Etherpad, see https://github.com/ether/etherpad-lite/issues/2985#issuecomment-225389711

**Comment by 3rd-Eden** [comment] 2016-07-10 23:18
https://github.com/visionmedia/debug/blob/master/browser.js#L127

Blame debug, not socket.io

**Comment by MasterJames** [comment] 2016-07-11 07:25
Maybe it's possible to put key deletion when undefined where you need ? 
`if (export.storage.debug === undefined) delete export.storage.debug;`
Or better skip setting if undefined? I'm not entirely sure what the problem is though.

**Comment by rugk** [comment] 2016-07-12 13:59
The problem is just that this is a useless key and the guys from Etherpad said it was Socket.io's fault.

**Comment by rugk** [comment] 2016-07-31 10:24
See https://github.com/ether/etherpad-lite/issues/2985#issuecomment-235361763:
> We don't reference the module "debug". It's a dependency of socket.io

So can you remove this debug module?

**Comment by darrachequesne** [comment] 2017-01-12 16:46
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).

**Comment by rugk** [comment] 2017-01-12 16:54
Please reopen (one cannot do it by themselves when the author closes the issue) the issue as this debug module [is still a dependency](https://github.com/socketio/socket.io/blob/master/package.json#L279) and you still gave no explanation for what this is used.

**Comment by darrachequesne** [comment] 2017-05-20 06:38
Please see https://socket.io/docs/logging-and-debugging/.

If you're using webpack, you could use something like [strip-loader](https://github.com/yahoo/strip-loader) to remove those lines from your bundle (see [example](https://github.com/socketio/socket.io-client/blob/master/support/webpack.config.slim.js))

**Closed by darrachequesne** 2017-05-20 06:38 UTC
