### ISSUE TITLE
Cannot assign to read only property 'type' of invalid utf8 sequence

### ISSUE THREAD

**Issue by bluejamesbond** [socketio/socket.io#2448] opened 2016-02-17 05:19 UTC
```
Uncaught TypeError: Cannot assign to read only property 'type' of invalid utf8 sequence 
    at WebSocket.onError (node_modules/ws/lib/WebSocket.js:426:16) 
    at Receiver.onerror (node_modules/ws/lib/WebSocket.js:851:10) 
    at Receiver.error (node_modules/ws/lib/Receiver.js:321:8) 
    at node_modules/ws/lib/Receiver.js:474:20 
    at node_modules/ws/lib/Receiver.js:361:7 
    at node_modules/ws/lib/PerMessageDeflate.js:221:5 
    at afterWrite (_stream_writable.js:346:3) 
    at onwrite (_stream_writable.js:337:7) 
    at WritableState.onwrite (_stream_writable.js:89:5) 
    at afterTransform (_stream_transform.js:78:3) 
    at TransformState.afterTransform (_stream_transform.js:54:12) 
    at Zlib.callback (zlib.js:613:5) 
```

**Comment by LordMajestros** [comment] 2016-02-17 06:35
This is an error in Websockets (https://github.com/websockets/ws) I have made a fix for it here https://github.com/websockets/ws/pull/681
Any timeline on merging this and integrating into socket.io @3rd-Eden @rauchg @nkzawa ?

**Comment by bluejamesbond** [comment] 2016-02-17 10:06
Thanks! What is the cause?

**Comment by LordMajestros** [comment] 2016-02-17 11:14
The onerror method in Receiver.js sometimes passes a string and at other times passes an Error object to the onError method in WebSocket.js  which attaches extra info to this object. This fails when a string is passed due to an attempt to assign extra members to a string as though it were an object leading to the error `Cannot assign to read only property 'type' of invalid utf8 sequence `

**Comment by darrachequesne** [comment] 2017-01-12 15:56
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).

**Closed by darrachequesne** 2017-01-12 15:56 UTC
Labels: Closed due to inactivity
