### ISSUE TITLE
Node v4.0.0 - Build failing

### ISSUE THREAD

**Issue by cjsaylor** [socketio/socket.io#2228] opened 2015-09-09 00:11 UTC
When installing socket.io latest with node V4.0.0 (stable), the following build failure occurs.

```
> utf-8-validate@1.1.0 install /app/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild

make: Entering directory `/app/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/utf-8-validate/build'
  CXX(target) Release/obj.target/validation/src/validation.o
In file included from ../src/validation.cc:15:0:
../node_modules/nan/nan.h:261:25: error: redefinition of 'template<class T> v8::Local<T> _NanEnsureLocal(v8::Local<T>)'
../node_modules/nan/nan.h:256:25: error: 'template<class T> v8::Local<T> _NanEnsureLocal(v8::Handle<T>)' previously declared here
../node_modules/nan/nan.h:661:13: error: 'node::smalloc' has not been declared
../node_modules/nan/nan.h:661:35: error: expected ',' or '...' before 'callback'
../node_modules/nan/nan.h: In function 'v8::Local<v8::Object> NanNewBufferHandle(char*, size_t, int)':
../node_modules/nan/nan.h:665:50: error: 'callback' was not declared in this scope
../node_modules/nan/nan.h:665:60: error: 'hint' was not declared in this scope
../node_modules/nan/nan.h: In function 'v8::Local<v8::Object> NanNewBufferHandle(const char*, uint32_t)':
../node_modules/nan/nan.h:672:67: error: call of overloaded 'New(v8::Isolate*, const char*&, uint32_t&)' is ambiguous
../node_modules/nan/nan.h:672:67: note: candidates are:
In file included from ../src/validation.cc:10:0:
/root/.node-gyp/4.0.0/include/node/node_buffer.h:31:40: note: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, v8::Local<v8::String>, node::encoding) <near match>
/root/.node-gyp/4.0.0/include/node/node_buffer.h:31:40: note:   no known conversion for argument 3 from 'uint32_t {aka unsigned int}' to 'node::encoding'
/root/.node-gyp/4.0.0/include/node/node_buffer.h:43:40: note: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, char*, size_t) <near match>
/root/.node-gyp/4.0.0/include/node/node_buffer.h:43:40: note:   no known conversion for argument 2 from 'const char*' to 'char*'
In file included from ../src/validation.cc:15:0:
../node_modules/nan/nan.h: In function 'v8::Local<v8::Object> NanNewBufferHandle(uint32_t)':
../node_modules/nan/nan.h:676:61: error: could not convert 'node::Buffer::New(v8::Isolate::GetCurrent(), ((size_t)size))' from 'v8::MaybeLocal<v8::Object>' to 'v8::Local<v8::Object>'
../node_modules/nan/nan.h: In function 'v8::Local<v8::Object> NanBufferUse(char*, uint32_t)':
../node_modules/nan/nan.h:683:12: error: 'Use' is not a member of 'node::Buffer'
make: *** [Release/obj.target/validation/src/validation.o] Error 1
make: Leaving directory `/app/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/utf-8-validate/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/nodejs/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.0.9-boot2docker
gyp ERR! command "/nodejs/bin/node" "/nodejs/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /app/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/utf-8-validate
gyp ERR! node -v v4.0.0
gyp ERR! node-gyp -v v3.0.1
gyp ERR! not ok

> bufferutil@1.1.0 install /app/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild

make: Entering directory `/app/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/bufferutil/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
In file included from ../src/bufferutil.cc:16:0:
../node_modules/nan/nan.h:261:25: error: redefinition of 'template<class T> v8::Local<T> _NanEnsureLocal(v8::Local<T>)'
../node_modules/nan/nan.h:256:25: error: 'template<class T> v8::Local<T> _NanEnsureLocal(v8::Handle<T>)' previously declared here
../node_modules/nan/nan.h:661:13: error: 'node::smalloc' has not been declared
../node_modules/nan/nan.h:661:35: error: expected ',' or '...' before 'callback'
../node_modules/nan/nan.h: In function 'v8::Local<v8::Object> NanNewBufferHandle(char*, size_t, int)':
../node_modules/nan/nan.h:665:50: error: 'callback' was not declared in this scope
../node_modules/nan/nan.h:665:60: error: 'hint' was not declared in this scope
../node_modules/nan/nan.h: In function 'v8::Local<v8::Object> NanNewBufferHandle(const char*, uint32_t)':
../node_modules/nan/nan.h:672:67: error: call of overloaded 'New(v8::Isolate*, const char*&, uint32_t&)' is ambiguous
../node_modules/nan/nan.h:672:67: note: candidates are:
In file included from ../src/bufferutil.cc:10:0:
/root/.node-gyp/4.0.0/include/node/node_buffer.h:31:40: note: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, v8::Local<v8::String>, node::encoding) <near match>
/root/.node-gyp/4.0.0/include/node/node_buffer.h:31:40: note:   no known conversion for argument 3 from 'uint32_t {aka unsigned int}' to 'node::encoding'
/root/.node-gyp/4.0.0/include/node/node_buffer.h:43:40: note: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, char*, size_t) <near match>
/root/.node-gyp/4.0.0/include/node/node_buffer.h:43:40: note:   no known conversion for argument 2 from 'const char*' to 'char*'
In file included from ../src/bufferutil.cc:16:0:
../node_modules/nan/nan.h: In function 'v8::Local<v8::Object> NanNewBufferHandle(uint32_t)':
../node_modules/nan/nan.h:676:61: error: could not convert 'node::Buffer::New(v8::Isolate::GetCurrent(), ((size_t)size))' from 'v8::MaybeLocal<v8::Object>' to 'v8::Local<v8::Object>'
../node_modules/nan/nan.h: In function 'v8::Local<v8::Object> NanBufferUse(char*, uint32_t)':
../node_modules/nan/nan.h:683:12: error: 'Use' is not a member of 'node::Buffer'
make: *** [Release/obj.target/bufferutil/src/bufferutil.o] Error 1
make: Leaving directory `/app/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/bufferutil/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/nodejs/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.0.9-boot2docker
gyp ERR! command "/nodejs/bin/node" "/nodejs/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /app/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/bufferutil
gyp ERR! node -v v4.0.0
gyp ERR! node-gyp -v v3.0.1
gyp ERR! not ok
npm WARN optional dep failed, continuing utf-8-validate@1.1.0
npm WARN optional dep failed, continuing bufferutil@1.1.0

> utf-8-validate@1.1.0 install /app/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild

make: Entering directory `/app/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/utf-8-validate/build'
  CXX(target) Release/obj.target/validation/src/validation.o
In file included from ../src/validation.cc:15:0:
../node_modules/nan/nan.h:261:25: error: redefinition of 'template<class T> v8::Local<T> _NanEnsureLocal(v8::Local<T>)'
../node_modules/nan/nan.h:256:25: error: 'template<class T> v8::Local<T> _NanEnsureLocal(v8::Handle<T>)' previously declared here
../node_modules/nan/nan.h:661:13: error: 'node::smalloc' has not been declared
../node_modules/nan/nan.h:661:35: error: expected ',' or '...' before 'callback'
../node_modules/nan/nan.h: In function 'v8::Local<v8::Object> NanNewBufferHandle(char*, size_t, int)':
../node_modules/nan/nan.h:665:50: error: 'callback' was not declared in this scope
../node_modules/nan/nan.h:665:60: error: 'hint' was not declared in this scope
../node_modules/nan/nan.h: In function 'v8::Local<v8::Object> NanNewBufferHandle(const char*, uint32_t)':
../node_modules/nan/nan.h:672:67: error: call of overloaded 'New(v8::Isolate*, const char*&, uint32_t&)' is ambiguous
../node_modules/nan/nan.h:672:67: note: candidates are:
In file included from ../src/validation.cc:10:0:
/root/.node-gyp/4.0.0/include/node/node_buffer.h:31:40: note: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, v8::Local<v8::String>, node::encoding) <near match>
/root/.node-gyp/4.0.0/include/node/node_buffer.h:31:40: note:   no known conversion for argument 3 from 'uint32_t {aka unsigned int}' to 'node::encoding'
/root/.node-gyp/4.0.0/include/node/node_buffer.h:43:40: note: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, char*, size_t) <near match>
/root/.node-gyp/4.0.0/include/node/node_buffer.h:43:40: note:   no known conversion for argument 2 from 'const char*' to 'char*'
In file included from ../src/validation.cc:15:0:
../node_modules/nan/nan.h: In function 'v8::Local<v8::Object> NanNewBufferHandle(uint32_t)':
../node_modules/nan/nan.h:676:61: error: could not convert 'node::Buffer::New(v8::Isolate::GetCurrent(), ((size_t)size))' from 'v8::MaybeLocal<v8::Object>' to 'v8::Local<v8::Object>'
../node_modules/nan/nan.h: In function 'v8::Local<v8::Object> NanBufferUse(char*, uint32_t)':
../node_modules/nan/nan.h:683:12: error: 'Use' is not a member of 'node::Buffer'
make: *** [Release/obj.target/validation/src/validation.o] Error 1
make: Leaving directory `/app/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/utf-8-validate/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/nodejs/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.0.9-boot2docker
gyp ERR! command "/nodejs/bin/node" "/nodejs/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /app/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/utf-8-validate
gyp ERR! node -v v4.0.0
gyp ERR! node-gyp -v v3.0.1
gyp ERR! not ok

> bufferutil@1.1.0 install /app/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild

make: Entering directory `/app/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/bufferutil/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
In file included from ../src/bufferutil.cc:16:0:
../node_modules/nan/nan.h:261:25: error: redefinition of 'template<class T> v8::Local<T> _NanEnsureLocal(v8::Local<T>)'
../node_modules/nan/nan.h:256:25: error: 'template<class T> v8::Local<T> _NanEnsureLocal(v8::Handle<T>)' previously declared here
../node_modules/nan/nan.h:661:13: error: 'node::smalloc' has not been declared
../node_modules/nan/nan.h:661:35: error: expected ',' or '...' before 'callback'
../node_modules/nan/nan.h: In function 'v8::Local<v8::Object> NanNewBufferHandle(char*, size_t, int)':
../node_modules/nan/nan.h:665:50: error: 'callback' was not declared in this scope
../node_modules/nan/nan.h:665:60: error: 'hint' was not declared in this scope
../node_modules/nan/nan.h: In function 'v8::Local<v8::Object> NanNewBufferHandle(const char*, uint32_t)':
../node_modules/nan/nan.h:672:67: error: call of overloaded 'New(v8::Isolate*, const char*&, uint32_t&)' is ambiguous
../node_modules/nan/nan.h:672:67: note: candidates are:
In file included from ../src/bufferutil.cc:10:0:
/root/.node-gyp/4.0.0/include/node/node_buffer.h:31:40: note: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, v8::Local<v8::String>, node::encoding) <near match>
/root/.node-gyp/4.0.0/include/node/node_buffer.h:31:40: note:   no known conversion for argument 3 from 'uint32_t {aka unsigned int}' to 'node::encoding'
/root/.node-gyp/4.0.0/include/node/node_buffer.h:43:40: note: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, char*, size_t) <near match>
/root/.node-gyp/4.0.0/include/node/node_buffer.h:43:40: note:   no known conversion for argument 2 from 'const char*' to 'char*'
In file included from ../src/bufferutil.cc:16:0:
../node_modules/nan/nan.h: In function 'v8::Local<v8::Object> NanNewBufferHandle(uint32_t)':
../node_modules/nan/nan.h:676:61: error: could not convert 'node::Buffer::New(v8::Isolate::GetCurrent(), ((size_t)size))' from 'v8::MaybeLocal<v8::Object>' to 'v8::Local<v8::Object>'
../node_modules/nan/nan.h: In function 'v8::Local<v8::Object> NanBufferUse(char*, uint32_t)':
../node_modules/nan/nan.h:683:12: error: 'Use' is not a member of 'node::Buffer'
make: *** [Release/obj.target/bufferutil/src/bufferutil.o] Error 1
make: Leaving directory `/app/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/bufferutil/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/nodejs/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.0.9-boot2docker
gyp ERR! command "/nodejs/bin/node" "/nodejs/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /app/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/bufferutil
gyp ERR! node -v v4.0.0
gyp ERR! node-gyp -v v3.0.1
gyp ERR! not ok
npm WARN optional dep failed, continuing utf-8-validate@1.1.0
npm WARN optional dep failed, continuing bufferutil@1.1.0
```

This is obviously a compilation problem with upstream packages on `utf-8-validate` and `bufferutil`, never-the-less a release will need to be made with their subsequent releases.

I will be adding tickets in these two projects as a result and reference this ticket.

**Comment by StevenDStanton** [comment] 2015-09-09 00:13
I had this issue and this ticket started 21 days ago solved it for me

https://github.com/socketio/socket.io/issues/2213

RamIdeas commented 5 days ago
Update: The issue with engine.io blocking this has been addressed. From @eugene1g's last comment, I believe socket.io now needs to update it's deps to pull in the engine.io fix.

socket.io currently references engine.io#f3fd4bb so upgrading to engine.io#385863d should do the job

Edit: Sorry, I've just realised that merged pull request is in a forked repo. But, I can confirm, changing the dependency (in "node_modules/socket.io/package.json") from "engine.io": "1.5.2" to "engine.io": "gsklee/engine.io#385863d" and then running npm install --production from within "node_modules/socket.io" does the trick to get this working on iojs 3.x

**Comment by cjsaylor** [comment] 2015-09-09 03:00
@StevenDStanton That workaround "works", but is not very practical. I can't really apply that patch in CI or deployment.

**Comment by Dignifiedquire** [comment] 2015-09-09 14:21
@owners Can this please be resolved and a new version released? This is causing karma users a lot of pain.

**Comment by KapuzenSohn** [comment] 2015-09-09 15:19
A fix in the next version would be nice :+1:

**Comment by SpainTrain** [comment] 2015-09-09 19:29
The issue is resolved in engine.io (https://github.com/socketio/engine.io/pull/341#issuecomment-138995427).

However, if you update socket.io to use engine.io v1.5.3, there are 23 tests that fail (even on node 0.12).  It appears that the API changes in ws 0.7->0.8 didn't affect engine.io's tests but have affected socket.io's tests. womp!

**Comment by rauchg** [comment] 2015-09-09 21:52
@SpainTrain thanks for the update. I see a few tests failing on engine.io as well with Node 0.4 now. Looking into it.

**Comment by frankleng** [comment] 2015-09-10 09:45
:+1:  to get updates

**Comment by mzgol** [comment] 2015-09-10 10:35
@frankleng To get updates you should click the Subscribe button instead of spamming every person already subscribed to this bug.

**Comment by SpainTrain** [comment] 2015-09-10 14:15
> To get updates you should click the Subscribe button instead of spamming every person already subscribed to this bug.

Sorry for contributing to spam comments, but this is a great chance to evangelize the petition that seeks to fix this GH UX fail - https://www.change.org/p/github-inc-add-voting-functionality-for-github-issues

There is also https://github.com/isaacs/github/issues/9 for general discussion.

**Comment by yosuke-furukawa** [comment] 2015-09-10 15:07
We are listing Node v4.0 issues in this thread. If you find any other issues, please write the issue and add the following url.
https://github.com/nodejs/node/issues/2798

**Comment by ChALkeR** [comment] 2015-09-12 17:11
Adding to the list: https://github.com/nodejs/node/issues/2798.

**Comment by maxime1992** [comment] 2015-09-13 20:19
Does someone have a solution ?

**Comment by KapuzenSohn** [comment] 2015-09-13 20:45
@maxime1992 a solution is currently:

- go in the package.json from socket.io
- change the dependency `engine.io` from `1.5.2` to `gsklee/engine.io#385863d` (I think `1.5.3` also does the job)
- rerun node install

Thanks to @StevenDStanton for that solution (is also the first answer in this post)

**Comment by tjwebb** [comment] 2015-09-14 03:45
is there some reason this isn't on npm yet?

**Comment by maxime1992** [comment] 2015-09-14 15:33
@StevenDStanton  & @KapuzenSohn Thanks, it worked like a charm :+1: 
I haven't understood your comment at the beginning but it's fine now.
@tjwebb +1

**Comment by stanier** [comment] 2015-09-15 01:41
+1 for @StevenDStanton's solution reposted by @KapuzenSohn.  It's worth noting that `npm shrinkwrap` would accomplish this better, as if does not require modification of a dependency `package.json`.

Vouche for consideration of implementation into the main branch.  Users of the package should not have to shrinkwrap or modify a project's `package.json` to accomplish this fix.  As it seems that `engine.io@1.5.4` will work, I suggest changing the `package.json` file to reflect a need for that version.  There shouldn't be any breaking changes to prevent the upgrade, but I can't say for certain.

**Comment by pmq20** [comment] 2015-09-16 09:36
@tjwebb Because, I guess, that the master still does not compile. See #2248

**Comment by thuutin** [comment] 2015-09-18 04:34
Roll back to socket.io@1.3.5 should do the trick. npm install socket.io@1.3.5

**Comment by garrows** [comment] 2015-09-18 06:16
@thuutin thank you! This worked and isn't a hack. 

@rauchg can you provide any light on the delay? v4.0.0 has been the stable release for a while now and as far as I can tell, its fixed in the latest engine.io.

**Comment by tomekmarchi** [comment] 2015-09-18 13:38
@thuutin Good looks.

Is there an ETA on when the master repo will have the fix for the most recent version of Socket.io?

**Comment by StevenDStanton** [comment] 2015-09-19 12:40
I have started looking for an alternate to socket.io. When such a serious bug with such a simple fix is ignored for so long it shows the maintainers of the software have either abandoned the project or lost interest in it

**Comment by pdonorio** [comment] 2015-09-19 12:45
> I have started looking for an alternate to socket.io. 

@StevenDStanton did you perhaps find any, and would you mind sharing? Thanks.

**Comment by tomekmarchi** [comment] 2015-09-19 15:08
@StevenDStanton totally agree.

**Comment by wbg** [comment] 2015-09-19 15:17
A project as big as socket.io (in terms of other modules and frameworks that depend on it) would really need a bigger team (and funding). Of course one can see that develpers can't always respond in time, but that even stuff like `yo webapp` are currently unusable paints the npm ecosystem in a really bad light.

**Comment by hinell** [comment] 2015-09-20 00:10
This error caused by simple optional dependency, see here: websockets/ws#586
It seems there is no problem with that.

**Comment by StevenDStanton** [comment] 2015-09-20 11:32
There is a huge problem with that.  If switching dependencies to a
different version fixes the compile problems then it should be updated so
people using socket.io do not have to waste time searching for how to fix a
compile error.  Issues like this left for months seriously harm faith in
the effected  projects and are what cause people to break away from
existing projects and fragment the ecosystem further

**Comment by Restuta** [comment] 2015-09-20 19:22
@StevenDStanton is my understanding correct that issue is that maintainers can't update NPM and release a new minor version with the trivial fix that _has already been merged_? So issue is _not_ that nobody can fix the code, but that people who are in control of the project are currently inactive and can't do trivial NPM package update? 

That is the situation?

**Comment by torvalamo** [comment] 2015-09-20 21:01
@Restuta Correct

**Comment by Restuta** [comment] 2015-09-20 21:38
@torvalamo I thought the process is automated as soon as you merge something to some branch like `v1.0` and test pass it's getting published to NPM.

**Comment by SpainTrain** [comment] 2015-09-20 21:52
> thought the process is automated

Doesn't appear to be in the travis file https://github.com/socketio/socket.io/blob/master/.travis.yml (would look like http://docs.travis-ci.com/user/deployment/npm/)

> people who are in control of the project are currently inactive and can't do trivial NPM package update

If this is the case, the folks that run the npm registry have processes to handle these situations - https://docs.npmjs.com/misc/disputes

**Comment by tjwebb** [comment] 2015-09-20 21:59
> issue is that maintainers can't update NPM and release a new minor version with the trivial fix that has already been merged

@rauchg why are we still waiting for this?

**Comment by mzgol** [comment] 2015-09-20 22:51
>> issue is that maintainers can't update NPM and release a new minor version with the trivial fix that has already been merged

> @rauchg why are we still waiting for this?

I don't think it's fixed; `npm install 'socket.io@socketio/socket.io#master'` fails as well, on the `bufferutil` package.

**Comment by ChALkeR** [comment] 2015-09-20 22:57
Yes. With path: `node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/bufferutil/build`.

`ws` is fixed and packaged long ago. `engine.io-client` is fine. `socket.io-client` is fine.
This means that `socket.io` should bump it's `socket.io-client` dependency version.

**Comment by rauchg** [comment] 2015-09-21 00:33
1.3.7 out! Thanks for the patience <3

—
@rauchg <https://twitter.com/rauchg>

**Comment by rauchg** [comment] 2015-09-21 00:36
This is the output you should now be getting

 ☯  ~ npm install socket.io
/

> bufferutil@1.2.1 install /Users/guillermorauch/node_modules/
socket.io/node_modules/engine.io/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node

> utf-8-validate@1.2.1 install /Users/guillermorauch/node_modules/
socket.io/node_modules/engine.io/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild

  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node
/
> bufferutil@1.2.1 install /Users/guillermorauch/node_modules/
socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node

> utf-8-validate@1.2.1 install /Users/guillermorauch/node_modules/
socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild

  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node
socket.io@1.3.7 node_modules/socket.io
├── debug@2.1.0 (ms@0.6.2)
├── has-binary-data@0.1.3 (isarray@0.0.1)
├── socket.io-parser@2.2.4 (isarray@0.0.1, debug@0.7.4,
component-emitter@1.1.2, benchmark@1.0.0, json3@3.2.6)
├── socket.io-adapter@0.3.1 (object-keys@1.0.1, debug@1.0.2,
socket.io-parser@2.2.2)
├── engine.io@1.5.4 (base64id@0.1.0, debug@1.0.3, engine.io-parser@1.2.2,
ws@0.8.0)
└── socket.io-client@1.3.7 (to-array@0.1.3, indexof@0.0.1, debug@0.7.4,
component-bind@1.0.0, backo2@1.0.2, object-component@0.0.3,
component-emitter@1.1.2, has-binary@0.1.6, parseuri@0.0.2,
engine.io-client@1.5.4)

**Comment by cjsaylor** [comment] 2015-09-21 00:39
Thanks @rauchg!

**Comment by jokeyrhyme** [comment] 2015-09-21 00:46
Building perfectly for me with Xcode 7 and Node.js 4.1 on OS X 10.11. Thanks @rauchg. <3

**Comment by joewood** [comment] 2015-09-21 00:49
Works on Windows too. Thanks @rauchg

**Comment by mzgol** [comment] 2015-09-21 00:53
Node 4 should also be added to [.travis.yml](https://github.com/socketio/socket.io/blob/master/.travis.yml).

**Comment by nerdenough** [comment] 2015-09-21 00:55
Working fine with Node.js 4.1 on Ubuntu 14.04. Thanks @rauchg

**Closed** 2015-09-21 01:36 UTC
