### ISSUE TITLE
Cannot read properties of undefined (reading 'protocol')

### ISSUE THREAD

**Issue by excalibur-knob** [socketio/socket.io#4426] opened 2022-07-17 08:29 UTC
After setting up the project and running with "npm start" in terminal, the error comes up and saying that protocol is not defined in socket.js. I tried to set up project in a new folder but same thing keeps popping up. \node_modules\socket.io\dist\socket.js:44
        if (client.conn.protocol === 3) {
                        ^
TypeError: Cannot read properties of undefined (reading 'protocol')

**Comment by darrachequesne** [comment] 2022-09-01 22:56
Hi!

The issue seems to come from this line: https://github.com/socketio/socket.io/blob/134226e96cfacab300ab8f27cf5765d5b07d0271/lib/socket.ts#L165

That being said, I don't think how `client.conn` can be undefined there. Which version of `socket.io`/Node.js are you using?

**Comment by excalibur-knob** [comment] 2022-09-02 06:53
I have installed the latest version of socket.io

**Comment by tandv592082** [comment] 2023-01-10 02:36
> I have installed the latest version of socket.io

Hi, may be not handle socket middleware like:
```js
io.use((socket, next) => {
const {name, age} = socket.handshake.auth;

if(name) {
socket.name = name;
}

if(age) {
socket.age = age;
}

next
})
```

**Comment by tulburg** [comment] 2023-06-07 16:17
Having same issue after switching to ES Module from commonjs

**Comment by darrachequesne** [comment] 2023-06-09 13:47
@tulburg I don't think this is related to the issue here, as both CommonJS and ES modules are supported.

I'm going to close this issue, as we were unable to reproduce it.

**Closed by darrachequesne** 2023-06-09 13:47 UTC
Labels: unable to reproduce

**Comment by Lokesh396** [comment] 2024-01-09 05:11
> Having same issue after switching to ES Module from commonjs
> 
> this fixed it for me
> 
> `import * as Socket from 'socket.io';`

Can you provide more code of how created the socket io instance..

**Comment by Lokesh396** [comment] 2024-01-09 05:33
This code is from the documentation and it is working fine.
`import { createServer } from "http";
import { Server } from "socket.io";

const httpServer = createServer();
const io = new Server(httpServer, { /* options */ });

io.on("connection", (socket) => {
  // ...
});

httpServer.listen(3000);`
