### ISSUE TITLE
net::ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by sametaylak** [socketio/socket.io#2431] opened 2016-02-05 07:28 UTC
Hey guys i'm trying to basic socket.io communication and i got a error as u see. Please share your solutions :) and i'm newbie so i copy paste codes please ignore them :)

This is my server.js

>  var socket  = require( 'socket.io' );
> var express = require('express');
> var app     = express();
> var server  = require('http').createServer(app);
> var io      = socket.listen( server );
> var port    = 3000;
> server.listen(port, function () {
>   console.log('Server listening at port %d', port);
> });
> io.on('connection', function (socket) {
>       io.sockets.emit('hey', 'hey i'm sent from server');
> });

This is my index.html

> ```
> var socket = io.connect('http://localhost:3000');
> socket.on('hey', function(data){
>    console.log(data);
> });
> ```

And this is my file structure
- public_html
  - node_modules
  - index.html
  - server.js

**Comment by mehmetakifalp** [comment] 2016-02-05 07:34
Hi,

You have parse error, try to like this :

io.on('connection', function (socket) {
io.sockets.emit('hey', 'hey i'm sent from server');


Also you can check this
http://www.kodrella.com/nodejssocket-io-ile-basit-bir-chat-uygulamasi-yapalim/
,






2016-02-05 9:28 GMT+02:00 Samet Aylak <notifications@github.com>:

> Hey guys i'm trying to basic socketio communication and i got a error as u
> see Please share your solutions :) and i'm newbie so i copy paste codes
> please ignore them :)
>
> This is my serverjs
>
> var socket = require( 'socketio' );
> var express = require('express');
> var app = express();
> var server = require('http')createServer(app);
> var io = socketlisten( server );
> var port = 3000;
> serverlisten(port, function () {
> consolelog('Server listening at port %d', port);
> });
> ioon('connection', function (socket) {
> iosocketsemit('hey', 'hey i'm sent from server');
> });
>
> This is my indexhtml
>
> var socket = ioconnect('http://localhost:3000');
> socketon('hey', function(data){
>    consolelog(data);
> });
>
> And this is my file structure
>
>    - public_html
>       - node_modules
>       - indexhtml
>       - serverjs
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/socketio/socket.io/issues/2431>.
>



-- 

Teşekkürler
*mehmetalp.com.tr* <http://mehmetalp.com.tr>

**Comment by sametaylak** [comment] 2016-02-05 07:52
i checked that site and i change my codes, it's running on localhost but when i upload host from ftp it's still getting same error :/

**Comment by mehmetakifalp** [comment] 2016-02-05 07:56
What is your error? Have you nodejs on your server? Should be change
localhost to yourhost.com, also the port should be available.

2016-02-05 9:53 GMT+02:00 Samet Aylak <notifications@github.com>:

> i checked that site and i change my codes, it's running on localhost but
> when i upload host from ftp it's still getting same error :/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/socketio/socket.io/issues/2431#issuecomment-180241550>
> .
>



-- 

Teşekkürler
*mehmetalp.com.tr* <http://mehmetalp.com.tr>

**Comment by darrachequesne** [comment] 2017-01-12 15:55
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).

**Closed by darrachequesne** 2017-01-12 15:55 UTC
Labels: Closed due to inactivity

**Comment by vainell** [comment] 2017-04-07 00:18
i have the same error. i tried hosting it on my laptop using my own laptop. it works when i access the site using my public ip. but when others access the site, the client connection refuse.. i am not sure what could be the problem. hope someone came up with a better solution.

**Comment by dhiefphams** [comment] 2017-04-07 06:37
@vainell Can you show your socket.io-client config ?
If you try to access with public IP, make sure you config socket.io-client with this public ip too.
For example:
You public IP is `192.168.2.77` and you server is listening at port 8080
Your socket.io-client config should be `var socket = io('http://192.168.2.77:8080');`

**Comment by PiroozMB** [comment] 2019-11-01 20:01
hi @vainell i have the same problem. what did you mean by saying "I just forgot to host the port which my server and client's are using".   I didn't get you saying host the port.

**Comment by vainell** [comment] 2019-11-02 03:43
I was hosting it using my own pc. i forgot to indicate the port

**Comment by Elvis339** [comment] 2020-03-01 16:51
Okay, so if it's working on your local machine but not on the production. It's working because you are accessing your local network from your machine.

Here's the fix.

```
const httpServer = require('http').createServer();
const app = require('./app');

const ENV = process.env.NODE_ENV || 'development';

global.io = require('socket.io').listen(httpServer);

httpServer.listen(3002, 'PRODUCTION-URL-HERE', () => {
  console.info(`Socket server started on ${PRODUCTION-URL-HERE}:${3002} (${ENV})`);
});

const src = app;

module.exports = src;

```

And the frontend:

```
componentDidMount() {
        let socket = io('PRODUCTION-URL-HERE');

        socket.on('notification', data => {
            this.setState({
                notifications: data
            })
        })
    }
```

**Comment by liyerun** [comment] 2022-11-22 13:31
hello

**Comment by Notekey** [comment] 2023-09-04 02:40
anyone?

**Comment by darrachequesne** [comment] 2023-09-13 10:37
@Notekey hi! You are commenting on an old issue, please open a new issue with all necessary details. Thanks!

Please also check our tutorial: https://socket.io/docs/v4/tutorial/introduction
