### ISSUE TITLE
npm stoped automatically

### ISSUE THREAD

**Issue by pokal4u** [socketio/socket.io#2174] opened 2015-07-10 04:38 UTC
Hi,
I am work on node express js and socket.io.

I started server like:   node app.js

after few minutes disconnected server automatically when putty was idle or ctrl+Z or ctrl+C.

How can i run server forever?

Thanks
Pokal

**Comment by sasankh** [comment] 2015-07-10 05:26
Use nodemon module

-----Original Message-----

**Comment by sasankh** [comment] 2015-07-10 05:32
Also you can install "byobu" if the system is Linux and run express from within it. That way even when putty is disconnected your node will keep running.

-----Original Message-----

**Comment by dschibait** [comment] 2015-07-10 06:19
Use screen 

Search For Linux screen... Hf!

send from iPhone

**Comment by cchamberlain** [comment] 2015-07-10 08:35
Bypass screen an go straight to tmux!

**Comment by tjhorner** [comment] 2015-07-12 01:03
For future reference, since this isn't directly related to socket.io it shouldn't go here but rather in StackOverflow. This question has actually already been answered several times over the internet, so a simple Google search would do.

**Comment by pokal4u** [comment] 2015-07-13 06:43
I installed nodemon and started with nodemon app.js.
but when ctrl+Z again disconnected.

**Comment by tecnogram888** [comment] 2015-07-15 15:44
I use the npm forever: https://www.npmjs.com/package/forever

**Comment by dsalcedo** [comment] 2015-07-31 05:17
And why create issue having stackoverflow or google?
Pd, close this "issue" please :c

**Comment by darrachequesne** [comment] 2017-01-12 15:49
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).

**Closed by darrachequesne** 2017-01-12 15:49 UTC
Labels: Closed due to inactivity
