### ISSUE TITLE
<Noob alert> Question: I want to send a file over the websocket connection with javascript. How can I do that?

### ISSUE THREAD

**Issue by Ahzam-Lathiya** [socketio/socket.io#3647] opened 2020-09-18 15:50 UTC
I am catching a file uploaded with <input type ="file"> thorugh javascript. I am printing the file and all it's contents, it shows that the content of the file is accessed and prints fine. 
Here is my code for Javascript:

`function upload_blob_application(event){
  //formElem = document.getElementById('cvform');

  event.preventDefault();

  let file = document.querySelector('input.cv').files[0];
  console.log(file);
 
  let reader = new FileReader();

  reader.onloadend = function(){

  if(event.target.readyState == FileReader.Done)
  {
   console.log('file is ready');

  }

  }
  reader.readAsArrayBuffer(file);

  socket.emit( 'process_cv', {
   payload: reader,
   query: ''
   })
  

  console.log('FIle send');
  document.querySelector('input.cv').setAttribute('disabled', 'true');
  document.querySelector('input.formsubmit').setAttribute('disabled', 'true');
}
}`

I am doing all the stuff like calling filereader and loading the file as arraybuffer but when I send the data to my server I don't get anything at all. The dictionary object of emit is empty when accessed by the backend.

**Comment by darrachequesne** [comment] 2020-10-05 12:18
Duplicate of https://github.com/socketio/socket.io/issues/3646.

**Closed by darrachequesne** 2020-10-05 12:18 UTC
