### ISSUE TITLE
Socket.io doesn't like some variables I pass to client.emit

### ISSUE THREAD

**Issue by igorpavlov** [socketio/socket.io#2029] opened 2015-03-02 20:25 UTC
I recently upgraded socket.io to 1.13.4 from 0.9.16.

Here is an error reproduction flow:
1. I make a call to mongo to retrieve some documents (info about files in my case)
2. In mongo callback I have a variable "files", containing valid JSON:
   [ { _id: 54ef4498e82c279f00000a44,
   __v: 0,
   conference: 5230a158894fb09300000098,
   ext: 'doc',
   google_id: '10JluoquhD9UVWmLmp9sf30tyNGAOT9sJECuTIzFzrmM',
   locking: 'unlocked',
   name: 'Content Sourcing Strategies_ Lytespark .docx',
   permission: 'anyoneWithLink',
   room: null,
   sharing: 'public',
   user_owner:
    { _id: 54afb6a0e9d8e08f000002f9,
      displayName: 'Vivica Pietz',
      firstName: 'Vivica',
      in_file: null,
      lastName: 'Pietz',
      pictureUrl: 'https://media.licdn.com/mpr/mprx/0_7wgjSYwccOkWk_-6mWP1S0oBvDvI3hY6mdiKwx4JUMqH532e2UpAdzdLrUi',
      shorturl: 'MT5Ud8xn8sw4',
      usedGuest: null,
      with_webrtc: true,
      minutes_conversation_counter: {},
      minutes_each_counter: {},
      packSpecific: [],
      pack: '100',
      localSendReceiveVideo: true,
      localStreamAudio: true,
      localStreamVideo: true },
   collaboratible: true,
   trashed: false } ]
3. Once I try to emit this data like this: client.emit("i connected to conference",{files: files})

Socket.io throws either:

Uncaught exception: ReferenceError: FileReader is not defined
    at _removeBlobs (/Users/igorpavlov/Development/Nodejs/lytespark/application/node_modules/socket.io/node_modules/socket.io-parser/binary.js:108:28)
    at _removeBlobs (/Users/igorpavlov/Development/Nodejs/lytespark/application/node_modules/socket.io/node_modules/socket.io-parser/binary.js:126:9)
    at _removeBlobs (/Users/igorpavlov/Development/Nodejs/lytespark/application/node_modules/socket.io/node_modules/socket.io-parser/binary.js:130:9)
    at _removeBlobs (/Users/igorpavlov/Development/Nodejs/lytespark/application/node_modules/socket.io/node_modules/socket.io-parser/binary.js:126:9)
    at _removeBlobs (/Users/igorpavlov/Development/Nodejs/lytespark/application/node_modules/socket.io/node_modules/socket.io-parser/binary.js:130:9)
    at Object.exports.removeBlobs (/Users/igorpavlov/Development/Nodejs/lytespark/application/node_modules/socket.io/node_modules/socket.io-parser/binary.js:137:3)
    at encodeAsBinary (/Users/igorpavlov/Development/Nodejs/lytespark/application/node_modules/socket.io/node_modules/socket.io-parser/index.js:207:10)
    at Encoder.encode (/Users/igorpavlov/Development/Nodejs/lytespark/application/node_modules/socket.io/node_modules/socket.io-parser/index.js:131:5)
    at Client.packet (/Users/igorpavlov/Development/Nodejs/lytespark/application/node_modules/socket.io/lib/client.js:155:20)
    at Socket.packet (/Users/igorpavlov/Development/Nodejs/lytespark/application/node_modules/socket.io/lib/socket.js:205:15)

or sometimes "Maximum call stack exceeded"
1. I understand, that I pass not pure JSON, but Mongo object, so I do JSON.parse(JSON.stringify(files)) and this solves the problem.

However, I have tons of places I just pass mongo objects to socket.io emits and it goes fine. 

Here are 2 interesting things:
1. My variable is calles "files" and the error is FileReader is not defined. Suspicious...
2. Error doesn't happen in socket.io 0.9.16, but happens in 1.13.4

**Comment by nkzawa** [comment] 2015-03-03 01:07
Did you add `Blob` or `File` to global scope? It's weird, but looks like that.
https://github.com/Automattic/socket.io-parser/blob/master/binary.js#L108

**Comment by igorpavlov** [comment] 2015-03-03 08:50
Yep, I do have a global File scope.

**Comment by nkzawa** [comment] 2015-03-09 16:46
That's the reason of this issue. socket.io checks `File` and `Blob` to detect browser environment. So if you remove `File` then this problem would not happen.

**Comment by darrachequesne** [comment] 2017-01-12 15:46
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).

**Closed by darrachequesne** 2017-01-12 15:46 UTC
Labels: Closed due to inactivity
