### ISSUE TITLE
update 1.3.7 to 1.4.5 stop sending messages to roms

### ISSUE THREAD

**Issue by diegoug** [socketio/socket.io#2451] opened 2016-02-18 20:52 UTC
Hello, I have a problem with socket.io update version 1.3.7 to 1.4.5 and stop sending messages to the rooms, you know what might have happened?

My code is very simple, it is only that:

```
// socket to room, using roomKey
socket.join(roomKey);
// room emmit
this.io.to(roomKey).emit(channel, message);
```

But when I want to send a message by a room in particular nothing happens, and if I go back to version 1.3.7 works again, you know it can be?

**Comment by CharGomez** [comment] 2016-02-19 16:16
Same happens to me, any clue ? Thx.

**Comment by svarunan** [comment] 2016-02-21 14:44
I too have this issue after new update. 
on server side socket.id gives me /#LF6L4-bVXD4u3fT9AAAA
on client side its LF6L4-bVXD4u3fT9AAAA
'/#' creates all new problem now. 
only io.emit works bit io.sockets.connected returns ["/#LpjTrYgEzpl2wbi2AAAB"]

Team, Please help us get a workaround or give a solution to this.

**Comment by oliversalzburg** [comment] 2016-02-22 11:37
We had a similar issue that was primarily caused by this change: https://github.com/socketio/socket.io/issues/1956

**Comment by jcsla** [comment] 2016-03-05 17:56
I had same issue.. plz help.

**Comment by dottodot** [comment] 2016-05-25 20:09
Same here with 1.4.6, not used socket.io in a while and thought I was doing something wrong, turns out rooms don't work at all as downgrading to 1.3.7 works as documented.

**Comment by darrachequesne** [comment] 2017-01-12 16:02
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).

**Closed by darrachequesne** 2017-01-12 16:02 UTC
Labels: Closed due to inactivity
