### ISSUE TITLE
Handshake authorization stuck.

### ISSUE THREAD

**Issue by EugeneKostrikov** [socketio/socket.io#1934] opened 2015-01-07 09:40 UTC
Hello, 

I'm trying to figure out how to fail authorization correctly. If i callback with error from the middleware the server is getting stuck. Tried both middleware style and `io.set('authorization')`. The code is as follows.

Client is the same for both scenarios:

``` js
        socket = ioClient.connect(options.ioUrl + "/people", {query: query, forceNew: true});
        socket.on('data', function(data){
          console.log(data);
        });
        socket.on('connect', function() {
          callback();
        });
        socket.on('error', function(err){
          callback(err);
        });
```

Server with `io.set`

``` js
      io.set('authorization', function(handshake, done){
        setTimeout(function(){
          done(null, false);
        }, 100);
      });
```

Server with middleware 

``` js
      io.use(function(socket, next){
          setTimeout(function(){
           next(new Error('Auth failed');
          });
    });
```

It looks like the problem is `transport`. The state is still `opening` when i fail the auth. However if i use timeouts, it is `writable`. The client does not get any event at all. 
If i do not fail the auth - `connect` event fires.
Any idea what is wrong here?

**Comment by aly006** [comment] 2015-01-10 02:21
Could you perhaps be a bit more specific as to the environment from which you are experiencing this issue? (Browser, Node version, OS, etc.)

I wrote a sample test and was not able to reproduce the issue.
Code for the test is here: https://gist.github.com/aly006/cbc84a57d24744b67a32

Let me know if I am misunderstanding anything.

**Comment by peteruithoven** [comment] 2015-02-17 13:00
@EugeneKostrikov, maybe you're experience this issue: https://github.com/Automattic/socket.io/issues/1888
Since you're trying to connect to a namespace. What happens when you try to connect to the root namespace? 
@aly006, maybe you can try to include a namespace in your sample?

**Comment by serhiisol** [comment] 2016-11-22 13:33
Experiencing exactly the same problem that @EugeneKostrikov has mentioned.

setTimeout works only when client has really strong connection, otherwise he won't get `error` event.

Tried with throttling - same result, won't receive `error` event

**Comment by murrayju** [comment] 2018-04-23 23:43
See #3089 and #2342. The error is being fired on the default namespace, and not your custom namespace. I don't think it should work this way, but that's the current behavior.

**Comment by darrachequesne** [comment] 2021-02-17 09:02
For future readers: this was fixed in Socket.IO v3

Documentation:

- https://socket.io/docs/v3/migrating-from-2-x-to-3-0/#No-more-implicit-connection-to-the-default-namespace
- https://socket.io/docs/v3/middlewares/

**Closed by darrachequesne** 2021-02-17 09:02 UTC
