### ISSUE TITLE
Getting a list of all rooms in a session

### ISSUE THREAD

**Issue by Kannaj** [socketio/socket.io#2388] opened 2016-01-14 12:05 UTC
I'm trying to get a list of created rooms in an application by using io.sockets.adapter.rooms. I'm just getting strings of socket id's and not their names. I'm not sure where i'm going wrong. Can anyone help?

Here's a snippet of my code 

```
socket.on('get_rooms',function(){
      var room_list = {};
      for (var room in io.sockets.adapter.rooms){
        if(room.indexOf('/chat_infra') == 0){
          var roomName = room.replace('/chat_infra/','');
          room_list[roomName] = io.sockets.adapter.rooms[room].length;
        }else{
          var roomName = room;
          room_list.roomName = io.sockets.adapter.rooms[room].length;
        }
      }
      socket.emit('rooms_list',room_list);
    });  
```

the rooms are created via this snippet

```
  socket.on('join_room',function(room){
      socket.join(room.name);
      // var comSocket = self.chatCom.sockets[socket.id];
      var comSocket = self.chatCom.connected[socket.id];
      comSocket.join(room.name);
      comSocket.room = room.name;
      // socket.in(room.name).broadcast.emit('user_entered',{'name': socket.nickname});
      socket.broadcast.to(room.name).emit('user_entered',{'name':socket.nickname});
      // io.to(room.name).emit('user_entered',{'name':socket.nickname});
    });
  });  
```

Also created a stackoverflow question for this

http://stackoverflow.com/questions/34760230/getting-a-list-of-rooms-from-a-socketio-application

**Comment by Kannaj** [comment] 2016-01-14 13:22
Used the below code to solve the issue. but this looks more like a hack to me . Is there a better way?

```
    socket.on('get_rooms',function(){
      var room_list = {};
      var rooms = io.nsps['/chat_infra'].adapter.rooms;

      for (var room in rooms){
        if (!rooms[room].hasOwnProperty(room)) {
                console.log(rooms[room]);
                room_list[room] = Object.keys(rooms[room]).length;
            }
      }
      console.log(room_list);
      socket.emit('rooms_list',room_list);
    });
```

**Comment by sandro-csimas** [comment] 2016-01-15 04:48
I was getting the socket rooms using this code:
````
socket.rooms.forEach(function(room) {
    if(isCircleRoom(room)) {
        .....
    }
});
````
When i upgrade to the newer socket.io version i'm getting [TypeError: socket.rooms.forEach is not a function] because socket.rooms is not an array anymore =(.

**Comment by nkzawa** [comment] 2016-01-17 06:51
Unfortunately, there is no good way to do that for now, especially when multiple nodes were running with redis-adapter.

**Comment by darrachequesne** [comment] 2017-01-12 15:53
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).

**Closed by darrachequesne** 2017-01-12 15:53 UTC
Labels: Closed due to inactivity, Feature request
