### ISSUE TITLE
Website chat demo not working

### ISSUE THREAD

**Issue by nacholibre** [socketio/socket.io#2622] opened 2016-07-27 15:04 UTC
So I wanted to check out the demo, but It's not working.

http://chat.socket.io/

`Uncaught ReferenceError: io is not defined`

**Comment by dospunk** [comment] 2016-07-28 23:59
To add to this, none of the demos are working either

**Comment by jhl0903** [comment] 2016-07-31 19:35
It's not working for me either. When will this be fixed?

**Comment by albanirneves** [comment] 2016-08-24 17:09
It's not working for me too

**Comment by jwickens** [comment] 2016-12-12 14:16
still doesn't work. I just tried on chrome, firefox and safari on a mac (all relatively recent versions.) On chrome I get the following error which seems to be the root cause:
```
GET http://chat.socket.io/socket.io/socket.io.js
net::ERR_INCOMPLETE_CHUNKED_ENCODING
```
looks like a server config error

**Comment by darrachequesne** [comment] 2016-12-13 23:23
Until we migrate the website, please use https://socketio-chat-dyfwapyfni.now.sh/

**Comment by darrachequesne** [comment] 2017-05-20 06:39
That should be fixed now, thanks: https://socket.io/demos/chat/

**Closed by darrachequesne** 2017-05-20 06:39 UTC
