### ISSUE TITLE
Conflicting @types/node version

### ISSUE THREAD

**Issue by andrejleitner** [socketio/socket.io#3793] opened 2021-02-04 11:19 UTC
**Describe the bug**
There is fixed version of node types defined as socket.io dependency causing conflicts.
https://github.com/socketio/socket.io/blob/12221f296d52b3dcde34246bd1ada98871b4ada3/package.json#L48

**To Reproduce**

- install other version of `@types/node` as your dev dependency of your project (e.g. `@types/node@12`)
- install `socket.io@3` as original dependency of your project
- try to compile typescript file, you will get the following error:
```
node_modules/socket.io/dist/client.d.ts:1:23 - error TS4090: Conflicting definitions for 'node' found at
'~/example_project/node_modules/socket.io/node_modules/@types/node/index.d.ts' and
'~/example_project/node_modules/@types/node/index.d.ts'.
Consider installing a specific version of this library to resolve the conflict.

1 /// <reference types="node" />
```

**Comment by ironicbrew** [comment] 2021-02-10 14:56
Unable to reproduce following the above instructions, everything compiles on my end without issue even with conflicting ```@types/node``` dev dep versions in my app vs. socket io

Can you try to ```rm -rf node_modules``` and reinstall with ```npm i```? A bungled ```package-lock.json``` might be the issue here.

If that doesn't work I'd need a repo to clone that reproduces this issue as something is key is missing from the reproduction instructions, perhaps some setting in ```tsconfig.json``` is causing the build to trip?

**Comment by andrejleitner** [comment] 2021-02-15 10:08
Hey @ironicbrew, thanks for looking at it. Before posting it here, I've tried a clean installation exactly as you suggested. It just didn't help. Btw. doesn't it make sense to have that and other @types defined as dependencies (non-dev)?

**Comment by Sumolari** [comment] 2021-02-15 17:02
> Btw. doesn't it make sense to have that and other @types defined as dependencies (non-dev)?

I was about to open a different issue about moving `@types/node` to devDependencies. It's a big package (around 740kb) and it should give no value on runtime.

**Comment by ironicbrew** [comment] 2021-02-15 21:10
@andrejleitner, Are you using any additional config in your ```tsconfig``` that may be a little more strict than mine? 

Only other thing I can think of is if you fork the repo and switch the troublesome dependency to a devDependency as suggested by @Sumolari and then npm install that it would be interesting to see if that resolved the issue.

**Comment by darrachequesne** [comment] 2021-02-24 21:51
@andrejleitner I could indeed reproduce, thanks.

I see two possible solutions:

- put the types as devDependencies (which was the case before https://github.com/socketio/socket.io/issues/3690)
- use a more relaxed version, for example `"@types/node": ">=10",` instead of `"@types/node": "^14.14.10",`

[This comment](https://github.com/microsoft/types-publisher/issues/81#issuecomment-234051345) suggests to go for the latter.

What is your opinion on this?

**Comment by andrejleitner** [comment] 2021-02-25 09:20
Thanks @darrachequesne for checking and for the link to interesting reading too. I quite like also [the latter comment](https://github.com/socketio/socket.io/issues/3690#issuecomment-761901591), but don't have a strong opinion either. 

However, the second option seems right to me, at least having this definition here:
https://github.com/socketio/socket.io/blob/7467216e024e4a5c99f23775c31b7041ca180560/package.json#L92

... and it should fix the conflict (the original issue).

**Comment by darrachequesne** [comment] 2021-02-26 00:25
Fixed by https://github.com/socketio/socket.io/commit/67a61e39e65f26c9c19b7ddaed8845e8c09e4e84, included in [`socket.io@3.1.2`](https://github.com/socketio/socket.io/releases/tag/3.1.2).

**Closed by darrachequesne** 2021-02-26 00:25 UTC
Labels: bug
