### ISSUE TITLE
Latency Varies Wildly between two clients

### ISSUE THREAD

**Issue by tencircles** [socketio/socket.io#3013] opened 2017-07-24 16:13 UTC
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behavior
Events that are sent from client A at a regular interval of 1000ms. Arrive at client B at intervals of anywhere between 200 and 2300 ms. 

### Steps to reproduce
clone https://github.com/tencircles/socketio-latency-test and follow the instructions to reproduce the bug.

### Expected behavior
Events that are sent from client A at time N should arrive at at time N + trip time to server + trip time to client B.

### Setup
- OS: OS X 10.12.5, Windows 10, Ubunutu 16.04, IOS 10.3.2
- browser: Chrome, Firefox, Safari, and Safari Mobile
- server environment: Node JS v7.10.0 on Ubuntu 16.04, Node JS v7.10.0 on OS X 10.12.5
- socket.io version: 2.0.3

### Other information
I'm trying to send a steady stream of events at a rate of approximately 30 events per second from one client to all other clients in a room in an application I'm developing. I notice in the application that periodically groups of 10 or more events will all arrive at the same time with the same timestamp from the server. This seems to indicate that either events are written to a buffer on the server and only read at some irregular interval, or that events are written to a buffer on the client and only emitted to the server at some irregular interval. This is just my best guess here. 

Any help would be greatly appreciated or if you can point me to a location in the source I'd be happy to submit a pull request. The application I'm developing requires that events are sent without any excess delay imposed by anything other than network conditions.

**Comment by Nibbler999** [comment] 2017-07-25 05:37
What am I looking for when I run the test case? Looks normal to me.

**Comment by tencircles** [comment] 2017-07-25 14:02
You're looking for times in the console which are greater than or less than ~1000. A client broadcasts an event to all other clients every 1000ms. Which means that in your second client you should see events received every ~1000ms, I understand that this will fluctuate slightly, but if you're running this on the same machine, these fluctuations shouldn't be larger that ~50ms at most. 

What I'm seeing in this test case across several different machines is that often more than ~2000ms has elapsed between events received. Immediately followed by a second event 0-1ms later. 

What I'm seeing in the actual application where events are emitted every ~33ms is that groups of 10 or more events from client A all arrive at the server at the same time. The expected behavior is that they all arrive 33ms apart (plus or minus some network latency).

**Comment by lpinca** [comment] 2017-07-28 10:27
Did you try to force the WebSocket transport and see if the issue happens with both libraries (ws and uws) used by Socket.IO? I wonder if this is the result of corking.

By default Socket.IO uses uws and falls back to ws. You can specify what library to use by setting the `wsEngine` option to `'ws'` or `'uws'`.

**Comment by tencircles** [comment] 2017-07-28 18:07
I've forced WebSocket transport in the application (not this test), that's why I was confused by these results.

**Comment by lpinca** [comment] 2017-08-02 17:48
@tencircles yes but I wonder if it's caused by the underlying WebSocket library. I doubt but if you can try to set the `wsEngine` option to `'ws'` and repeat the test.

**Comment by darrachequesne** [comment] 2021-06-28 07:55
I think this was fixed in `socket.io@2.1.0`, as we reverted to `ws` as the default WebSocket server implementation.

Please reopen if needed.

**Closed by darrachequesne** 2021-06-28 07:55 UTC
