### ISSUE TITLE
How to solve the problem of garbage

### ISSUE THREAD

**Issue by xiaojunl** [socketio/socket.io#2030] opened 2015-03-03 08:20 UTC
client -> socket.emit('say', '才能开');
server -> socket.on('say', function (msg) {console.log('msg='+msg)});  
and get 'msg=æè½å¼'

**Comment by nkzawa** [comment] 2015-03-09 16:37
What version of socket.io do you use? I think this doesn't happen with the latest one.

**Comment by xiaojunl** [comment] 2015-03-10 09:52
socket.io version is v1.3.5, but my ios client  is based on the v1.0.6

**Comment by nkzawa** [comment] 2015-03-10 10:02
I think that's the reason of the issue. You have to use a same version on both server and client.

**Comment by peteruithoven** [comment] 2015-03-10 10:32
@nkzawa, are you sure? Don't you mean that they both should be v1.3.x for example? 
If not that would be very problematic. If you're building anything that can't retrieve the client javascript from the server (like a non javascript based app) you can't be sure they will be in-sync. You can't control when people update.

**Comment by nkzawa** [comment] 2015-03-10 10:40
@peteruithoven sorry, I should say it's better to use a same version as much as possible.
In this case, the problem is because there is a small protocol change between 1.0.x and 1.1.x.

**Comment by darrachequesne** [comment] 2017-01-12 15:47
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).

**Closed by darrachequesne** 2017-01-12 15:47 UTC
Labels: Closed due to inactivity
