### ISSUE TITLE
socket.io cluster with sticky-session  problems

### ISSUE THREAD

**Issue by hussion** [socketio/socket.io#1944] opened 2015-01-15 08:42 UTC
Recently, i do the socket.io stress test,  what make me confused is socket.io use one cpu can support more than 20k connections, but use cluster modle with stikcy-session, it only can support 4k connections. Can someone explain this is what causes it ? help me please !

At last, i hope socket.io can provide a affcial example with cluster. thx. :)

**Comment by peteruithoven** [comment] 2015-01-15 09:14
That might be because then it needs to communicate between multiple instances, using redis pub sub. 
This pull request should help with that: https://github.com/Automattic/socket.io-redis/pull/46
Looks like the author also added a small performance test.

**Comment by Hussion** [comment] 2015-01-15 09:35
@peteruithoven you mean: i need use multiple instances and not use cluster ?

**Comment by peteruithoven** [comment] 2015-01-15 09:41
When you use clusters you in effect also use multiple instances. Maybe you need to read a little bit more before you start asking for help.

**Comment by Hussion** [comment] 2015-01-15 10:00
@peteruithoven First of all want to thank you very much, now my question is I said above , I use a cpu core test (one instance), they can support the 20k number of connections, but I used the cluster mode, but only supports 4k connections , Why do I use the cluster with sticky-session after a drop in performance so much ? you understand I mean?

**Comment by peteruithoven** [comment] 2015-01-15 10:09
I think I understand you. Please at least read the pull request #46
<https://github.com/Automattic/socket.io-redis/pull/46> description
and socket.io-redis
issue #41 <https://github.com/Automattic/socket.io-redis/issues/41>.

**Comment by Hussion** [comment] 2015-01-15 10:18
@peteruithoven oh my friend, what important is i think i should let you know:  I did NOT USE "socket.io-redis" ,  i am now just test how many connections the socket.io server can support. 

so now you understand ?

**Comment by ebuildy** [comment] 2015-01-27 10:44
Do you have a proxy such as Nginx in front of your multiple socket.io servers?

**Comment by darrachequesne** [comment] 2017-01-12 15:40
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).

**Closed by darrachequesne** 2017-01-12 15:40 UTC
Labels: Closed due to inactivity
