### ISSUE TITLE
In Firefox, connection ....  was interrupted while the page was loading

### ISSUE THREAD

**Issue by selay** [socketio/socket.io#2016] opened 2015-02-21 00:08 UTC
Hi, 
it shows  connection to ws:.....  was interrupted while the page was loading in Firefox but works. 
I saw many possible fix suggestions on different sites but none of them work now. 
It works fine in other browsers without any error/warning in the console. 
I am using socket.io 1.3.4 and firefox latest version 35.0.1.

**Comment by oxhak** [comment] 2015-02-28 21:22
Same here, random disconnect on firefox, not on chrome. I can't understand what is the problem.

**Comment by selay** [comment] 2015-08-04 23:46
It still happens on the latest version 1.3.6

**Comment by arusahni** [comment] 2015-08-19 17:09
[There's an open ticket for this on Bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=712329). The "workaround" doesn't work for me.

**Comment by dragongem45** [comment] 2015-08-22 13:02
This will fix it 
window.onload(function()
{
//code goes here
});

**Comment by Aviditas** [comment] 2016-03-17 23:29
Issue is still alive apparently getting the exact same error, I've tried both versions 1.2.0 I believe and the one that comes with the latest NPM package. Any workarounds?

**Comment by UndergroundLabs** [comment] 2016-03-19 14:25
I too am getting the same error in Firefox. Can't seem to find a fix anywhere.

**Comment by chchrist** [comment] 2016-04-19 11:50
I'm getting this error in FF 45 and my websocket connection times out.

**Comment by maxpaynestory** [comment] 2016-04-29 13:52
I am getting this error on FF 46 + Mac, FF 45 + Windows 10.

**Comment by chchrist** [comment] 2016-04-29 14:10
For us the problem was the version of the net scaler we used

**Comment by maxpaynestory** [comment] 2016-04-29 14:15
Are you referring to the python script net scaler? I am not using it and still getting this error on socket.io

**Comment by gotev** [comment] 2016-07-15 12:56
Had the same issue on OS X 10.11.5 and Firefox 47. With the following configuration it works without errors for me on Firefox 47 and Chrome 51.0.2704.103.

`package.json`
```json
{
  "name": "socket-io-test",
  "version": "1.0.0",
  "description": "socket io test",
  "main": "app.js",
  "scripts": {
    "start": "node app.js"
  },
  "repository": {
    "type": "git",
    "url": ""
  },
  "keywords": [],
  "author": "Aleksandar Gotev",
  "license": "ISC",
  "homepage": "",
  "dependencies": {
    "express": "^4.14.0",
    "socket.io": "^1.4.8"
  }
}
```

`config.json`
```json
{
    "process_title": "wstest",
    "web_server_port": 3000,
    "max_seconds_to_wait_on_kill": 3
}
```

`app.js`
```java
var expressFramework = require('express');
var express = expressFramework();
var fs = require('fs');

//read configuration
var configuration = JSON.parse(fs.readFileSync('config.json', "utf8"));

//setup express
express.set('json spaces', 2);
express.disable('x-powered-by'); //disable express framework credits
express.use("/", expressFramework.static(__dirname + "/static")); //serve static files

//start web server
var webServer = express.listen(configuration.web_server_port, function () {
    console.log("Web server listening on port " +  configuration.web_server_port); 
});

//setup socket.io
var io = require('socket.io')(webServer);
io.on('connection', function (socket) {
    socket.emit('hello', {
        msg: "hello"
    });
});

//setup process
var killHook = function killHook() {
    console.log("Detected kill signal");

    webServer.close(function() {
        console.log("Graceful shutdown");
        process.exit(0);
    });

    setTimeout(function () {
        console.log("Waited for " + configuration.max_seconds_to_wait_on_kill + " seconds. Force kill.");
        process.exit(0);
    }, configuration.max_seconds_to_wait_on_kill * 1000);
};

process.title = configuration.process_title;
process.on('SIGTERM', killHook);
process.on('SIGINT', killHook);
```

`static/index.html`
```html
<html>
<head>
    <title>WS Test</title>
</head>
<body>
    <script src="/socket.io/socket.io.js"></script>
    <script>
    window.onload = function() {
        var socket = io.connect('http://localhost:3000');
    
        socket.on('hello', function (data) {
            document.write("<p> Hello message: " + JSON.stringify(data) + "</p>");
        });
        
        window.addEventListener("beforeunload", function() {
            console.log("Close web socket");
            socket.close();
        });
    };
    </script>
</body>
</html>
```
Just recreate the files in a directory and then execute:
```shell
npm install
npm start
```
And head your browser to [http://localhost:3000](http://localhost:3000)

**Comment by nagarjunbn8** [comment] 2016-08-20 07:50
Hi all, 
I was having the same issue..
By using **socket io 1.0.***  my errors fixed .
Hope this helps.

**Comment by nottherealbatman** [comment] 2017-02-01 15:42
Any updates on this? Because this is issue also affects Firefox 51.0.1

**Comment by vipersec** [comment] 2017-03-02 16:17
I get the same error but the connection works perfectly, strange...

**Comment by fschiefelbein** [comment] 2017-08-01 23:23
Set network.notify.ipv6 to false.

**Comment by bovas85** [comment] 2017-12-04 14:42
still an issue on firefox quantum release

**Comment by Graal46** [comment] 2017-12-05 01:25
.

**Comment by shaukatwaqarangular** [comment] 2017-12-07 16:50
@nagarjunbn 
It actually does resolve the issue for me as well.
I used the latest socket.io available:
"socket.io": "2.0.4"

and the below issue is gone:
The connection to http://localhost:55542/dist/__webpack_hmr was interrupted while the page was loading.

**Comment by cigzigwon** [comment] 2017-12-31 20:53
Firefox is fast. I'm using Riot 'before-mount'. In retrospect this is a bad idea. window.onload makes sense because you need the connection to persist before you boot your web app

**Comment by andreasvirkus** [comment] 2018-01-30 13:07
Still getting this error with `2.0.4`, Firefox Quantum (58.0), macOS 10.12.6

**Comment by cigzigwon** [comment] 2018-01-30 15:20
FF Quantum is sending a PING. Is there a socket.io handler implementation for WebSocket ping/pong? Could this be the issue?

**Comment by dizid** [comment] 2018-04-01 21:40
This error suddenly popped up in my Vue project when starting to use vuetify.
Firefox 59.0.2 (64-bit) on Ubuntu.
No errors in Chrome.
A bit later the error changed to:
Firefox can’t establish a connection to the server at http://localhost:8080/__webpack_hmr.

**Comment by tetreault** [comment] 2018-04-27 13:12
have this same issue using gatsby static site generator for react, issue only occurs in FF... I noticed it because my fonts render everywhere but FF.

**Comment by ferdinandosp** [comment] 2018-05-01 14:10
have this same exact issue using Firefox Developer edition version 60.0b16.
my app is using react...

**Comment by darrachequesne** [comment] 2018-05-02 10:59
@ferdinandosp  @tetreault which version of socket.io are you using? Does it still happen with version 2.1.0?

**Comment by racheldelman** [comment] 2018-05-09 21:46
@darrachequesne I'm using socket.io v2.1.0 and still getting that error, also using Reactjs in Firefox

**Comment by sukhdeothakur** [comment] 2018-05-26 06:47
# sukhdeothaur.96@gmail.com
<b> :</b></br>Error in Firefox</br> <b>The connection to ws://localhost:62000/chhotiduniya/demoServer.php was interrupted while the page was loading.</b>
Reply:
Use IP address(127.0.0.1) instead of localhost in client socket code
Like: "ws://<b>127.0.0.1</b>:62000/demoServer.php";
<This will cause error e.g:"ws://<b>localhost</b>:62000/demoServer.php";>

**Comment by PopovMaxim** [comment] 2018-07-24 14:30
Maybe it helps anyone... 
Also works with SSE in Firefox 61

```
$(window).on('beforeunload', function () {
     source.close();
});
```

**Comment by remdex** [comment] 2018-10-16 11:48
Added connection closing event.

**Comment by princeivankent** [comment] 2019-03-07 13:21
I am getting this warning too. Im using Vue-CLI with laravel and tried to run npm serve. The warning shows only in firefox.

**Comment by cigzigwon** [comment] 2019-03-08 03:03
@princeivankent There is definitely a difference. Before we compare our implementations let's do some discovery. In chrome my socket joins the lobby. In Firefox my socket closes, reconnects and then joins the lobby. People are suggesting that operations based on window events are a workaround which may help with edge cases but does not speak for WHAT is actually the problem. I've suggested in the linked issue above #1436, that you need to implement PING -> PONG on your server side. But the problem I'm seeing suggests that the event pipeline in Mozilla still has a flaw in Quantum which is at 65.0.1. But I'll report back with more. I'm going to try connecting after the DOM loads. I don't see that suggestion yet.

**Comment by cigzigwon** [comment] 2019-03-08 03:54
So in this case I've confirmed for myself that the issue I see only occurs on "beforeunload" like @PopovMaxim has pointed out. Things happen faster or are actually being reported in Firebug but not Chrome's inspector. But again something has variance in their event handling pipeline when transitioning pages. I'm going to wager that all server side implementations that are dealing with random disconnects are just not replying with a pong respective to ping. Also @princeivankent you are more likely dealing with race conditions in "front end world". You would need to elaborate more about the problem but I suspect that your websocket connection does persist after the page loads but you are seeing warnings when it unloads.

**Comment by cigzigwon** [comment] 2019-04-02 19:47
I still don't think this problem can mitigated within the socket.io lib. I suspect that this is a race condition due to concurrent processing in FFQ browser and that's why the "beforeunload" workaround is effective. It provides a means to close the socket when the browser is doing whatever it is doing. Why is this still open?

**Comment by tomo0613** [comment] 2019-05-21 20:02
This have to be a Firefox bug.

I used my dev-server for months without this issue (SSE).
Then, after an update, (haven't checked which, around v67, [using developer edition]), started getting this errors: "The connection to http://localhost:3000/sse was interrupted while the page was loading.", constantly roughly 2mins after connecting, even if no actions were taken.

The only workaround I find, is to reconnect (create new connection) when the error occurs.
`eventSource.addEventListener('error', onConnectionError);`

**Comment by wpitallo** [comment] 2019-07-11 20:32
Just did an update and now I am getting this too FFS :(

**Comment by shahindesigner** [comment] 2019-07-19 07:55
I forgot to write 'export default{}' in nuxt layouts. I did that and reconnect fixed the problem.

**Comment by mhurwicz** [comment] 2019-09-28 07:47
Getting this on Firefox 69.0.1 (64-bit) on Mac OSX Mojave 10.14.6

**Comment by samenz** [comment] 2019-10-06 05:44
Getting this error using Firefox 69.0.2 (64-bit) on Ubuntu 18.04. I'm using the dojo 6 framework I used dojo/cli-create-app version 6.0.1-pre to create the project. The error specifically is:
`The connection to http://localhost:9999/__webpack_hmr was interrupted while the page was loading.`

**Comment by 100ideas** [comment] 2019-11-20 19:08
fyi, Over at [webpack-hot-middleware/issues/265](https://github.com/webpack-contrib/webpack-hot-middleware/issues/265) @pstadler wrote (2017)
> This message appears in Firefox when reloading a page. This is unavoidable (because true) and not related to Quantum.

**Comment by zababurinsv** [comment] 2019-11-22 22:56
Hi i created connect with server side events.
Mozila
SSE: open
But when  connect closing 
reconnect does not occur

In chrome this working.

Server side events: open
webSocket.mjs:38 Connection break
webSocket.mjs:41 Code: 1006: 
(index):42 Event: error EventSource {url: "http://localhost:7777/connect", withCredentials: false, readyState: 0, onmessage: null, onopen: ƒ, …}
(index):44 Reconect (readyState=0)...
:7777/connect:1 Failed to load resource: net::ERR_INCOMPLETE_CHUNKED_ENCODING
(index):38 Server side events: open

**Comment by jpodpro** [comment] 2020-07-30 21:16
i was getting this with Firefox 79. since it isn't very obvious what to do the solution is to upgrade package `react-scripts` to 3.4.1

**Comment by darrachequesne** [comment] 2021-02-17 09:35
I've added a note here: https://socket.io/docs/v3/logging-and-debugging/#Error-logs-in-the-browser-console

I'm not sure there is something to fix at the Socket.IO level. Please reopen if needed.

**Closed by darrachequesne** 2021-02-17 09:35 UTC

**Comment by metacast-dev** [comment] 2021-04-05 06:26
I'm getting this error in firefox (when using mercure-hub to subscribe )
To fix it,  you have to close the event source  after getting the data from event source ( eventSource).
Here is the javascript code to fix the problem:

window.addEventListener('beforeunload', function () {
    if (eventSource != null) {
        eventSource.close();
    }
});

**Comment by q0rban** [comment] 2021-06-21 14:28
Does anyone have steps for how to replicate this? We have some customers reporting this issue in Firefox but I've been unable to replicate it. Does this happen when Firefox runs out of memory or something?

**Comment by kmoec** [comment] 2022-07-05 01:17
> Currently experiencing this issue when developing a React Native app with Expo, using `npm start` or `expo start` runs it and starts correctly, but gives a black screen and a lot of errors in the console that (as far as I can tell) are related to this.
> 
> https://i.imgur.com/csJOgJM.png

I'm experiencing exactly the same issue except my expo is running in docker.
