### ISSUE TITLE
Socket.io is emitting an event twice

### ISSUE THREAD

**Issue by rajpurohityogesh** [socketio/socket.io#4004] opened 2021-07-05 15:12 UTC
### Discussed in https://github.com/socketio/socket.io/discussions/4003

<div type='discussions-op-text'>

<sup>Originally posted by **rajpurohityogesh** July  5, 2021</sup>
Hey Techies,

I am emitting an event for a specific client from the server but it is emitting twice and the socket.on() method is executing twice on the react.js frontend which is ruining my project.

Server Side

`
socket.on("returning signal", payload => {
        console.log("Returning recieverd signal from "+socket.id+" to "+payload.callerID)
        io.to(payload.callerID).emit('receiving returned signal', { signal: payload.signal, id: socket.id });
});
`

Client-Side

`
user.socket.on("receiving returned signal", payload => {
        console.log("Getting receiving returned signal event");
        const item = peersRef.current.find(p => p.peerID === payload.id);
        item.peer.signal(payload.signal);
});
`

I used logs for debugging and "Getting receiving returned signal event" this message is printing twice on the browser console.

It's been a month so please help!!!</div>

**Comment by darrachequesne** [comment] 2021-07-06 22:07
Duplicate of https://github.com/socketio/socket.io/discussions/4003

**Closed by darrachequesne** 2021-07-06 22:07 UTC
