### ISSUE TITLE
Socket.io private chat example outdated

### ISSUE THREAD

**Issue by theSmartRed** [socketio/socket.io#4681] opened 2023-04-03 15:43 UTC
### Discussed in https://github.com/socketio/socket.io/discussions/4680

<div type='discussions-op-text'>

<sup>Originally posted by **theSmartRed** April  3, 2023</sup>
I am trying to run the private chat example following the readme instructions but I see this error trying to install the client side

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: private-messaging@0.1.0
npm ERR! Found: @vue/cli-service@undefined
npm ERR! node_modules/@vue/cli-service
npm ERR!   dev @vue/cli-service@"~4.5.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @vue/cli-service@"^3.0.0 || ^4.0.0-0" from @vue/cli-plugin-babel@4.5.19
npm ERR! node_modules/@vue/cli-plugin-babel
npm ERR!   dev @vue/cli-plugin-babel@"~4.5.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```
I am using Node 18.15 and NPM 9.5 that are the current LTS versions for both. How to fix?</div>

On the server side trying to run I see:

```
Node.js v18.15.0
Worker 1737 died
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)
Emitted 'error' event on RedisAdapter instance at:
    at Redis.onError (/Users/lelio.faieta/Documents/Sites/private-messaging/server/node_modules/socket.io-redis/dist/index.js:65:22)
    at Redis.emit (node:events:513:28)
    at Redis.silentEmit (/Users/lelio.faieta/Documents/Sites/private-messaging/server/node_modules/ioredis/built/redis/index.js:553:26)
    at Socket.<anonymous> (/Users/lelio.faieta/Documents/Sites/private-messaging/server/node_modules/ioredis/built/redis/event_handler.js:191:14)
    at Object.onceWrapper (node:events:628:26)
    at Socket.emit (node:events:525:35)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 6379
}

this is just an example since it keeps looping on this kind of error


```

**Comment by haneenmahd** [comment] 2023-04-09 19:05
I will take a look at into this issue 👍 !

**Comment by pawanmkr** [comment] 2023-04-14 02:56
> 

can you provide link to the instructions?

**Comment by haneenmahd** [comment] 2023-04-15 10:03
I could reproduce several issues in the vue project. They are
- outdated npm packages
- not supported to the new ssl provider after node v16
- outdated eslint config

On the server side, it fails to connect to the port 6379 because you aren't running a Redis server. You have run it using the command `redis-server`. See [Stackoverflow](https://stackoverflow.com/questions/8754304/redis-connection-to-127-0-0-16379-failed-connect-econnrefused)

**Comment by Ertan222** [comment] 2023-04-21 09:04
Thanks @haneenmahd for the "not supported ..... after node v16" part. I don't have much time and wants to learn about private messaging. Didn't know about the error's cause. I can use it with 16 lts right now :+1: I hope going to fix in the near future.

**Comment by haneenmahd** [comment] 2023-04-22 03:19
I'm gonna take a look into the example and let me do what I can do with it 😊!

**Comment by haneenmahd** [comment] 2023-04-30 09:10
I have opened up a new PR fixing the docs and legacy provider bug. Hope it helps future devs checking out the example. FYI, you can fix the dependency installation by adding a `-legacy-peer-deps` flag while installing.

**Comment by darrachequesne** [comment] 2023-05-03 08:20
I've bumped the dependencies in https://github.com/socketio/socket.io/commit/cbf0362476a23a573233369f1119f7e305539336, it should now work properly on Node.js 18. Could you please check?

**Comment by haneenmahd** [comment] 2023-05-04 14:08
@darrachequesne yes, it does work now! the dependencies are up-to-date.

<img width="1062" alt="Screenshot 2023-05-04 at 19 38 29" src="https://user-images.githubusercontent.com/72091386/236232726-43b7f6b2-7000-44e7-9326-3a43a2cfdfd7.png">

**Comment by darrachequesne** [comment] 2023-05-15 12:49
@haneenmahd awesome, thanks for the feedback :+1: 

I'm closing this now, please reopen if needed.

**Closed by darrachequesne** 2023-05-15 12:49 UTC
Labels: documentation
