### ISSUE TITLE
Socket "refresh" or listeners fails after shutting down server and reconnecting

### ISSUE THREAD

**Issue by thevinci** [socketio/socket.io#1633] opened 2014-06-18 00:37 UTC
I'm using a room as well here. After the server is reset, the client successfully connects but all the event listeners stop working. I am using the latest Chrome. I have the latest Socket.io 1.0.4. I see the room requests and I am sure that the client joined to room in the log but updateFn stops working.

Server code

``` javascript
socket
.on('join', function(options) {
    console.log('joined room '+options.room);
    socket.join(options.room);
});

setInterval(function() {
    socket.to('lounge', { test:'test' });
}, 3000);
```

Client code

``` javascript
socket = io.connect('/', { forceNew:true });
updateFn = function(data) { console.log('do something', data); };

socket.on('connect', function() {
    console.log('you have connected');
    socket.on('update', updateFn); // This works once and then stops after the reconnect
    socket.emit('join', {room:'lounge'});
});
```

**Comment by rase-** [comment] 2015-01-12 01:23
@thevinci does this still happen?

**Comment by sSeewald** [comment] 2015-06-07 15:28
Hi i have the same problem. 
My implementation looks like this:
1. A user connects to the site and a socket is created. (reconnection is true)
2. Server shuts down and the client script try's to reconnect
3. After 10 times the socket will be disconnected from the client side (not closed)
4. The user gets a popup to retry
5. Server is restarted
6. The user clicks the reconnect button -> this fires a socket->connect()
7. The socket works

The only thing that does not work is the "auto reconnect" after the reconnection. When the server is killed again. The socket.io client script does not try a reconnect.

**Comment by darrachequesne** [comment] 2017-01-12 15:48
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).

**Closed by darrachequesne** 2017-01-12 15:48 UTC
Labels: Closed due to inactivity

**Comment by ramalingaa** [comment] 2024-06-13 07:47
I tried adding listener again while reconnecting and it worked for me. It seems old listerner is still available for reconnects while is a stale one and passing a new listener is working.
export const connectSocket = (url: string, dispatch?: any, isReconnect = false) => {
  if (socket) return;
  if(url) {
    socket = io(url);
  connected = new Promise<void>((resolve, reject) => {
    socket?.on('connect', () => {
      resolve();
      const socketPayload = {
        id: socket?.id,
        connected: socket?.connected,
      }
      dispatch && dispatch(updateCurrentSocketObject(socketPayload));
      dispatch && dispatch(updateSocketLoading(false));
      if(isReconnect) {   
        socket?.on('bot_uttered', listener);
      }
    });
    socket?.on('connect_error', (error: any) => {
      console.error('WebSocket connection error:', error);
      reject(error);
      dispatch && dispatch(updateSocketLoading(false));
    });

    socket?.on('disconnect', () => {
      console.log('WebSocket disconnected');
      dispatch && dispatch(resetChatState());
    });
  });
  }
};

I am using above function on click events to reconnect and passing isReconnect as true.
