### ISSUE TITLE
Connecting to custom namespace connects to default namespace, too

### ISSUE THREAD

**Issue by MickL** [socketio/socket.io#3089] opened 2017-10-20 09:44 UTC
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour
`const adminSocket = io('/admin', { forceNew: true });` will connect to Namespace "/" AND "/admin". 

Using this will connect to default namespace two times: 
```
const socket = io();
const adminSocket = io('/admin', { forceNew: true });
```

Im not sure if this is by design but if yes, it did not found it in the documentation.

### Expected behaviour
Connecting to a namespace should not connect to default namespace

### Setup
- socket.io version: 2.0.3

**Comment by akashada** [comment] 2018-03-30 02:39
its by design, discussion can be found in #2124 and #2342 . the description about it in the docs is still fuzzy

**Comment by cryptogearbox** [comment] 2018-03-30 03:58
Is it also by design that when the root namespace disconnects all other related namespace disconnects also?

For example, these two IDs, yRvGKh9Svkp_yvvCAAAA and /otherNamepace#yRvGKh9Svkp_yvvCAAAA when the root yRvGKh9Svkp_yvvCAAAA ID is disconnected, it also disconnects the other namespace too.

**Comment by murrayju** [comment] 2018-04-23 23:35
The biggest problem that I have with this is, if the default namespace has some middleware that might emit an error (e.g. authentication), when the client connects to some other namespace this middleware will (correctly?) stop the connection from succeeding, but it does *not* fire the `error` event on the namespace. So to the user of the namespace, it looks like the thing is just hanging, and neither connects or disconnects.

**Comment by darrachequesne** [comment] 2021-02-20 22:43
For future readers: this was fixed in Socket.IO v3, the implicit connection to the default namespace was removed.

Documentation: https://socket.io/docs/v3/migrating-from-2-x-to-3-0/#No-more-implicit-connection-to-the-default-namespace

**Closed by darrachequesne** 2021-02-20 22:43 UTC
