### ISSUE TITLE
closeOnBeforeunload not working properly after upgrading to socketio v4.7.5

### ISSUE THREAD

**Issue by sarmad36** [socketio/socket.io#5058] opened 2024-06-24 15:54 UTC
### Discussed in https://github.com/socketio/socket.io/discussions/5055

<div type='discussions-op-text'>

<sup>Originally posted by **sarmad36** June 23, 2024</sup>
With following configuration
this.socket = io({
      closeOnBeforeunload: true,
      reconnection: true,
      reconnectionDelay: 100,
      reconnectionDelayMax: 2000,
      reconnectionAttempts: Infinity,
      transports: ["polling"],
      secure: true,
      rejectUnauthorized: false,
      forceNew: false,
      timeout: 6000,
})

when I try to leave the page on Firefox the socket connection is disconnected  and if I try to log the reason for disconnection it says " **transport error** "</div>

**Comment by darrachequesne** [comment] 2024-10-23 08:35
Duplicate of https://github.com/socketio/socket.io/discussions/5055.

**Closed by darrachequesne** 2024-10-23 08:35 UTC
